chart/docker-images.yaml
services/api/src/api/routes/webhook.py

The upstream issue has been fixed on the Hub. It's important to restore the test, because it avoids collision between datasets and models (models don't have a prefix in the webhook v1).

fix: 🐛 restore the check on the webhook payload

---

chart/docker-images.yaml
chart/static-files/openapi.json
services/worker/src/worker/asset.py
services/worker/tests/fixtures/hub.py
services/worker/tests/test_features.py

Instead of returning a string with the URL, we now return an object with: src: the URL, height and width: the dimensions of the image in pixels.
BREAKING CHANGE: 🧨 the image cell format is now an object {src, height, width}

feat: 🎸 change the format of the image cells in /first-rows

---

services/worker/poetry.lock
services/worker/src/worker/features.py
services/worker/src/worker/responses/first_rows.py
services/worker/src/worker/responses/splits.py
services/worker/tests/fixtures/datasets.py
services/worker/tests/fixtures/hub.py
services/worker/tests/responses/test_first_rows.py
services/worker/tests/responses/test_splits.py
services/worker/tests/test_features.py

Support Sequence of dicts

---

chart/docker-images.yaml
services/worker/src/worker/features.py
services/worker/src/worker/responses/first_rows.py
services/worker/tests/fixtures/datasets.py
services/worker/tests/fixtures/files.py
services/worker/tests/fixtures/hub.py
services/worker/tests/responses/test_first_rows.py
services/worker/tests/test_features.py

also: use JSONL file for tests

test: 💍 add tests for missing fields and None value

---

chart/docker-images.yaml
chart/templates/worker/first-rows/_container.tpl
chart/templates/worker/splits/_container.tpl
chart/values.yaml
workers/first_rows/README.md
workers/first_rows/src/first_rows/config.py
workers/first_rows/src/first_rows/constants.py
workers/splits/README.md
workers/splits/src/splits/config.py
workers/splits/src/splits/constants.py

Now that the canonical datasets are loaded from the Hub, DATASETS_REVISION (or HF_SCRIPTS_VERSION in datasets) is useless.

feat: 🎸 remove obsolete DATASETS_REVISION

---

chart/templates/services/admin/_container.tpl
chart/templates/services/api/_container.tpl
chart/templates/worker/first-rows/_container.tpl
chart/templates/worker/splits/_container.tpl

the token was not extracted and passed to the applications

fix: 🐛 fix hf-token

---

chart/docker-images.yaml
chart/env/prod.yaml
workers/datasets_based/poetry.lock
workers/datasets_based/pyproject.toml
workers/datasets_based/src/datasets_based/workers/parquet.py

see  https://github.com/huggingface/datasets/releases/tag/2.8.0
remove fix because https://github.com/huggingface/datasets/pull/5333 has been included in the release, and remove deprecated use_auth_token argument in download_and_prepare

feat: 🎸 upgrade datasets to 2.8.0

---

chart/.helmignore
chart/env/prod.yaml
chart/templates/_envCommon.tpl
chart/templates/ingress.yaml
chart/templates/jobs/mongodb-migration/job.yaml
chart/templates/worker/first-rows/_container.tpl
chart/templates/worker/parquet/_container.tpl
chart/templates/worker/splits/_container.tpl
chart/values.yaml

- Ignore env files in packaged charts
- Add ability to completely specify `ingress.tls`
- Automatic value for `token.secretName` if not specified
- Do not submit `mongodb-migration` job if image not specified
- Add ability to specify `imagePullPolicy`

Small tweaks on Helm charts

---

chart/docker-images.yaml
jobs/mongodb_migration/Dockerfile
services/admin/Dockerfile
services/api/Dockerfile
services/api/src/api/routes/webhook.py
workers/datasets_based/Dockerfile

We don't use the new fields for now.

feat: 🎸 update the HF webhook content

---

chart/docker-images.yaml
services/api/src/api/routes/webhook.py
services/api/tests/routes/test_webhook.py

checking the payload in details (eg if the URL field is well formed) while not using it afterward is not useful. It even lead to breaking the webhook after https://github.com/huggingface/moon-landing/pull/4477 (internal link) where the "url" field format had changed.
cc @SBrandeis @coyotte508 fyi

fix: 🐛 only check webhook payload for what we are interested in

---

.github/workflows/_quality-python.yml
chart/docker-images.yaml
jobs/mongodb_migration/Dockerfile
services/admin/Dockerfile
services/api/Dockerfile
tools/Python.mk
workers/datasets_based/Dockerfile
workers/datasets_based/poetry.lock
workers/datasets_based/pyproject.toml

to reduce the size of the docker images
Thanks @XciD

chore: 🤖 add --no-cache (poetry) and --no-cache-dir (pip)

---

chart/docker-images.yaml
workers/datasets_based/src/datasets_based/worker.py
workers/datasets_based/tests/test_worker.py

if we re-run a "DAG", all the steps will be processed, even if the first ones are skipped because the result is already in the cache.
It will fix the issue with https://github.com/huggingface/datasets-server/pull/694#issuecomment-1400568759 (we will update the datasets in the queue, and remove the duplicates, without having to re-run already computed responses).

feat: 🎸 launch children jobs even when skipped

---

chart/docker-images.yaml
libs/libcommon/src/libcommon/config.py
libs/libcommon/tests/test_processing_steps.py

`/splits` fails if any config is broken. By depending on `/split-names`, the working configs will have `/first-rows`.
Follow-up to #702

feat: 🎸 make /first-rows depend on /split-names, not /splits

---

chart/docker-images.yaml
jobs/mongodb_migration/src/mongodb_migration/collector.py
jobs/mongodb_migration/src/mongodb_migration/migrations/_20230126164900_queue_job_add_priority.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py

In this PR:
- the jobs have a new field called `priority`: `normal` (default) or `low`
- the `normal` jobs are fetched before the `low` ones (but respecting `max_jobs_per_namespace`)
- when updating a job, i.e., if a dataset has been updated again, the priority is inherited, never lowered, even if the priority field is set. This way: when launching backfill (with a low priority) on a dataset that was already waiting for update, we don't deprioritize it.
- same logic with the existing "force" field: when updating a job, if force was true, we maintain it.

Add priority field to queue

---

chart/docker-images.yaml
jobs/mongodb_migration/src/mongodb_migration/migrations/_20230126164900_queue_job_add_priority.py

See https://github.com/huggingface/datasets-server/pull/705#issuecomment-1405433714

fix: 🐛 fix migration script

---

chart/docker-images.yaml
libs/libcommon/src/libcommon/dataset.py
libs/libcommon/src/libcommon/operations.py
libs/libcommon/src/libcommon/queue.py
services/admin/src/admin/app.py
services/admin/src/admin/routes/backfill.py
services/api/src/api/routes/webhook.py
workers/datasets_based/src/datasets_based/worker.py
workers/datasets_based/tests/test_worker.py
workers/datasets_based/tests/test_worker_factory.py
workers/datasets_based/tests/workers/test__datasets_based_worker.py
workers/datasets_based/tests/workers/test_config_names.py
workers/datasets_based/tests/workers/test_dataset_info.py
workers/datasets_based/tests/workers/test_first_rows.py
workers/datasets_based/tests/workers/test_parquet.py
workers/datasets_based/tests/workers/test_parquet_and_dataset_info.py
workers/datasets_based/tests/workers/test_sizes.py
workers/datasets_based/tests/workers/test_split_names.py
workers/datasets_based/tests/workers/test_splits.py

The logic is very basic: it updates all the datasets of the Hub, with a low priority. Note that most of the jobs will be skipped, because the response will already be in the cache.
We might want to take a more detailed approach later to reduce the number of unnecessary jobs by specifically creating jobs for the missing data only.
Apart of this, the PR also fixes the creation of children jobs: the priority is preserved (ie low priority jobs created low priority children jobs)

feat: 🎸 add a /backfill admin endpoint

---

.github/workflows/_unit-tests-python.yml
libs/libcommon/src/libcommon/dataset.py
libs/libcommon/src/libcommon/operations.py
services/admin/src/admin/routes/backfill.py

As we are running a loop of updates on supported datasets, it's useless to check if the dataset is supported inside the `update_dataset` method.

fix: 🐛 don't check if dataset is supported when we know it is

---

chart/env/prod.yaml

Current status: https://grafana.huggingface.tech/d/i7gwsO5Vz/global-view?orgId=1&from=now-15m&to=now&refresh=1m&var-slo_quantile_99_5=0.995&var-slo_quantile_85=0.85&var-slo_period=7d
A lot of jobs in /first-rows (critical for the Hub) and /parquet-and-dataset-info (less critical for now, only for parquet files)

feat: 🎸 adapt number of replicas to flush the queues

---

chart/env/prod.yaml

it breaks on a new database. Disabling it until we fix the issue.

fix: 🐛 disable the mongodbMigration job for now

---

chart/env/prod.yaml
jobs/mongodb_migration/src/mongodb_migration/migrations/_20221116133500_queue_job_add_force.py
jobs/mongodb_migration/src/mongodb_migration/migrations/_20221117223000_cache_generic_response.py
jobs/mongodb_migration/src/mongodb_migration/migrations/_20230126164900_queue_job_add_priority.py

fix: 🐛 fix the migration scripts to be able to run on new base

---

.github/workflows/chart.yml
.github/workflows/e2e.yml
.github/workflows/j-migration.yml
.github/workflows/l-libcommon.yml
.github/workflows/openapi-spec.yml
.github/workflows/s-admin.yml
.github/workflows/s-api.yml
.github/workflows/w-datasets_based.yml

currently, the actions are run twice in the PRs. See https://github.com/huggingface/datasets-server/pull/757/commits/c80eeacfdb2839149ad8b7b81cdaf6b0b4fcb944 for example.

ci: 🎡 only run on PR and on main

---

workers/datasets_based/src/datasets_based/worker.py
workers/datasets_based/tests/test_worker.py

Instead of retrying for any non-successful response in the cache, we
only retry if the error is in the list of "retry-able" errors. Also:
refactor the logic and add complete tests

update the logic to skip a job

---

chart/env/dev.yaml
chart/env/prod.yaml
chart/templates/worker/first-rows/_container.tpl
chart/values.yaml
tools/docker-compose-datasets-server.yml
workers/datasets_based/README.md
workers/datasets_based/src/datasets_based/config.py
workers/datasets_based/src/datasets_based/workers/first_rows.py
workers/datasets_based/tests/workers/test_first_rows.py

Adding custom exception to fix scenarios like https://github.com/huggingface/datasets-server/issues/731

Adding custom exception when cache insert fails because of too many columns

---

front/admin_ui/app.py

Allow to force refresh some datasets

Add refresh dataset ui

---

.github/workflows/doc-pr-build.yml

This is what is done in the other HF repos on github.
This way the Delete doc github action has something to delete.
If the doc doesn't exists, the job fails

Create doc for every PR

---

Makefile
front/admin_ui/README.md
tools/docker-compose-dev-base.yml
tools/docker-compose-dev-datasets-server.yml
workers/datasets_based/src/datasets_based/worker.py
workers/datasets_based/src/datasets_based/worker_loop.py

I switched the HF endpoint to the hub-ci one and added the corresponding tokens, and fixed the docker-compose to use the right base.
Now the local dev environment from `make dev-start` works correctly.
Close https://github.com/huggingface/datasets-server/issues/765

Use hub-ci locally

---

workers/datasets_based/src/datasets_based/worker_loop.py
workers/datasets_based/tests/test_worker_loop.py

Fix type checking on WorkerLoop.loop method, when tryin to access the worker_factory's attribute app_config.
This PR fixes an issue introduced by:
- #774
```
src/datasets_based/worker_loop.py:100: error: "WorkerFactory" has no attribute "app_config"
```

Fix CI mypy error: "WorkerFactory" has no attribute "app_config"

---

.github/workflows/e2e.yml
.github/workflows/l-libcommon.yml
.github/workflows/s-admin.yml
.github/workflows/s-api.yml
.github/workflows/w-datasets_based.yml

see
https://github.com/huggingface/datasets-server/pull/775#issuecomment-1422255785.

ci: 🎡 run e2e tests only once for a push or pull-request

---

jobs/mongodb_migration/Dockerfile
services/admin/Dockerfile
services/api/Dockerfile
tools/Docker.mk
workers/datasets_based/Dockerfile
workers/datasets_based/dev.Dockerfile

Running `make e2e` locally, I had the following error:
```
=> ERROR [e2e-worker-dataset-info 11/13] RUN poetry install --no-cache                                                                                                                                                                                                    0.4s
------
> [e2e-worker-dataset-info 11/13] RUN poetry install --no-cache:
#0 0.345 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
```
Adding the path fixes the issue.

Fix dockerfiles

---

chart/templates/jobs/mongodb-migration/job.yaml

To avoid to block the uninstall process : the PVC wait for job deletion before remove.

feat: remove job after 5 minutes

---

jobs/mongodb_migration/src/mongodb_migration/config.py
libs/libcommon/src/libcommon/config.py
services/admin/src/admin/config.py
services/api/src/api/config.py
workers/datasets_based/src/datasets_based/config.py
workers/datasets_based/src/datasets_based/resources.py

if we decide to allow changing config parameters later, it will need to be explicit.
Depends on: #784

feat: 🎸 ensure immutability of the configs

---

libs/libcommon/src/libcommon/queue.py
libs/libcommon/src/libcommon/simple_cache.py
libs/libcommon/tests/test_queue.py
libs/libcommon/tests/test_simple_cache.py
services/admin/src/admin/app.py
services/admin/src/admin/routes/dataset_status.py
services/admin/tests/test_app.py

While looking at https://github.com/huggingface/datasets-server/issues/764 and https://github.com/huggingface/datasets-server/issues/736#issuecomment-1412242342, I added a new admin endpoint that gives the current status of a dataset. I think it can help to get insights about a dataset when doing support manually.
It takes a `?dataset=` parameter, ie https://dataset-server.huggingface.co/admin/dataset-status?dataset=glue
As with all the admin endpoints, it requires being authenticated as part of the huggingface org.

feat: 🎸 add a new admin endpoint: /dataset-status

---

services/worker/src/worker/job_runners/split_names_from_dataset_info.py

`get_new_splits` function is used when creating children jobs, this function was missing in the new worker `split-names-from-dataset-info`

Adding missing function on split-names-from-dataset-info worker

---

jobs/mongodb_migration/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py
services/admin/poetry.lock
services/api/poetry.lock
services/worker/README.md
services/worker/poetry.lock
services/worker/src/worker/config.py
services/worker/src/worker/executor.py
services/worker/src/worker/job_runner.py
services/worker/src/worker/main.py
services/worker/tests/conftest.py
services/worker/tests/test_executor.py
services/worker/tests/test_job_runner.py

Took @severo 's comments from https://github.com/huggingface/datasets-server/pull/827 and https://github.com/huggingface/datasets-server/pull/824
In particular:
- I moved the queue related stuff to queue.py
- I moved all the job runner related stuff to job_runner.py
- I shortened the env variable names
- I added Job.info() to avoid repeated the same error-prone dict creation over and over
- I added tests for each part that I moved

Reorganize executor

---

chart/Chart.yaml
chart/env/dev.yaml
chart/env/prod.yaml
chart/values.yaml

fix: 🐛 set the list of supported job types as a csv string

---

chart/env/prod.yaml

nearly all the jobs should be managed by the generic worker. We still reserve two workers for each job type (for now)

feat: 🎸 reduce a lot the resources used in production

---

e2e/tests/test_12_splits.py
services/worker/src/worker/job_runners/split_names_from_dataset_info.py
services/worker/src/worker/job_runners/split_names_from_streaming.py
services/worker/tests/fixtures/hub.py
services/worker/tests/job_runners/test_split_names_from_dataset_info.py
services/worker/tests/job_runners/test_split_names_from_streaming.py

Fix content response name in split_names_from_streaming and split_names_from_dataset_info from "split_names" to "splits" so that it is consistent with the response of splits worker

Renaming split-names response to splits

---

chart/env/dev.yaml
chart/env/prod.yaml

It's required for the api/admin services which were absolutely over-provisioned. And for the workers: we reduce a lot for now, since most of the datasets don't require that quantity of RAM, and we now manage the failed jobs due to OOm. We will work on a strategy to relaunch these jobs on "big" workers (to be done)

feat: 🎸 reduce the requests (and limits) in k8s resources

---

services/api/src/api/routes/endpoint.py

All the endpoints require the dataset parameter, at least, for the moment. The auth_check and the get_cache_entry_from_steps methods require dataset to be a string (None is not supported) and we have to check before that it's the case.

fix: 🐛 ensure the dataset parameter is provided in endpoints

---

chart/env/prod.yaml
chart/values.yaml

We have two new JobRunners name:
- /split-names-from-streaming -> It was previously /split-names, but it was renamed 
- /split-names-from-dataset-info -> It is a new JobRunner which is supposed to have a similar workload as /dataset-info or /parquet

Adding deploy for missing JobRunners in chart

---

chart/templates/services/api/_container.tpl
chart/values.yaml
e2e/Makefile
services/api/README.md
services/api/src/api/app.py
services/api/src/api/authentication.py
services/api/src/api/config.py
services/api/src/api/routes/endpoint.py
services/api/src/api/routes/valid.py
services/api/src/api/utils.py
services/api/tests/conftest.py
services/api/tests/test_authentication.py
tools/docker-compose-datasets-server.yml
tools/docker-compose-dev-datasets-server.yml

Set to 200ms by default and in production. See #877

feat: 🎸 add timeout when requesting Hub authentication check

---

jobs/mongodb_migration/src/mongodb_migration/collector.py
jobs/mongodb_migration/src/mongodb_migration/migrations/_20230309141600_cache_add_job_runner_version.py
jobs/mongodb_migration/tests/migrations/test_20230309141600_cache_add_job_runner_version.py
libs/libcommon/src/libcommon/simple_cache.py
libs/libcommon/tests/test_simple_cache.py
services/worker/src/worker/job_runner.py
services/worker/src/worker/job_runners/config_names.py
services/worker/src/worker/job_runners/dataset_info.py
services/worker/src/worker/job_runners/first_rows.py
services/worker/src/worker/job_runners/parquet.py
services/worker/src/worker/job_runners/parquet_and_dataset_info.py
services/worker/src/worker/job_runners/sizes.py
services/worker/src/worker/job_runners/split_names_from_dataset_info.py
services/worker/src/worker/job_runners/split_names_from_streaming.py
services/worker/src/worker/job_runners/splits.py
services/worker/tests/job_runners/test__datasets_based_worker.py
services/worker/tests/job_runners/test_config_names.py
services/worker/tests/job_runners/test_first_rows.py
services/worker/tests/job_runners/test_parquet_and_dataset_info.py
services/worker/tests/job_runners/test_split_names_from_streaming.py
services/worker/tests/job_runners/test_splits.py
services/worker/tests/test_job_runner.py
services/worker/tests/test_loop.py

According to conversation on https://github.com/huggingface/datasets-server/pull/912, worker_version needs to be an int value.
I renamed worker_version to job_runner_version as suggested in a comment in https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runner.py#L315 to keep consistency between class name and field.

Change worker_version to int job_runner_version

---

.github/workflows/_e2e_tests.yml

Note that it would not change anything because we don't e2e test the Hub sending a request to the datasets-server...

ci: 🎡 use the public key of the CI Hub

---

chart/env/dev.yaml
chart/env/prod.yaml
chart/values.yaml

Given the new job runners/ job types: `dataset-split-names-from-streaming and dataset-split-names-from-dataset-info`, we will move them to be processed in a dedicated "light" worker with 2 pods.

Adding ligth worker

---

chart/env/prod.yaml

Currently, 20 jobs are only for one namespace, blocking all the other users/datasets (220 waiting jobs). Also: moving config-names to the list of "light" jobs (even if it's not as light as the other ones, it's quick because it only creates the dataset builder.

feat: 🎸 reduce the number of allowed jobs for one namespace

---

tools/docker-compose-dev-base.yml
tools/docker-compose-dev-datasets-server.yml

- give the docker services access to the host network. It is required to be able to access a local port on the same machine,
for example.
- run 4 workers in parallel, it helps processing the jobs quicker

Access docker host

---

services/worker/src/worker/job_runners/parquet_and_dataset_info.py
services/worker/tests/job_runners/test_parquet_and_dataset_info.py

The split regex is defined at https://github.com/huggingface/datasets/blob/4db8e33eb9cf6cd4453cdfa246c065e0eedf170c/src/datasets/naming.py#L28, I updated the one used to parque parquet file paths to use it

Support splits with dots

---

services/worker/src/worker/job_runner.py
services/worker/src/worker/job_runners/config/split_names_from_dataset_info.py
services/worker/src/worker/job_runners/config/split_names_from_streaming.py
services/worker/tests/job_runners/config/test_split_names_from_dataset_info.py
services/worker/tests/job_runners/config/test_split_names_from_streaming.py

Closes https://github.com/huggingface/datasets-server/issues/963
Adding validation on split names - config level job runners to throw an error if the response of the same info has already been computed.

check if /splits-name-from-* exists before processing it 

---

.github/ISSUE_TEMPLATE/hub-dataset-viewer.yml

No need to be assigned automatically to @severo.

Remove assignee from Dataset Viewer Issue template

---

services/worker/src/worker/job_runner.py
services/worker/src/worker/job_runners/config/split_names_from_dataset_info.py
services/worker/src/worker/job_runners/config/split_names_from_streaming.py
services/worker/src/worker/job_runners/split/first_rows_from_parquet.py
services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
services/worker/tests/job_runners/config/test_split_names_from_streaming.py
services/worker/tests/job_runners/split/test_first_rows_from_parquet.py
services/worker/tests/job_runners/split/test_first_rows_from_streaming.py
services/worker/tests/test_job_runner.py

Add validation on first-rows job runners to skip compute if a similar response already exists (Parallel response split-first-rows-from-streaming vs split-first-rows-from-parquet).
I moved the validation at job runner level since we have exactly same logic for split-names-from-streaming vs split-names-from-dataset-info.
Context: https://github.com/huggingface/datasets-server/pull/988#issuecomment-1491968842

First rows skip compute if a response already exists

---

docs/source/valid.mdx
libs/libcommon/src/libcommon/dataset.py

This PR raises error when the viewer is disabled, thus making the server fail quickly instead of relying on moon-landing.
Fix #1004.

Raise error when the viewer is disabled

---

chart/env/dev.yaml
chart/env/prod.yaml

Disabling backfill Job action since it was intended to run only one time.
Later, it will be a cron job (But should backfill only missing cache records in order to avoid appending too many jobs).

Disable full backfill action

---

jobs/mongodb_migration/src/mongodb_migration/collector.py

It was missing in
https://github.com/huggingface/datasets-server/pull/1033
FYI @albertvillanova

fix: 🐛 enable the two last migrations

---

chart/templates/jobs/cache-maintenance/job.yaml

It is required to allow helm uninstall quickly if necessary.
✅ Closes: https://github.com/huggingface/datasets-server/issues/1035

fix: 🐛 reduce the k8s job TTL to 5 minutes

---

libs/libcommon/src/libcommon/queue.py
libs/libcommon/src/libcommon/state.py
libs/libcommon/src/libcommon/utils.py
libs/libcommon/tests/test_utils.py

Used for the Job unicity_id field, and for the artifact ids.
BREAKING CHANGE: 🧨 the job unicity_id has changed a bit
The only issue with the breaking change is that it could temporarily start twice the same job. Not a big issue, I think.
fixes #861

feat: 🎸 use a common function to forge unique ids

---

chart/env/prod.yaml
jobs/cache_maintenance/src/cache_maintenance/backfill.py

Also: only run backfill job every 6 hours

fix: 🐛 report backfill every 100 anaylized datasets

---

front/admin_ui/app.py

The URL is weird, but while some steps still start with `/`, we are a bit stuck with that (otherwise, the double slash would be converted to one slash, and would break the route).

fix: 🐛 fix the URL for /admin/force-refresh

---

services/worker/src/worker/job_runner_factory.py
services/worker/src/worker/job_runners/config/split_names_from_dataset_info.py
services/worker/src/worker/job_runners/split/first_rows_from_parquet.py
services/worker/tests/job_runners/config/test_split_names_from_dataset_info.py
services/worker/tests/job_runners/split/test_first_rows_from_parquet.py

split-names-from-dataset-info and first-rows-from-parquet don't need to inherit from DatasetsBasedJobRunner, changing to JobRunner

Fix parent class for split-names-from-dataset-info and first-rows-from-parquet

---

chart/env/prod.yaml

Reduce the overcommitment to avoid having too many nodes killed by was. I also reduced a lot the number of workers, because we currently don't need as many.

Overcommit a bit less

---

services/worker/src/worker/job_runner.py
services/worker/src/worker/job_runners/_datasets_based_job_runner.py

Small fix for https://github.com/huggingface/datasets-server/pull/1146#discussion_r1191621514
We don't need to initialize job_manager attributes on job_runner

Removing non necessary attributes in job runner init

---

services/api/src/api/routes/rows.py

See
https://github.com/huggingface/moon-landing/pull/6300#issuecomment-1547590109 for reference (internal link).

fix: 🐛 don't fill truncated_cells w/ unsupported cols on /rows

---

front/admin_ui/app.py

to fix errors when duckdb tries to cast the columns like "started_at"
(already deployed on HF - I ran my tests there ^^')

Set datetime types in admin ui

---

libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py

Now we get the value as expected. This means that the backfill function will create jobs at the same level of priority, instead of moving everything to the NORMAL priority queue

fix: 🐛 the started jobinfo always contained priority=NORMAL

---

jobs/mongodb_migration/src/mongodb_migration/collector.py

we missed this migration, which leads to still having 5,000 pending jobs for this step in the Grafana charts, while these jobs don't exist now.

feat: 🎸 delete metrics for /split-names-from-streaming

---

libs/libcommon/src/libcommon/config.py
libs/libcommon/src/libcommon/processing_graph.py
services/api/src/api/app.py
services/api/src/api/config.py
services/api/src/api/routes/rows.py
services/api/tests/conftest.py
services/api/tests/fixtures/fsspec.py
services/api/tests/routes/test_rows.py
services/worker/tests/conftest.py
tools/docker-compose-datasets-server.yml
tools/docker-compose-dev-datasets-server.yml

Step 2 of https://github.com/huggingface/datasets-server/issues/1186
I implemented ParquetIndexWithMetadata (new) and ParquetIndexWithoutMetadata (from the existing code).:
- ParquetIndexWithMetadata is used when `config-parquet-metadata` is cached and is fast
- ParquetIndexWithoutMetadata is the old code, that runs when `config-parquet-metadata` is not available yet
I think in the long run we should remove ParquetIndexWithoutMetadata. I just kept it so that the UI doesn't show an error when `config-parquet-metadata` is not available.
I re-added support for image and audio for the ParquetIndexWithMetadata

Use parquet metadata in /rows

---

chart/env/prod.yaml
libs/libcommon/src/libcommon/simple_cache.py

the idea is to reduce the number of pending jobs, currently we have > 200,000 jobs, from a lot of different datasets.
And as it seems like a cause of the issues with the queue is that concurrent backfill processes run at the same time for the same dataset, we reduce the concurrency drastically to 1 job per namespace (we don't have a way to limit per dataset, for now)

Reduce number of concurrent jobs in namespace

---

services/api/src/api/routes/rows.py

including text, audio and full hd image datasets

Use parquet metadata for more datasets

---

chart/templates/_envNumba.tpl
chart/templates/services/api/_container.tpl
tools/docker-compose-base.yml
tools/docker-compose-datasets-server.yml
tools/docker-compose-dev-base.yml

this should fix issues when importing librosa in the API (it causes issues in /rows for audio datasets)

Add numba cache to api

---

services/api/src/api/routes/endpoint.py

As per discussion in https://github.com/huggingface/moon-landing/pull/6332#discussion_r1202989143
Fake data will be hardcoded on the server side so that it is consistent with what API returns and what we show in the UI.
NOTE.- This is a temporal solution, once https://github.com/huggingface/datasets-server/issues/1087 is implemented, this code can be removed.

Adding temporal hardcoded data for opt in/out: laion/laion2B-en and kakaobrain/coyo-700m

---

libs/libcommon/src/libcommon/queue.py
libs/libcommon/src/libcommon/state.py
libs/libcommon/src/libcommon/utils.py
libs/libcommon/tests/state/test_objects.py
libs/libcommon/tests/state/test_plan.py
libs/libcommon/tests/state/utils.py
libs/libcommon/tests/test_queue.py
services/api/src/api/routes/endpoint.py

Do only one request to mongo to delete multiple jobs, instead of one per job deletion.

Reduce requests to mongo (deleteMany)

---

libs/libcommon/src/libcommon/queue.py
libs/libcommon/src/libcommon/state.py
libs/libcommon/tests/state/test_objects.py
libs/libcommon/tests/state/test_plan.py

when backfilling a new revision, all pending jobs for other revisions (be it started or waiting) are canceled.

fix: 🐛 delete pending jobs for other revisions

---

services/worker/src/worker/job_manager.py

instead of finishing all the jobs with CANCELLED though backfill(), first finish the job with SUCCESS or ERROR, then backfill.

fix: 🐛 finish the job before backfilling, to get the status

---

services/admin/src/admin/app.py
services/admin/src/admin/routes/cancel_jobs.py
services/admin/src/admin/routes/force_refresh.py
services/admin/tests/test_app.py
services/admin/tests/test_app_real.py

As discussed with @severo, this PR fixes the missing slash in some admin endpoints, e.g.: 
- https://datasets-server.huggingface.co/admin/force-refreshdataset-config-names
After this PR, it will be:
- https://datasets-server.huggingface.co/admin/force-refresh/dataset-config-names
Related to:
- #1246

Fix missing slash in admin endpoints

---

services/worker/poetry.lock
services/worker/pyproject.toml

Move `pytest-asyncio` dependency from main to dev category.
This was introduced by:
- #1044

Move pytest-asyncio dependency from main to dev

---

libs/libcommon/src/libcommon/config.py
libs/libcommon/tests/test_processing_graph.py
services/api/src/api/routes/valid.py
services/api/tests/routes/test_valid.py

we were only considering a dataset supports the dataset viewer when the first-rows were generated with the "streaming" mode.

fix: 🐛 dataset viewer is valid if any of first-rows work

---

docs/source/quick_start.mdx

Removes the extra "Access parquet files" section in the quickstart.

[docs] Fix quickstart

---

chart/env/prod.yaml

We have long-lasting jobs due to the refresh of all the datasets that had the "GatedExtraFieldsError" (see #1298).

feat: 🎸 increasing the number of pods to process the queue

---

services/worker/src/worker/job_runners/split/first_rows_from_parquet.py

It must be split-first-rows-from-streaming, not config-split-names-from-info

fix: Parallel job runner for split-first-rows-from-parquet

---

chart/env/prod.yaml

also: increase the number of started jobs per namespace, because the remaining jobs are only for a small number of datasets

feat: 🎸 reduce the number of workers

---

chart/env/prod.yaml

(only increased to 1000, which is a lot more than the max number of started jobs). I think that we don't need this restriction anymore, because the jobs are limited in time, and the datasets with less started job are already prioritized. I think that the code could be removed at one point (let's first see how it goes), which would simplify the queries to mongo

feat: 🎸 disable the limit per namespace

---

services/worker/src/worker/job_runners/_datasets_based_job_runner.py
services/worker/tests/job_runners/test__datasets_based_worker.py

Generate random cache subdirectory for dataset job runner.
This might fix the stale file handle error:
```
OSError: [Errno 116] Stale file handle
```
See: https://huggingface.co/datasets/tapaco/discussions/4

Generate random cache subdirectory for dataset job runner

---

chart/static-files/openapi.json
libs/libcommon/src/libcommon/config.py
libs/libcommon/src/libcommon/processing_graph.py
libs/libcommon/tests/test_processing_graph.py
services/api/src/api/routes/valid.py
services/api/tests/routes/test_valid.py
services/api/tests/test_app.py

Change the response of `/valid`, from:
```json
{
"valid": ["datasets", "that", "have", "/first-rows"]
}
```
to
```json
{
"preview": ["datasets", "that", "only", "have", "/first-rows"],
"viewer": ["datasets", "that", "have", "/rows", "and", "/size"],
"valid": ["preview", "and", "viewer"]
}
```
Note that `valid` is the same as before, and will be removed in a future PR, once the Hub has been updated to use "preview" and "viewer".
I propose to first try this. If it works, we will remove the `valid` field, update the docs (https://huggingface.co/docs/datasets-server/valid) and do the same switch for `/is-valid`.

refactor: 💡 rename required_by_dataset_viewer: enables_preview

---

front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
services/admin/poetry.lock
services/api/poetry.lock
services/api/pyproject.toml
services/worker/poetry.lock

After 2.13.0 datasets release, update dependencies on it.
Note that I have also removed the explicit dependency on `datasets` from `services/api`,
- see commit: https://github.com/huggingface/datasets-server/commit/a2c0cd908b45a7065d936964c4d0477143146d6c
This is analogous to what was previously done on `services/worker`.
- See discussion: https://github.com/huggingface/datasets-server/pull/1147#issuecomment-1539883057
- See commit: https://github.com/huggingface/datasets-server/pull/1147/commits/4163a18ec561ddf93f93c096d76c2b06cf652f4d
Fix #1370.

Update datasets dependency to 2.13.0 version

---

docs/source/_toctree.yml
docs/source/analyze_data.mdx
docs/source/quick_start.mdx

Based on @mishig25's [feedback](https://huggingface.slack.com/archives/C0311GZ7R6K/p1684484245379859), this adds:
- a response to the code snippets in the Quickstart
- an end-to-end example of using `/parquet` to get a dataset, analyze it, and plot the results
- button to open in a Colab notebook to run examples right away

[docs] Improvements

---

tools/docker-compose-dev-base.yml

This is required to connect to the local DB instance on Linux; it is already added to `tools/docker-compose-dev-datasets-server.yml`

Add Docker internal to extra_hosts

---

jobs/mongodb_migration/src/mongodb_migration/collector.py
jobs/mongodb_migration/tests/test_deletion_migrations.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py

Adding a condition TTL index in  Job document.
It will only delete those records with a final state of SUCCESS, ERROR or CANCELLED

Modify TTL index condition

---

services/worker/src/worker/job_runners/config/parquet_and_info.py

In prod I got an ArrowInvalid when instantiating a pq.ParquetFile for bigcode/the-stack-dedup even though all the parquet files are valid (I ran a script and checked I could get all the pq.ParquetFile objects)

Retry get_parquet_file_and_size

---

services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/tests/fixtures/files.py
services/worker/tests/fixtures/hub.py
services/worker/tests/job_runners/config/test_parquet_and_info.py

It adds a test on the concurrency of job runners on the step `config-parquet-and-info`(which creates `refs/convert/parquet` and uploads parquet files), to detect when the lock is not respected, leading to `CreateCommitError`.
Also:
- group all the code that accesses the Hub inside the lock (create the "branch", send the commit, get the list of files)
- retry "hf_api.list_repo_refs" on connection error (I saw it during the tests)
- adapt the sleep intervals
---
First: tests should fail (https://github.com/huggingface/datasets-server/actions/runs/5335283399/jobs/9668277338)
```
FAILED tests/job_runners/config/test_parquet_and_info.py::test_concurrency - huggingface_hub.utils._errors.HfHubHTTPError: 500 Server Error: Internal Server Error for url: …
```

Test concurrency in parquet and info

---

e2e/tests/test_11_api.py
libs/libcommon/src/libcommon/parquet_utils.py
services/api/src/api/routes/rows.py
services/api/tests/routes/test_rows.py
services/worker/src/worker/job_runners/split/first_rows_from_parquet.py

I noticed some datasets have a slow pagination like https://huggingface.co/datasets/mlfoundations/datacomp_1b that times out.
This is because there was a regression in https://github.com/huggingface/datasets-server/pull/1287 where it wouldn't use the parquet metadata because `get_best_response` returns the first successful response

Fix regression: use parquet metadata when possible

---

jobs/mongodb_migration/src/mongodb_migration/database_migrations.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/src/libcommon/simple_cache.py
libs/libcommon/tests/test_simple_cache.py
services/worker/src/worker/job_manager.py
services/worker/src/worker/job_runners/config/opt_in_out_urls_count.py
services/worker/src/worker/job_runners/dataset/info.py
services/worker/src/worker/job_runners/dataset/opt_in_out_urls_count.py
services/worker/src/worker/job_runners/dataset/parquet.py
services/worker/src/worker/job_runners/dataset/size.py
services/worker/tests/test_executor.py

Remove too restrictive `__all__` from `libcommon/simple_cache`:
- it contained only one attribute: `DoesNotExist`
- Python considers as private all the module attributes which are not defined in `__all__`
```
from libcommon.simple_cache import upsert_response
Warning: Accessing a protected member of a class or a module:
'upsert_response' is not declared in __all__
```

Remove too restrictive __all__ definitions

---

jobs/cache_maintenance/tests/test_collect_metrics.py
jobs/mongodb_migration/src/mongodb_migration/collector.py
jobs/mongodb_migration/src/mongodb_migration/migrations/_20230622131500_lock_add_owner.py
jobs/mongodb_migration/tests/migrations/test_20230622131500_lock_add_owner.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_backfill.py
libs/libcommon/tests/test_orchestrator.py
libs/libcommon/tests/test_queue.py
services/admin/src/admin/routes/force_refresh.py
services/api/tests/routes/test_endpoint.py
services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/src/worker/loop.py
services/worker/tests/test_job_manager.py
services/worker/tests/test_loop.py

To avoid multiple job runners getting the same job at the same time, for a given unicity_id (identifies job type + parameters):
- a lock is used during the update of the selected job
- we ensure no other job is already started
- we select the newest (in date order) job from all the waiting jobs and start it (status, started_at)
- we cancel all the other waiting jobs
Should fix #1323.

Ensure only one job is started for the same unicity_id

---

chart/Chart.yaml
chart/templates/_envWorker.tpl
libs/libcommon/src/libcommon/config.py
services/worker/src/worker/job_runners/split/duckdb_index.py

Error `duckdb.IOException: IO Error: Failed to create directory \"//.duckdb\"!\n `
is shown when computing duckdb index.

Set Duckdb extensions install directory

---

libs/libcommon/src/libcommon/config.py
libs/libcommon/tests/test_processing_graph.py

Previously, `split-duckdb-index` was triggered only by `config-split-names-from-info` but when this step finished with error 500 because of ResponseAlreadyComputedError, `split-duckdb-index` never started.
Adding other parents to avoid skipping job compute. 
Note that  the issue with parallel processing steps will remain and should be fixed on https://github.com/huggingface/datasets-server/issues/1358

Adding other processing steps

---

chart/Makefile

The path to staging environment in the Makefile was outdated (the name was changed from `dev` to `staging`)

Update quality target in Makefile for /chart

---

libs/libcommon/src/libcommon/operations.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py
services/admin/src/admin/routes/dataset_backfill.py
services/admin/src/admin/routes/force_refresh.py

webhook and jobs created when a requested cache entry is missing are the only ones with Priority.NORMAL. All the jobs created by administrative tasks (/force-refresh, /backfill, backfill job...) will use Priority.LOW.

feat: 🎸 use Normal priority only for API

---

jobs/mongodb_migration/src/mongodb_migration/migrations/_20230703110100_cache_add_partial_field_in_config_parquet_and_info.py
jobs/mongodb_migration/tests/migrations/test_20230703110100_cache_add_partial_field_in_config_parquet_and_info.py
services/worker/src/worker/dtos.py
services/worker/src/worker/job_runners/config/info.py
services/worker/src/worker/job_runners/config/parquet.py
services/worker/src/worker/job_runners/config/parquet_metadata.py
services/worker/src/worker/job_runners/config/size.py
services/worker/src/worker/job_runners/dataset/info.py
services/worker/src/worker/job_runners/dataset/parquet.py
services/worker/src/worker/job_runners/dataset/size.py
services/worker/tests/job_runners/config/test_info.py
services/worker/tests/job_runners/config/test_parquet.py
services/worker/tests/job_runners/config/test_parquet_metadata.py
services/worker/tests/job_runners/config/test_size.py
services/worker/tests/job_runners/dataset/test_info.py
services/worker/tests/job_runners/dataset/test_parquet.py
services/worker/tests/job_runners/dataset/test_size.py

Following #1448 we need all subsequent jobs to `config-parquet-and-info` to have the "partial" field:
- "config-parquet-and-info"
- "config-parquet"
- "dataset-parquet"
- "config-parquet-metadata"
- "config-info"
- "dataset-info"
For dataset level jobs, "partial" is True if there is at least one config with "partial == True".
I updated the code of all the jobs and update the migration job to add "partial" to existing entries.
I'll update the docs in another PR.

Add partial to subsequent parquet-and-info jobs

---

chart/env/prod.yaml

Following #1448 
note that `cache-maintenance` took care of running a backfill for the datasets >5GB:
```
"DatasetTooBigFromDatasetsError,DatasetTooBigFromHubError,DatasetWithTooBigExternalFilesError,DatasetWithTooManyExternalFilesError"
```

More workers

---

services/worker/src/worker/dtos.py
services/worker/src/worker/job_runners/config/size.py
services/worker/src/worker/job_runners/dataset/size.py

Because `download_size` is `None` in `config-and-parquet-info` if the dataset is >5GB

Optional num_bytes_original_files

---

libs/libcommon/src/libcommon/config.py
services/worker/README.md
services/worker/src/worker/config.py
services/worker/src/worker/job_runners/split/duckdb_index.py

Moving config to worker folder since it is not used from any other project.
Also adding doc in the readme file.

split-duckdb-index config

---

libs/libcommon/src/libcommon/viewer_utils/asset.py

FileNotFoundError can happen because of concurrent api calls, and we can ignore it
(found this error while checking some logs today)

Minor fix in update_last_modified_date_of_rows_in_assets_dir

---

libs/libapi/src/libapi/utils.py
libs/libcommon/src/libcommon/parquet_utils.py
services/rows/src/rows/routes/rows.py

I'd like to understand better why specific requests take so long (eg refinedweb, the-stack).
Locally they work fine but take too much time in prod.

More logging for /rows

---

chart/env/prod.yaml

Because it causes an OOM for all the big parquet datasets like the-stack, refinedweb etc.
causing their pagination to hang because it uses the parquet index without metadata which is too slow for big datasets

Don't run config-parquet-metadata in light workers

---

chart/env/prod.yaml
chart/env/staging.yaml
chart/values.yaml
libs/libcommon/src/libcommon/queue.py

note that the limits (min and max) will always be set in the mongo queries. I also added an index to make it quick but let's see if it works well.

fix: 🐛 ensure the env vars are int

---

chart/env/prod.yaml
chart/env/staging.yaml
chart/templates/_initContainerCache.tpl
chart/templates/_initContainerDuckDBIndex.tpl
chart/templates/_initContainerParquetMetadata.tpl
chart/templates/_volumeCache.tpl
chart/templates/_volumeDuckDB.tpl
chart/templates/_volumeParquet.tpl
chart/templates/services/rows/deployment.yaml
chart/templates/worker/_deployment.yaml
chart/values.yaml

Related to https://github.com/huggingface/datasets-server/issues/1407
Adding new volumes for: cache (datasets library), parquet and duckdb
Based on https://github.com/huggingface/infra/pull/607, the persistenceVolumeClaims should be:
- datasets-server-cache-pvc
- datasets-server-parquet-pvc
- datasets-server-duckdb-pvc
I think it depends on https://github.com/huggingface/infra/pull/607/files to be merged/implemented first.

Adding EFS volumes for cache, parquet and duckdb storage

---

libs/libcommon/src/libcommon/parquet_utils.py

It was causing the workers memory to keep increasing and finally OOM.
If there are still memory errors after that I might remove the LRU cache altogether

Reduce rows lru cache

---

services/worker/src/worker/job_runners/config/parquet_metadata.py
services/worker/tests/job_runners/config/test_parquet_metadata.py

I moved some code to make the job write the parquet metadata on disk as they are downloaded, instead of keeping them all in RAM and write them all at the end.
should help for https://github.com/huggingface/datasets-server/issues/1502

Memory efficient config-parquet-metadata

---

libs/libcommon/src/libcommon/queue.py

Syncing advised indexes by Mongo Atlas and removing not used index (Replaced with a new one).

Sync advised indexes by Atlas

---

libs/libcommon/src/libcommon/viewer_utils/parquet_metadata.py
services/worker/src/worker/job_runners/config/parquet_metadata.py
services/worker/tests/job_runners/config/test_parquet_metadata.py

Since we added partial conversion to parquet, we introduced the new config/split/ssss.parquet paths but the parquet metadata worker was nos following it and therefore splits could overwrite each other
This affects any dataset with partial conversion and multiple splits, e.g. c4
Related tohttps://github.com/huggingface/datasets-server/issues/1483

Separate parquet metadata by split

---

e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/worker/poetry.lock

Update `certifi` to 2023.7.22 in poetry lock files
Fix #1556

Update certifi to 2023.7.22

---

e2e/poetry.lock

Update locked `cachecontrol` version from yanked 0.13.0 to 0.13.1 in `e2e` subpackage.
Related to:
- #1344

Update locked cachecontrol yanked version in e2e

---

chart/env/prod.yaml

it will allocate less pods per node. We regularly have OOM errors, with pods that use 3, 5, 6, 7 GiB RAM, and the node has not enough RAM left for them.

feat: 🎸 request 4Gi per /rows pod

---

DEVELOPER_GUIDE.md

Add to `DEVELOPER_GUIDE` docs how to set up local development environment with Poetry version 1.4.2, the same as in CI.
Fix #1565.

Document setting up local dev env with same Poetry version as CI

---

services/worker/tests/job_runners/split/test_opt_in_out_urls_scan_from_streaming.py

Related to https://github.com/huggingface/datasets-server/issues/1085.
Temporarily disabling real test for spawning API to unblock external PRs like https://github.com/huggingface/datasets-server/pull/1570

Skip real test

---

services/search/src/search/routes/search.py

Currently /search is throwing error:
```
File "/src/services/search/src/search/routes/search.py", line 91, in download_index_file
hf_hub_download(
File "/src/services/search/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "/src/services/search/.venv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1159, in hf_hub_download
os.makedirs(storage_folder, exist_ok=True)
File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/local/lib/python3.9/os.py", line 225, …
```

fix: /search - set cache directory when download index

---

e2e/tests/test_11_api.py
e2e/tests/test_52_search.py
e2e/tests/utils.py
services/worker/tests/fixtures/hub.py
services/worker/tests/job_runners/config/test_split_names_from_streaming.py
services/worker/tests/job_runners/split/test_first_rows_from_streaming.py
services/worker/tests/job_runners/split/test_image_url_columns.py
services/worker/tests/job_runners/split/test_opt_in_out_urls_scan_from_streaming.py
services/worker/tests/job_runners/test__job_runner_with_cache.py
services/worker/tests/job_runners/test__job_runner_with_datasets_cache.py
services/worker/tests/test_job_manager.py

Fix default config name and refactor:
- the function no longer uses the argument `dataset`
- it returns a 2-tuple
Fix partially #1589.

Fix default config name

---

services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/tests/fixtures/hub.py

Fix the filename of cached files, so that it contains the `builder.dataset_name` instead of `builder.name`.
Fix partially #1589.

Fix cached filenames

---

services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/tests/job_runners/config/test_parquet_and_info.py

Fix usage of `HfFileSystem` (instead of `HTTPFileSystem`) and filename format of `data_files`.
Additionally, fix `fill_builder_info` with additional builder information: `builder_name`, `dataset_name`, `config_name` and `version`.
Fix partially #1589.

Fix HfFileSystem

---

e2e/tests/test_16_statistics.py

Fix e2e `test_16_statistics`. as this file was added after branch (https://github.com/huggingface/datasets-server/tree/update-datasets-2.14) was created from main.
This fix is necessary after the refactoring introduced by:
- #1616

Fix e2e test_16_statistics

---

chart/env/prod.yaml
chart/env/staging.yaml

In order to try correct functionality of delete-index job, I would like to test every 10 minutes.
Then I will remove this schedule and will keep as default (once a day).

Enable delete-indexes job to run every 10 minutes

---

chart/Chart.yaml
chart/env/staging.yaml
chart/templates/_common/_helpers.tpl
chart/templates/cron-jobs/delete-indexes/_container.tpl
chart/templates/cron-jobs/delete-indexes/job.yaml

Staging deploy fails with message:
```
one or more objects failed to apply, reason: CronJob in version "v1" cannot be handled as a CronJob: json: cannot unmarshal number into Go struct field EnvVar.spec.jobTemplate.spec.template.spec.containers.env.value of type string
```

Try to fix delete indexes job

---

jobs/cache_maintenance/src/cache_maintenance/main.py

It should not be initialized for other actions like backfill or collect-metrics.

Init duckdb storage only for delete-indexes action

---

chart/env/prod.yaml
chart/env/staging.yaml

- delete indexes job will run at 00:00 for staging and prod (default in values.yaml)
- expiredTimeIntervalSeconds: 259_200 # 3 days for prod

Set default env values for staging and prod - delete indixes

---

chart/env/prod.yaml

because nodes have only 16RAM -> we want two pods per node

feat: 🎸 reduce RAM from 8 to 7GiB for rows and search services

---

chart/env/prod.yaml

because no nodes can provide this in the current setup

feat: 🎸 reduce the number of cpus for storage admin

---

services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/src/worker/job_runners/config/split_names_from_streaming.py
services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
services/worker/src/worker/utils.py

Once we update `datasets` to version 2.14.4, we no longer need the authentication tweaks (where we had to use `download_config` instead of `token`) introduced by:
- #1620
Fix #1659.

Revert datasets authentication with DownloadConfig

---

.spectral.yml
.vscode/monorepo.code-workspace
chart/values.yaml
docs/source/openapi.json
e2e/tests/test_12_splits.py
e2e/tests/test_13_first_rows.py
e2e/tests/utils.py
libs/libcommon/src/libcommon/exceptions.py
libs/libcommon/src/libcommon/utils.py
services/rows/src/rows/routes/rows.py
services/worker/src/worker/dtos.py
services/worker/src/worker/job_runners/config/split_names_from_info.py
services/worker/src/worker/job_runners/config/split_names_from_streaming.py
services/worker/src/worker/job_runners/dataset/split_names.py
services/worker/tests/job_runners/config/test_config_job_runner.py
services/worker/tests/job_runners/dataset/test_dataset_job_runner.py
services/worker/tests/job_runners/split/test_split_job_runner.py

Missing:
In other PRs:
- document all the X-Error-Code in OpenAPI -> #1671 
- do contract testing on the OpenAPI examples. Maybe use a new field, like `x-contract-testing-url`, to get the URL to test programmatically. Also: create permanent test datasets (like severo/private) in prod that can be used to contract test in prod? -> #518 
- generate OpenAPI spec from the code -> #1670
- test authenticated against authorized, and maybe add examples in the openapi spec -> in #1656

fix: 🐛 update the OpenAPI spec

---

chart/env/prod.yaml
chart/env/staging.yaml

It will be   `schedule: "13 00 * * *"` as default in values.yaml

Set cache metrics cron schedule to default value

---

docs/source/openapi.json

I made these changes by looking at how the Typescript types are created with https://github.com/oazapfts/oazapfts (that we use on the Hub).

fix: 🐛 fix the optional types in OpenAPI

---

chart/env/prod.yaml
e2e/tests/test_31_admin_metrics.py
jobs/cache_maintenance/src/cache_maintenance/queue_metrics.py
jobs/cache_maintenance/tests/test_collect_queue_metrics.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_orchestrator.py
libs/libcommon/tests/test_queue.py
libs/libcommon/tests/utils.py

Currently, queue metrics are getting wrong values and sometimes negative.
It could be related to an issue with jobs being processed more than one time by different workers https://github.com/huggingface/datasets-server/issues/1467.
Rollbacking incremental queue metrics until job processing issues have been solved.
Note that I changed the cron schedule back to two minutes (as it was before https://github.com/huggingface/datasets-server/pull/1684)

Rollback queue incremental metrics

---

libs/libcommon/src/libcommon/simple_cache.py

It will be added again in the next deploy as:
```
{
"fields":["kind", "http_status", "error_code"],
"unique": True
}
```
(In another PR)

Temporarily delete cache metric index

---

services/worker/src/worker/job_runners/split/duckdb_index.py
services/worker/tests/fixtures/hub.py
services/worker/tests/job_runners/split/test_duckdb_index.py

Fixes https://github.com/huggingface/datasets-server/issues/1686
Using hf_download instead of loading parquet files to duckdb directly.

Download parquet in split-duckdb-index

---

chart/env/prod.yaml

Has tons of data files and is updated every day.
12k commits already in
https://huggingface.co/datasets/KakologArchives/KakologArchives/tree/refs%2Fconvert%2Fparquet
Let's block it until we have a better way of handling big datasets with frequent updates

Block KakologArchives/KakologArchives

---

jobs/mongodb_migration/src/mongodb_migration/migrations/_20230825170200_lock_add_ttl.py
jobs/mongodb_migration/tests/migrations/test_20230825170200_lock_add_ttl.py
libs/libcommon/src/libcommon/queue.py

Added the `ttl` parameter to `lock()`.
(ony supported value is 600 though, which is the value of the TTL index in mongo - but this extendable for later if needed)
Close https://github.com/huggingface/datasets-server/issues/1727

Add TTL for unicity_id locks

---

chart/env/prod.yaml

The search is now in production in the Hub, so we need to increase the number of pods

feat: 🎸 increase the number of pods for /search

---

chart/env/prod.yaml
services/worker/src/worker/job_runners/config/parquet_and_info.py

The 800+ datasets with 60+ configs each have been updated which has filled up the queue to the point that the other datasets are not processed as fast as they should.
Blocking them for now, until we have a better way to handle them

Block open-llm-leaderboard

---

front/admin_ui/app.py

when the dataset status query returns errors (eg today when whoami-v2 was down)

Add error message in admin app

---

services/worker/src/worker/job_runners/split/duckdb_index.py
services/worker/tests/job_runners/split/test_duckdb_index.py

Duckdb does support indexing nested data so we're all good on that side already.
Therefore I simply improved the indexable column detection to check for nested data.
The old code used to index all the columns as long as there is at least one non-nested string column though, so we just need to refresh the datasets with the "no indexable columns" error.
Close https://github.com/huggingface/datasets-server/issues/1710

Search for nested data

---

libs/libcommon/src/libcommon/rows_utils.py
libs/libcommon/src/libcommon/viewer_utils/asset.py
libs/libcommon/src/libcommon/viewer_utils/features.py
libs/libcommon/tests/viewer_utils/test_features.py
services/rows/src/rows/routes/rows.py
services/search/src/search/routes/search.py
services/worker/tests/fixtures/hub.py

Using this code I can run `to_rows_list` in less than 2sec on 100 wav files of 1.5MB (from 20sec before).
I chose to stop converting to WAV and only send the MP3 file to the user, and to parallelize the audio conversions.
This should enable the viewer on audio datasets for both /rows and /search :)
Though to try this feature on /rows I first enabled it on `arabic_speech_corpus` and will enable it on all datasets if it works fine
Note: this can probably be improved later, e.g. by avoiding unnecessary conversions

Support audio in rows and search

---

chart/templates/_env/_envWorker.tpl
chart/values.yaml
services/worker/src/worker/config.py
services/worker/src/worker/job_manager.py

and block `alexandrainst/nota`, see [internal slack thread](https://huggingface.slack.com/archives/C04L6P8KNQ5/p1693548446825959)
The idea is to never process anything for blocked datasets. I also chose to not store anything in the cache in this case

Add blockedDatasets variable

---

chart/env/prod.yaml

8GB -> 16GB
Fixes (hopefully) https://github.com/huggingface/datasets-server/issues/1758
Idk what kind of pods we have though, we might have to double check it's not too much
It should be enough to perform the indexing of datasets (up to 5GB which is the max)

More memory for workers

---

chart/env/prod.yaml

because the nodes have 32GB RAM, and we cannot fit 2x 16GB due to the small overhead kubenetes requires aside of the pods.
cc @lhoestq

feat: 🎸 reduce the max ram

---

chart/env/prod.yaml

Following https://github.com/huggingface/datasets-server/pull/1769
since deployed failed again because there are no nodes available. Sureley because /rows can't run on nodes made for dataset workers.
I also reduced the amount of uvicorn workers in case it was the reason the pods were OOMing (too many parallel calls)

Less rows workers and less uvicorn workers

---

services/rows/src/rows/routes/rows.py

It's now working at correct speed, e.g. https://huggingface.co/datasets/arabic_speech_corpus/viewer/clean/train?p=1 takes only a few seconds. It was only enabled on this dataset for testing purposes.
Following #1788 
Fixes (hopefully once and for all) https://github.com/huggingface/datasets-server/issues/1255

Enable audio in the Dataset Viewer pagination

---

chart/env/prod.yaml
chart/env/staging.yaml

This reverts commit 66d755eb3f020e7a46866919c636387d46756ff5.
to let 48h to the user to respond before we block
following https://github.com/huggingface/datasets-server/pull/1791#issuecomment-1711357091

Revert "feat: 🎸 disable the viewer for org CyberHarem (#1791)"

---

services/worker/src/worker/job_runners/split/descriptive_statistics.py

While reviewing https://github.com/huggingface/datasets-server/issues/1443 I found that for the first error AttributeError, there is a minor bug in split-descriptive-statistics, it fails when features include list (sequences).
After this fix, we should force-refresh cached records for:
```
db.cachedResponsesBlue.countDocuments({error_code:"UnexpectedError", "details.copied_from_artifact":{$exists:false}, "details.cause_exception":"AttributeError",kind:"split-descriptive-statistics"})
9748
```

fix: split-descriptive-statistics fails for datasets with list features

---

e2e/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/worker/poetry.lock

Update `gitpython` to 3.1.36 version to fix the CVE-2023-41040 vulnerability.
Fix #1785.

Update gitpython to 3.1.36 version

---

libs/libcommon/src/libcommon/exceptions.py
services/worker/src/worker/job_runners/config/config_job_runner.py
services/worker/src/worker/job_runners/split/descriptive_statistics.py
services/worker/src/worker/job_runners/split/duckdb_index.py
services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
services/worker/src/worker/job_runners/split/split_job_runner.py
services/worker/src/worker/utils.py
services/worker/tests/job_runners/config/test_config_job_runner.py
services/worker/tests/job_runners/config/test_info.py
services/worker/tests/job_runners/config/test_is_valid.py
services/worker/tests/job_runners/config/test_opt_in_out_urls_count.py
services/worker/tests/job_runners/config/test_parquet.py
services/worker/tests/job_runners/config/test_parquet_and_info.py
services/worker/tests/job_runners/config/test_parquet_metadata.py
services/worker/tests/job_runners/config/test_size.py
services/worker/tests/job_runners/config/test_split_names_from_info.py
services/worker/tests/job_runners/config/test_split_names_from_streaming.py
services/worker/tests/job_runners/split/test_descriptive_statistics.py
services/worker/tests/job_runners/split/test_duckdb_index.py
services/worker/tests/job_runners/split/test_first_rows_from_parquet.py
services/worker/tests/job_runners/split/test_first_rows_from_streaming.py
services/worker/tests/job_runners/split/test_image_url_columns.py
services/worker/tests/job_runners/split/test_is_valid.py
services/worker/tests/job_runners/split/test_opt_in_out_urls_count.py
services/worker/tests/job_runners/split/test_opt_in_out_urls_scan_from_streaming.py
services/worker/tests/job_runners/split/test_split_job_runner.py
services/worker/tests/test_job_runner_factory.py

Before, we were adding split validation in some job runners, but we should to it in all according to their granularity.
**Config** level should validate that the config exists in the dataset.
**Split** level should validate that the split exists in the config and that the config exists in the dataset.
**Example:**
When trying to `force-refresh` for step `split-first-rows-from-parquet` for dataset=ColumbiaNLP/FLUTE config=ColumbiaNLP--FLUTE split=train it failed with error:
`404, message='Not Found', url=URL('https://huggingface.co/datasets/ColumbiaNLP/FLUTE/resolve/refs%2Fconvert%2Fparquet/ColumbiaNLP--FLUTE/train/0000.parquet')
`
But it is wrong because the config no longer exists for the dataset and it should have thrown a SplitNotFoundError.
Related to …

Adding parent validation at job runner level

---

chart/env/prod.yaml

Re-appyling https://github.com/huggingface/datasets-server/pull/1791 since the author didn't add the NFAA tag
This will disable the preview for all the future datasets.
I'll also delete the cached previews for the existing datasets from this namespace.
cc @giadilli

Block cyberharem

---

services/worker/src/worker/job_manager.py
services/worker/src/worker/job_runner.py
services/worker/src/worker/job_runners/config/config_job_runner.py
services/worker/src/worker/job_runners/split/split_job_runner.py
services/worker/tests/job_runners/config/test_config_job_runner.py
services/worker/tests/job_runners/split/test_first_rows_from_streaming.py
services/worker/tests/job_runners/split/test_split_job_runner.py

We should be able to create an invalid job runners (e.g. for tests but most importantly because we need to do it to kill zombie jobs). Therefore I moved the check_config_exists() validation check to a dedicated `.validate()` method that is called only when the job will be run.
This should fix the kill_zombies failures that make all our workers crash in loop now.

Validate job runner

---

services/worker/src/worker/job_runners/split/first_rows_from_parquet.py

Fix typo in `SplitFirstRowsFromParquetJobRunner`.

Fix typo in SplitFirstRowsFromParquetJobRunner

---

services/worker/src/worker/job_runners/config/size.py
services/worker/src/worker/job_runners/split/descriptive_statistics.py

Two fixes to remove the erroneous `PreviousStepFormatError` for empty datasets. See `nicaplz/autotrain-data-autogpt` for example.

Fix empty datasets

---

chart/env/prod.yaml
chart/values.yaml

As proposed by @lhoestq, this PR reduces the value of `maxRowGroupByteSizeForCopy` from 500_000_000 to 300_000_000, so that it is compatible with `maxArrowDataInMemory` (300_000_000).
This should fix the `UnexpectedApiError` that we have in some full viewer pages.
Fix #1795.

Lower maxRowGroupByteSizeForCopy

---

docs/source/openapi.json

Update /search external docs URL in `openapi.json`, once that this PR is merged:
- #1767
fixing:
- #1663

Update /search external docs URL in openapi.json

---

docs/source/openapi.json

Add query parameter to /search 422 error description in `openapi.json`.

Add query parameter to /search 422 error description in openapi.json

---

libs/libcommon/src/libcommon/parquet_utils.py

someone is querying an image dataset ioclab/animesfw a lot at different offsets which fills the lru cache of image data and leads to OOM

Reduce rows lru cache in /rows

---

jobs/mongodb_migration/src/mongodb_migration/collector.py
jobs/mongodb_migration/src/mongodb_migration/migrations/_20230926095900_cache_add_has_fts_field_in_split_duckdb_index.py
jobs/mongodb_migration/tests/migrations/test_20230926095900_cache_add_has_fts_field_in_split_duckdb_index.py
libs/libapi/src/libapi/exceptions.py
libs/libcommon/src/libcommon/exceptions.py
services/search/src/search/routes/search.py
services/worker/src/worker/job_runners/split/duckdb_index.py
services/worker/src/worker/job_runners/split/is_valid.py
services/worker/tests/job_runners/split/test_duckdb_index.py
services/worker/tests/job_runners/split/test_is_valid.py

Needed for https://github.com/huggingface/datasets-server/pull/1418
Option 1: Since we need all the split datasets with the duckdb file for /filter, I propose just removing the limitation in the job runner as a noninvasive change.
Pending:
~~Option 2:~~
~~As an alternative, I think we could split the tasks into two separate runners:~~
~~- split-duckdb-data: in charge of data ingestion for the duckdb file only.~~
~~- split-duck-index: in charge of indexing the existing table only if indexable columns exist (might need to first download the previous one and generate a new one + the index).~~
~~But there could be open questions: Will we keep only one file in the repo? Should we have two separate files in the repo? (one for data and another for data+index)?~~

remove indexable columns limitation in split-duckdb-index

---

jobs/cache_maintenance/src/cache_maintenance/discussions.py

the revision text (ie: 39871f7) automatically creates a link. No need to create one by hand.

fix: 🐛 fix comment

---

chart/env/staging.yaml

We are now using Cloudfront to serve it, and expose assets from S3

feat(chart): remove external dns for staging env

---

libs/libcommon/src/libcommon/viewer_utils/asset.py
libs/libcommon/tests/viewer_utils/test_assets.py

Local files remain in local cached-assets when they already exist on the bucket, we should remove them anyway.
I will improve the logic in another PR: create files ONLY when they don't exist on the bucket.

fix: remove file in cached-assets even if not uploaded

---

libs/libcommon/src/libcommon/viewer_utils/features.py

The audio file extension was not inferred correctly when we stream the first rows.
Indeed in some cases the audio file path can be
```
zip://audio.wav::https://foo.bar/data.zip
```
fix https://huggingface.co/datasets/ccmusic-database/acapella_eval/discussions/3

Fix zipped audio extension in streaming

---

e2e/tests/test_11_api.py
e2e/tests/test_14_statistics.py
e2e/tests/test_52_search.py
e2e/tests/utils.py

As reported by @AndreaFrancis (see: https://github.com/huggingface/datasets-server/pull/1418#discussion_r1340621923), the condition on `expected_error_code` can be removed because it equals `None`.

Delete unnecessary condition on expected_error_code

---

chart/env/prod.yaml

With 29GB it still OOMs on some mC4 configs like `af`

Increase heavy workers ram

---

e2e/tests/test_53_filter.py
services/search/src/search/routes/filter.py
services/search/tests/routes/test_filter.py

I found something missing in one line of the final code (maybe lost during one of the multiple merges of the main branch and subsequent conflict resolutions).
CC: @severo @lhoestq

Fix missing index column in /filter

---

e2e/tests/test_11_api.py
e2e/tests/test_14_statistics.py
e2e/tests/test_52_search.py
e2e/tests/test_53_filter.py
e2e/tests/utils.py

This PR refactors e2e tests so that we do not pass unnecessary None headers (this is their default value).

Do not pass None headers in e2e tests

---

services/search/src/search/routes/filter.py

Replace `UnexpectedError` with `UnexpectedApiError` in filter endpoint, so that it is aligned with the other endpoints. This misalignment was introduced after the simultaneous merge of:
- #1475 
- #1418

Replace UnexpectedError with UnexpectedApiError in filter

---

services/api/poetry.lock
services/rows/poetry.lock
services/sse-api/poetry.lock

Now that `libapi` depends on `duckdb`, this PR updates `libapi` in all services.

Update libapi duckdb dependency in all services

---

chart/env/prod.yaml

Currently, we have 856 cached records with error ExternalServerError. This error is thrown when connection to Spawning AI API is not working:
`Error when trying to connect to https://opts-api.spawningaiapi.com/api/v2/query/urls: '{'detail': 'An unknown error has occurred.'}'`
We should retry those jobs because it is not related to an error with our logic but with the connection.
```
Atlas atlas-x5jgb3-shard-0 [primary] datasets_server_cache> db.cachedResponsesBlue.countDocuments({error_code:"ExternalServerError"})
856
Atlas atlas-x5jgb3-shard-0 [primary] datasets_server_cache> db.cachedResponsesBlue.distinct("kind", {error_code:"ExternalServerError"})
[ 'split-opt-in-out-urls-count', 'split-opt-in-out-urls-scan' ]
```
-------------------------
Also removing NoIndexableColumnsError from …

add ExternalServerError in error codes to retry for backfilling

---

docs/source/openapi.json
libs/libapi/src/libapi/request.py
services/rows/src/rows/routes/rows.py
services/search/src/search/routes/filter.py
services/search/src/search/routes/search.py

Factorize getting the request parameters `length` and `offset` from the service routes (/rows, /search and /filter) to `libapi`.
Additionally, align their error messages.

Factorize getting the request parameters length and offset

---

docs/source/openapi.json
libs/libapi/src/libapi/request.py
libs/libapi/tests/test_request.py

Fix `UnexpectedError` for non-integer length/offset and raise `InvalidParameterError` instead.

Fix UnexpectedError for non-integer length/offset

---

.github/workflows/_quality-python.yml
e2e/poetry.lock

Add check to CI quality, so that we verify that the `poetry.lock` file is consistent with the `pyproject.toml`.
@severo this verification also checks if the dependencies of a service are consistent, for example if the dependencies of `libcommon` or `libapi` have been previously updated. See related discussion in: https://github.com/huggingface/datasets-server/pull/1943#issuecomment-1750964793
Note that this approach does not avoid skipping updating the dependencies of the `libs` without updating the dependencies in the dependent services, but at least will guarantee that the dependencies of the services are updated as soon as possible afterwards.
The CI should be green once other PRs (that update the dependencies of the services after the updates of the libs) are merged:
See …

Make CI quality verify consistency of poetry.lock

---

e2e/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/worker/poetry.lock

Update `gitpython` to 3.1.37 to fix vulnerability.
This should fix 10 dependabot alerts.
Supersede and close #1958.
Supersede and close #1959.

Update gitpython to 3.1.37 to fix vulnerability

---

docs/source/parquet.mdx

1. refs/convert/parquet lives in parallel to `main` and is not meant to be merged, 2. the parquet native datasets are not converted

docs: ✏️ add two details to the Parquet docs

---

libs/libcommon/src/libcommon/config.py

hopefully will fix ` JobManagerExceededMaximumDurationError` for `split-descriptive-statistics` for big datasets like https://huggingface.co/datasets/Open-Orca/OpenOrca. It appears that loading data to in-memory table takes too much time
We can try like this and meanwhile I'm exploring other options how to query faster on big data

Add bonus difficulty to `split-descriptive-statistics` for big datasets

---

docs/source/openapi.json
libs/libapi/src/libapi/request.py
libs/libapi/tests/test_request.py
services/admin/src/admin/routes/dataset_backfill.py
services/admin/src/admin/routes/dataset_backfill_plan.py
services/admin/src/admin/routes/dataset_status.py
services/admin/src/admin/routes/force_refresh.py
services/admin/src/admin/routes/recreate_dataset.py
services/rows/src/rows/routes/rows.py
services/search/src/search/routes/filter.py
services/search/src/search/routes/search.py

Factorize getting the required request parameters `dataset`, `config`, `split`, `query` and `where` (from the service admin and the endpoints /rows, /search and /filter) to `libapi`.
Additionally, align their error messages.

Factorize getting required request parameters

---

chart/templates/_common/_helpers.tpl
chart/templates/cron-jobs/clean-duckdb-index-downloads/_container.tpl
chart/templates/cron-jobs/clean-duckdb-index-downloads/job.yaml
chart/templates/cron-jobs/clean-duckdb-index-job-runner/_container.tpl
chart/templates/cron-jobs/clean-duckdb-index-job-runner/job.yaml

When deploying to staging, this error appeared:
`one or more objects failed to apply, reason: CronJob.batch "staging-datasets-server-job-clean-duckdb-index-downloads" is invalid: metadata.name: Invalid value: "staging-datasets-server-job-clean-duckdb-index-downloads": must be no more than 52 characters,CronJob.batch "staging-datasets-server-job-clean-duckdb-index-job-runner" is invalid: metadata.name: Invalid value: "staging-datasets-server-job-clean-duckdb-index-job-runner": must be no more than 52 characters`
Reducing the job name to see if it fix the error

fix cron job metadata name lenght

---

chart/env/prod.yaml

Currently loading data into table takes too much time but should be decreased proportionally to the number of cpus. 
For example, on my local machine using 2 cpus loads 4Gb parquet files of [Open-Orca/OpenOrca](https://huggingface.co/datasets/Open-Orca/OpenOrca) for 20 sec and with 8 cpus for 5 sec.
Can we try this?

Increase the number of CPUs from 2 to 8 for heavy workers

---

services/admin/poetry.lock
services/admin/pyproject.toml
services/admin/src/admin/authentication.py
services/admin/src/admin/routes/cache_reports.py
services/admin/src/admin/routes/cache_reports_with_content.py
services/admin/src/admin/routes/dataset_backfill.py
services/admin/src/admin/routes/dataset_backfill_plan.py
services/admin/src/admin/routes/dataset_status.py
services/admin/src/admin/routes/force_refresh.py
services/admin/src/admin/routes/num_dataset_infos_by_builder_name.py
services/admin/src/admin/routes/obsolete_cache.py
services/admin/src/admin/routes/pending_jobs.py
services/admin/src/admin/routes/recreate_dataset.py
services/admin/tests/conftest.py
services/admin/tests/test_authentication.py
services/admin/tests/utils.py

Make admin service authentication asynchronous by using `httpx` instead of `requests`.
Related to:
- #1975

Make admin authentication asynchronous

---

libs/libcommon/src/libcommon/resources.py
libs/libcommon/src/libcommon/simple_cache.py
libs/libcommon/tests/test_simple_cache.py

Mongo only supports dates with time (not date alone) because of bson. 
So the `date` python type from `date32` pyarrow type couldn't be saved in mongo.
I fixed it by saving the `date` the same way as `string` objects.
Fix https://github.com/huggingface/datasets-server/issues/86
e.g. in first-rows for [aborruso](https://huggingface.co/aborruso)[/pnrr](https://huggingface.co/datasets/aborruso/pnrr)
```json
{
"dataset": "__DUMMY_DATASETS_SERVER_USER__/pnrr",
"config": "default",
"split": "train",
"features": [
{
"feature_idx": 0,
"name": "Programma",
"type": {
"dtype": "string",
"_type": "Value"
}
},
...
{
"feature_idx": 50,
"name": "Data di Estrazione",
"type": {
"dtype": "date32",
"_type": "Value"
}
}
],
"rows": [
{
"row_idx": 0,
"row": {
"Programma": "PNRR",
...
"Data di Estrazione": …
```

Add date type support in cache responses

---

libs/libapi/src/libapi/duckdb.py
services/search/src/search/routes/search.py

EDIT:
After the explanation by @AndreaFrancis, this PR moves the updating of the modification time of the duckdb index file from the /search endpoint to the `libapi` function `get_index_file_location_and_download_if_missing`.
This way, the modification time is also updated by the /filter endpoint.
~~Remove unnecessary `Path.touch` in /search.~~
~~I think this is not needed.~~
CC: @AndreaFrancis

Move modification time update of duckdb index file to libapi

---

services/worker/src/worker/job_runners/split/descriptive_statistics.py
services/worker/src/worker/job_runners/split/duckdb_index.py

it's not used for files download anymore, we use `huggingface_hub` directly
**+ I added some logging to check what's going on with the stats computing in this PR to make it fast, to be removed!**

Remove unused httpfs duckdb extension

---

services/worker/src/worker/job_runners/split/descriptive_statistics.py

Current value of `max_memory` in prod is 105.7Gb (despite the pod has only 34Gb but it's set automatically by duckdb as 80% of ram and ram of the node in total is 128Gb)
I want to try to lower it manually since we assume there might be some memory issues with duckdb causing the  `split-descriptive-statistics` process to stuck at the step of loading data into in-memory db.
(also want to try to load data to local db file, this is the only difference with `duckdb-index` step)

Limit max RAM that duckdb can use

---

services/worker/src/worker/job_runners/split/descriptive_statistics.py

This is my almost last idea on how make things not freezing on big datasets. It's the only difference with `duckdb-index` worker which apparently works fine for 5Gb datasets: it uses local db file, stats worker didn't use it.

Store data in a local database file for stats instead of an in-memory connection

---

e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/worker/poetry.lock

Update `urllib3` from 1.26.17 to fix vulnerability:
- to 2.0.7 in e2e
- to 1.26.18 in the rest of the components
This should fix 12 dependabot alerts.
Supersede and close #1994.
Supersede and close #1995.

Update urllib3 from 1.26.17 to fix vulnerability

---

libs/libapi/poetry.lock
libs/libapi/pyproject.toml
libs/libapi/src/libapi/jwt_token.py
services/admin/poetry.lock
services/api/poetry.lock
services/api/pyproject.toml
services/rows/poetry.lock
services/rows/pyproject.toml
services/search/poetry.lock
services/search/pyproject.toml
services/sse-api/poetry.lock

Remove `requests` as `libapi` dependency by using `httpx` instead.

Remove requests as dependency of libapi

---

.github/workflows/doc-build.yml

This token is not used by your action.
Secret is removed from the repository.

fix: remove useless token

---

chart/templates/_env/_envCommon.tpl
chart/values.yaml
libs/libcommon/README.md
libs/libcommon/src/libcommon/config.py
libs/libcommon/src/libcommon/exceptions.py
services/worker/pyproject.toml
services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
services/worker/src/worker/job_runners/split/opt_in_out_urls_scan_from_streaming.py
services/worker/src/worker/utils.py
services/worker/tests/conftest.py
services/worker/tests/job_runners/config/test_parquet_and_info.py
tools/docker-compose-base.yml
tools/docker-compose-dev-base.yml

The `config-parquet-and-info` step will now raise a `DatasetWithScriptNotSupportedError` for datasets with a script, except those in the allow list. This will prevent users from running arbitrary code using dataset scripts.
The error message is shown to the user on the website and it says
```python
raise DatasetWithScriptNotSupportedError(
"The dataset viewer doesn't support this dataset because it runs "
"arbitrary python code. Please open a discussion in the discussion tab "
"if you think this is an error and tag @lhoestq and @severo."
)
```
The allow list is hardcoded for now: `DATASET_SCRIPTS_ALLOW_LIST = ["canonical"]`
The keyword "canonical" means all the datasets without namespaces.
We can add other datasets to the allow list, and it supports `fnmatch`, for example to support all …

Disable dataset scripts

---

libs/libapi/src/libapi/request.py
libs/libapi/src/libapi/utils.py
libs/libapi/tests/test_request.py
services/admin/src/admin/routes/cache_reports.py
services/admin/src/admin/routes/cache_reports_with_content.py
services/admin/src/admin/routes/dataset_backfill.py
services/admin/src/admin/routes/dataset_backfill_plan.py
services/admin/src/admin/routes/dataset_status.py
services/admin/src/admin/routes/force_refresh.py
services/admin/src/admin/routes/recreate_dataset.py
services/rows/src/rows/routes/rows.py
services/search/src/search/routes/filter.py
services/search/src/search/routes/search.py
services/sse-api/src/sse_api/routes/hub_cache.py

Factorize getting request parameters for both required and non-required ones, by using the function `get_request_parameter` and merging `get_required_request_parameter` into it, with the addition of the parameters "required" and "default".
Use `get_request_parameter` to get the "cursor", "priority" and "all" parameters.

Factorize getting request parameters

---

chart/Chart.yaml
chart/env/prod.yaml
chart/templates/_common/_helpers.tpl
chart/templates/cron-jobs/clean-duckdb-index-cache/_container.tpl
chart/templates/cron-jobs/clean-duckdb-index-cache/job.yaml
chart/values.yaml

We have a cache folder in `/storage/duckdb-index`, this folder is used for cached downloads in `/search` and `/filter` while calling `  hf_hub_download` https://github.com/huggingface/datasets-server/blob/ef8a1cb34ba661b859962ac8d6c138374a0b0190/libs/libapi/src/libapi/duckdb.py#L78 (which needs a cache directory).
I noticed that we have old files in `/storage/duckdb-index/cache` which are using about 185G:
We can apply the same cleaning as we do for other folders so I added a new cron job.
I think another approach to avoid using `hf_hub_download` cache is to use `hf_transfer` directly, but I will investigate more about the advantages, meanwhile, the cron job will avoid increasing the storage usage.

add cron job to clean duckdb index cache

---

libs/libapi/poetry.lock
libs/libapi/pyproject.toml
libs/libapi/src/libapi/duckdb.py
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/search/src/search/duckdb.py
services/search/src/search/routes/filter.py
services/search/src/search/routes/search.py
services/sse-api/poetry.lock
services/worker/poetry.lock

Remove `duckdb` from libapi by moving the function `duckdb_connect` to the "search" service. 
In the future, if this function is required by other components, I would suggest to create a new duckdb-specific lib, so that we decouple API and DuckDB functionalities.
Additionally update all components that depend on `libapi` and remove their dependency on `duckdb` if they do not need it. These are:
- admin
- api
- rows
- sse-api

Remove duckdb as libapi dependency

---

front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/worker/poetry.lock

Update `pandas` dependency to latest patch release 2.0.3 in 2.0 series: https://github.com/pandas-dev/pandas/releases/tag/v2.0.3
> This is a patch release in the 2.0.x series and includes some regression and bug fixes. We recommend that all users upgrade to this version.
Note that most components had `pandas` 2.0.2.
Also note that we have respected the constrain `<2.1`, until we update `duckdb` as well. More details in:
- #1914

Update pandas dependency to 2.0.3

---

libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py
services/admin/src/admin/routes/recreate_dataset.py
services/admin/tests/routes/test_recreate_dataset.py

Adding test for recreate dataset in admin service.
Also found a bug for cancel_jobs, it was returning always 0 after the update statement.

adding tests for recreate dataset

---

libs/libapi/src/libapi/duckdb.py

Support asynchronous file I/O to get duckdb index file by replacing `pathlib.Path` with `anyio.Path`.

Support async file I/O to get duckdb index file

---

chart/env/staging.yaml
chart/values.yaml
tools/docker-compose-datasets-server.yml
tools/docker-compose-dev-datasets-server.yml

fixes #1961.
RELEASE NOTES are here: https://nginx.org/en/CHANGES.
The change we're interested in is:
> *) Change: improved detection of misbehaving clients when using
HTTP/2.

feat: 🎸 upgrade nginx image to 1.25.3

---

chart/values.yaml

Quick fix to avoid deleting old cache entries (in particular, to be sure to keep the old dataset cache entries for datasets with a dataset script, now that we don't support scripts anymore)

invalidate the datasets cache after 3 years instead of 3 months

---

chart/nginx-templates/default.conf.template
chart/templates/reverse-proxy/_container.tpl
chart/values.yaml

After deploying https://github.com/huggingface/datasets-server/pull/2040 in staging, reverse-proxy component failed (I could not see the specific error but suspect it is because of an alias to a no longer existent location /storage).

fix reverse proxy

---

libs/libcommon/src/libcommon/storage_client.py
services/admin/tests/routes/test_obsolete_cache.py

Fix for obsolete cache, FileNotFound error is shown when a datasets does not have either assets or cached assets:
```
ERROR: 2023-11-07 15:42:28,461 - root - Unexpected error.
Traceback (most recent call last):
File "/src/services/admin/src/admin/routes/obsolete_cache.py", line 126, in delete_obsolete_cache_endpoint
delete_obsolete_cache(
File "/src/services/admin/src/admin/routes/obsolete_cache.py", line 95, in delete_obsolete_cache
cached_assets_storage_client.delete_dataset_directory(dataset)
File "/src/libs/libcommon/src/libcommon/storage_client.py", line 50, in delete_dataset_directory
self._fs.rm(dataset_key, recursive=True)
File "/src/services/admin/.venv/lib/python3.9/site-packages/fsspec/asyn.py", line 118, in wrapper
return sync(self.loop, func, *args, **kwargs)
File …
```

catch exception on delete assets

---

chart/env/prod.yaml
services/worker/src/worker/job_runners/split/descriptive_statistics.py

@polinaeterna I fixed the n_threads and max_memory settings of DuckDB (they should be different based on the pod type)
I also set requests == limits for cpu to see if it fixes the DuckDB hanging issue (and more generally any hanging issue that we can also observe when killing pods or in parquet conversion jobs)

Stats resources

---

libs/libcommon/src/libcommon/parquet_utils.py
services/worker/src/worker/job_runners/split/first_rows_from_parquet.py
services/worker/tests/job_runners/split/test_first_rows_from_parquet.py

Part of https://github.com/huggingface/datasets-server/issues/1443
Currently, we have `{ _id: { cause: 'ParquetResponseEmptyError' }, count: 303 }`, records in cache collection with UnexpectedError because of `ParquetResponseEmptyError`.
Actually, we have two definitions of `ParquetResponseEmptyError`: one in parquet_utils.py https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/src/libcommon/parquet_utils.py#L29 and another in https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/src/libcommon/exceptions.py#L424.
`SplitFirstRowsFromParquetJobRunner` should throw the cacheable version of `ParquetResponseEmptyError` but currently it is not handling the noncacheable exception leading to an `UnexpectedError`.
After this PR, I will refresh the cache of the …

add cacheable ParquetResponseEmptyError in first-rows-from-parquet

---

chart/values.yaml

> a lot of calls to the Hub are pending because of "expand" in the tree
API by the datasets library

feat: 🎸 disable two datasets to avoid load on the Hub

---

services/api/src/api/routes/croissant.py
services/api/tests/routes/test_croissant.py

Reason: `/` are used in the syntax as delimiters.
I ended up testing on the first dataset names and configs, and found more conflicts (like ` ` or `=` in the names), so I ended up applying a regular expression corresponding to [the one used by Croissant](https://github.com/mlcommons/croissant/blob/475998a89716a8a022817f1126cf3dd1a3526418/python/mlcroissant/mlcroissant/_src/structure_graph/base_node.py#L20).

Escape names in Croissant.

---

libs/libcommon/src/libcommon/queue.py

**According to index usage, these indexes are not used very frecuently or can ve covered by another index:**
- ("type", "dataset", "revision", "config", "split", "status", "priority"),
- ("priority", "status", "created_at", "namespace"),
- ("unicity_id", "-created_at", "status"), # 4440
I hid them to evaluate if the system will be affected once we delete them. 
**Adding these indexes in the code as they already exist in the server and are used by the queries:**
- ("dataset", "status"),
- ("priority", "status", "created_at", "namespace", "difficulty", "unicity_id"),
- ("priority", "status", "created_at", "difficulty", "namespace"),
- ("unicity_id", "status", "-created_at"),
See index usage report:
```
[
{
name: 'type_1_dataset_1_revision_1_config_1_split_1_status_1_priority_1',
key: { …
```

Sync queue index

---

chart/env/prod.yaml

Currently we have a queue that isn't able to reduce for at least a couple of days
The current difficulty distribution is:
```
Atlas atlas-x5jgb3-shard-0 [primary] datasets_server_queue> db.jobsBlue.aggregate([{$match:{status:"waiting"}},{$group:{_id:{difficulty:"$difficulty"},count:{$sum:1}}},{$sort:{count:-1}}])
[
{ _id: { difficulty: 70 }, count: 3290 },
{ _id: { difficulty: 90 }, count: 501 },
{ _id: { difficulty: 50 }, count: 327 },
{ _id: { difficulty: 60 }, count: 19 }
]
```
I will try to see if changing the worker max/min difficulty helps reducing the load.

temporary changing difficulty intervals in workers

---

chart/values.yaml

Temporary blocking namespace lunaluan/* because of a high activity in datasets (many frequent commits): 
- lunaluan/chatbox6_history 23778 commits
- lunaluan/chatbox8_history 22964 commits
- lunaluan/chatbox4_history 79255 commits
- lunaluan/chat_history5 46412 commits
- lunaluan/chatbox3_history 76140 commits

blocking temporary lunaluan datasets

---

jobs/mongodb_migration/tests/test_deletion_migrations.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py

As suggested by @severo  in https://github.com/huggingface/datasets-server/pull/2175#discussion_r1412342252 for "remove finished jobs," PR, finished_at, and TTL index field is being removed from code. Once merged, It will be necessary to deploy before changes in https://github.com/huggingface/datasets-server/pull/2175

remove finished_at from code

---

services/worker/src/worker/job_runners/split/descriptive_statistics.py

Related to https://github.com/huggingface/datasets-server/issues/2047
I am not sure if this will help, but I saw that many jobs got stuck in the CREATE command, `duckdb-index` worker also performs this operation, but it looks like it doesnt stuck for so long.
I want to try loading directly to parquet files instead of using `read_parquet` function.

remove read_parquet from descriptive stats

---

libs/libcommon/src/libcommon/queue.py
services/worker/src/worker/executor.py
services/worker/src/worker/job_manager.py

Sometimes, a long job gets finished by another worker (still investigating the cause), and heartbeat logs the issue forever.
Once the heartbeat fails for some reason, the executor should stop to avoid blocking the worker:
This scenario keeps being logged forever until the worker restarts, which is why, in each deployment, we have almost the same number of started jobs compared to the number of workers, but when getting into this case, the number of active workers reduces.
I also changed the log level to INFO when finishing a job to investigate the root cause of the message: `"WARNING: 2023-12-07 17:44:14,644 - root - Heartbeat skipped because job 657202cb9c5adfceb6840d88 doesn't exist in the queue." `
Note.- I have already seen this behavior before: …

logs and stop executor on failure

---

chart/values.yaml

It generates >1K jobs with difficulty 90, which will never be processed (too few "heavy" workers). Also note that the dataset is gated with manual approval, which limits the audience of dataset viewer / parquet conversion.

feat: 🎸 block big dataset

---

services/worker/src/worker/job_runners/split/duckdb_index.py

`split-duckdb-index` fails mostly for big datasets in the create index step (PRAGMA create_fts_index) because of OOM.
Same as in https://github.com/huggingface/datasets-server/pull/2081/files, I would like to try custom duckdb configurations to see if that helps.
Also I noticed the close condition was never closed when there was an error in parquet files downloading.

try duckdb resources configuration

---

services/worker/src/worker/job_runners/split/duckdb_index.py

Memory setting didn't work for big datasets. It took more time to process, rolling back and trying another configuration as recommended in https://duckdb.org/docs/guides/performance/how-to-tune-workloads#the-preserve_insertion_order-option

try preserve_insertion_order

---

services/worker/src/worker/job_runners/split/duckdb_index.py

Rollback of setting in https://github.com/huggingface/datasets-server/pull/2212. Heavy workers are taking more time when inserting.

remove duckdb setting

---

chart/env/prod.yaml

With 34Gi it fails because of OOMs when processing `split-duckdb-index` for some Wikipedia configs like 20231101.es and 20231101.en when creating index step.

increase limits memory for heavy workers

---

jobs/cache_maintenance/Dockerfile
jobs/mongodb_migration/Dockerfile
services/admin/Dockerfile
services/admin/dev.Dockerfile
services/api/Dockerfile
services/api/dev.Dockerfile
services/rows/Dockerfile
services/rows/dev.Dockerfile
services/search/Dockerfile
services/search/dev.Dockerfile
services/sse-api/Dockerfile
services/sse-api/dev.Dockerfile
services/worker/dev.Dockerfile

we could surely build a base image, if somebody wants to do it...
it should fix the following error message we see in the admin service logs:
```
/src/services/admin/.venv/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work 
warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
```

chore: 🤖 use the same packages in all the docker imges

---

e2e/tests/test_11_api.py
jobs/cache_maintenance/src/cache_maintenance/backfill.py
libs/libapi/src/libapi/utils.py
libs/libcommon/src/libcommon/exceptions.py
libs/libcommon/src/libcommon/operations.py
libs/libcommon/src/libcommon/utils.py
libs/libcommon/tests/test_operations.py
services/admin/Makefile
services/admin/src/admin/routes/force_refresh.py
services/admin/tests/routes/test_recreate_dataset.py
services/api/Makefile
services/api/src/api/routes/endpoint.py
services/api/tests/routes/test_endpoint.py
services/rows/Makefile
services/search/Makefile

See https://github.com/huggingface/datasets-server/pull/2244#discussion_r1445259783
Instead of returning DatasetNotFound, return the reason why the dataset is not supported: disabled repo, disabled viewer, private repo, or blocked dataset. When we do the check, the user is already authenticated and authorized to access the dataset, so: it makes no sense to hide the reason as if the dataset would not exist (the initial idea was to avoid disclosing the existence of a private dataset).
Also: refactoring to "simplify": we raise if a dataset is not supported. No need for a "DatasetStatus" abstraction
Also (unrelated): delete the docker network when running make test, to avoid errors.

return a specific error message when dataset is not supported

---

e2e/tests/test_11_api.py
jobs/cache_maintenance/src/cache_maintenance/backfill.py
libs/libapi/src/libapi/utils.py
libs/libcommon/src/libcommon/exceptions.py
libs/libcommon/src/libcommon/operations.py
libs/libcommon/src/libcommon/utils.py
libs/libcommon/tests/test_operations.py
services/admin/Makefile
services/admin/src/admin/routes/force_refresh.py
services/admin/tests/routes/test_recreate_dataset.py
services/api/Makefile
services/api/src/api/routes/endpoint.py
services/api/src/api/routes/webhook.py
services/api/tests/routes/test_endpoint.py
services/api/tests/test_app_real.py
services/rows/Makefile
services/search/Makefile

fixes #1823. Note that we now always require the user to be trusted (ie to pass a secret with the /webhook request) because all the actions are destructive.
Depends on merging https://github.com/huggingface/datasets-server/pull/2246 first

recreate the dataset on webhook to avoid mixed content

---

chart/env/prod.yaml
chart/templates/cron-jobs/backfill/_container.tpl
chart/values.yaml
jobs/cache_maintenance/README.md
jobs/cache_maintenance/src/cache_maintenance/backfill.py
jobs/cache_maintenance/src/cache_maintenance/config.py
jobs/cache_maintenance/src/cache_maintenance/main.py
libs/libcommon/src/libcommon/constants.py
libs/libcommon/src/libcommon/operations.py
libs/libcommon/src/libcommon/orchestrator.py
libs/libcommon/src/libcommon/state.py
libs/libcommon/tests/test_backfill.py
libs/libcommon/tests/test_orchestrator.py
libs/libcommon/tests/utils.py

There is no need to have this as an environment variable, and it clutters the code.
Note that the two lists we had (default one and backfill one) were different, by the way

hardcode the error codes to retry

---

libs/libcommon/src/libcommon/exceptions.py
libs/libcommon/src/libcommon/operations.py
libs/libcommon/tests/test_operations.py
services/api/tests/routes/test_endpoint.py

Fixes #2272 and #2273.
See related PR: https://github.com/huggingface/huggingface_hub/pull/1965 (once released, change the code in datasets-server)

delete the dataset when repo is disabled or does not exist

---

libs/libapi/src/libapi/duckdb.py
libs/libcommon/src/libcommon/parquet_utils.py
libs/libcommon/tests/test_parquet_utils.py
services/worker/src/worker/job_runners/split/descriptive_statistics.py
services/worker/src/worker/job_runners/split/duckdb_index.py

Fixes #1755 
This PR adds `extract_split_name_from_url` function to parquet utils and function is called when necessary.

Add extract_split_name_from_parquet_url function to parquet utils

---

docs/source/analyze_data.mdx
docs/source/filter.mdx
docs/source/first_rows.mdx
docs/source/index.mdx
docs/source/info.mdx
docs/source/openapi.json
docs/source/parquet.mdx
docs/source/quick_start.mdx
docs/source/rows.mdx
docs/source/search.mdx
docs/source/size.mdx
docs/source/splits.mdx
docs/source/valid.mdx
e2e/tests/test_12_splits.py

Update minor details in the doc:
- partial field for some responses
- filter example
- rename `duorc` by `ibm/duorc` instead (even though the hub redirects to the correct organization, datasets-server API does not)
Note.- I haven't update yet `Server infrastructure` page, I will do it in another PR

doc - Update minor details in the doc

---

libs/libapi/src/libapi/response.py
libs/libapi/tests/test_response.py
services/search/src/search/routes/filter.py
services/search/src/search/routes/search.py
services/search/tests/routes/test_filter.py

fix https://huggingface.co/datasets/fka/awesome-chatgpt-prompts/viewer/default/train?f[act][min]=4&f[act][max]=8&f[act][transform]=length
This was caused by `RuntimeError: The indexing process did not store the features.`

Fix filter no features in duckdb index cache

---

front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/worker/poetry.lock

This should fix 11 dependabot alerts.

Update cryptography dependency to 42.0 to fix vulnerability

---

services/worker/src/worker/job_runners/dataset/config_names.py

fixes #2385 
I didn't increment the job runner version, because it only happen in 235 datasets. We will update them manually.
```
db.cachedResponsesBlue.countDocuments({error_code: "DatasetWithScriptNotSupportedError", kind: "dataset-config-names"})
235
```

catch ValueError before ImportError

---

front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libapi/pyproject.toml
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/worker/poetry.lock
services/worker/pyproject.toml

Update `starlette` minor version to 0.37.1: https://github.com/encode/starlette/releases/tag/0.37.1
Related to:
- #2400 
- #2401

Update starlette minor version to 0.37.1

---

front/admin_ui/poetry.lock

Update `fastapi` to fix vulnerability Note there is a version constraint between fastapi and starlette (starlette: >=0.36.3,<0.37.0). Bump:
- fastapi-0.109.2
- starlette-0.36.3
Note this PR fixes 2 simultaneous vulnerabilities: :crossed_fingers: 
- Vulnerability in fastapi <= 0.109.0
- Vulnerability in: starlette <= 0.36.1
Also note that in our project we have 2 different dependencies on starlette:
- One in libapi: we can freely choose this version
- Another in admin_ui: this is an indirect dependency and we can't freely choose the version: gradio > fastapi > starlette (required: >=0.36.3,<0.37.0)

Update fastapi to fix vulnerability

---

front/admin_ui/README.md
front/admin_ui/requirements.txt

follows #2445. cc @albertvillanova fyi. I already did the same error... We should find a way to have only one source of truth for the packages, instead of ... 3!

requirements.txt is used by spaces, pyproject.yaml is ignored

---

libs/libcommon/src/libcommon/orchestrator.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_queue.py
services/worker/src/worker/executor.py
services/worker/src/worker/job_manager.py
services/worker/src/worker/loop.py

Also, random updates:
- fix names: we don't "cancel" jobs anymore, we "delete" them
- remove obsolete catch of `DatasetInBlockListError` exception when running `finish_job()` -> it's not checked anymore

Log more details when worker crashes

---

chart/env/prod.yaml

we have 5K long jobs (statistics and duckdb), so: increasing here in the code, instead of scaling manually, to be sure to keep these values if we deploy again in the next hours or days

increase resources to 10/80/10

---

.github/workflows/_e2e_tests.yml
.github/workflows/_quality-python.yml
.github/workflows/_unit-tests-python.yml
.github/workflows/cd.yml
.github/workflows/openapi-spec.yml
.github/workflows/stale.yml

Update GitHub Actions to Node 20.
See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Fix #2467.

Update GitHub Actions to Node 20

---

libs/libcommon/src/libcommon/constants.py

Follows #2227
To be merged next week, when all the occurrences will have been recomputed.
Currently:
```
use datasets_server_cache
db.cachedResponsesBlue.countDocuments({kind: "split-descriptive-statistics", error_code: "SplitWithTooBigParquetError"})
2937
```

remove obsolete error code

---

libs/libcommon/src/libcommon/orchestrator.py

The backfill was creating duckdb indexing jobs for big datasets without adjusting the difficulty.
Because of that the medium workers were processing them and OOMing and every retry.

Fix backfill wrong difficulties, causing OOMs

---

libs/libcommon/src/libcommon/processing_graph.py
libs/libcommon/tests/test_operations.py
libs/libcommon/tests/test_processing_graph.py
libs/libcommon/tests/utils.py
services/worker/tests/test_job_manager.py

fixes #2530
it:
- reverts #2489
- adds the missing triggering step
- adds a check when creating the processing graph, to ensure all the config- and dataset-level steps have at least one triggering step of the same level, to handle the case where we couldn't get the configs or the splits.

Restore missing triggers between steps

---

services/worker/src/worker/job_runners/config/parquet_and_info.py

I assume the fact that we don't restrict the max number of workers (which results in [32 workers](https://github.com/tqdm/tqdm/blob/master/tqdm/contrib/concurrent.py#L44)* from `tqdm.contrib.concurrent.thread_map` which we use at this step) might result in (likely) OOM for `bigcode/the-stack-v2`. Since there are about 1k parquet files in this dataset.
\+ add logs to see where exactly that happens to support this hypothesis.
*UPD: i'm not sure here because in theory Kubernetes should restrict the max number of accessible cpu's to 8 https://github.com/huggingface/datasets-server/blob/main/chart/env/prod.yaml#L452
But when I monitor in `htop` I see that all cpu's are loaded at this moment.

Set max workers for `retry_and_validate_get_parquet_file_and_size` in `config-parquet-and-info` to 4

---

services/worker/src/worker/job_runner_factory.py
services/worker/src/worker/job_runners/dataset/loading_tags.py
services/worker/tests/job_runners/dataset/test_loading_tags.py

`dataset-hub-cache` is failing because of `dataset-loading-tags` - PermissionError - [Errno 13] Permission denied: '/.cache'
Currently 754 affected datasets.

Fix: Add datasets cache to loading tags job runner

---

services/worker/src/worker/job_runners/dataset/config_names.py
services/worker/tests/fixtures/hub.py
services/worker/tests/job_runners/config/test_parquet_and_info.py
services/worker/tests/job_runners/dataset/test_config_names.py

Show the default config first in the Viewer.
I did this by ordering the configs in `dataset-config-names` to have the default config in first position
fix https://github.com/huggingface/datasets-server/issues/2541
No need to recompute all the entries, it's fine to apply this to new / updated datasets imo
cc @HugoLaurencon for WebSight

Default config first

---

chart/env/prod.yaml

30 jobs is too low for the medium jobs (and for the light ones too). On the other side, I think we can lower the limit for the heavy ones to 20.

tweaking the threshold for autoscaling

---

docs/source/filter.md
docs/source/first_rows.md
docs/source/info.md
docs/source/openapi.json
docs/source/rows.md
docs/source/search.md
docs/source/statistics.md
docs/source/valid.md
e2e/pyproject.toml
e2e/tests/test_12_splits.py
front/admin_ui/app.py
jobs/cache_maintenance/pyproject.toml
jobs/mongodb_migration/pyproject.toml
libs/libcommon/pyproject.toml
libs/libcommon/tests/test_duckdb_utils.py
libs/libcommon/tests/test_parquet_utils.py
services/admin/pyproject.toml
services/admin/tests/test_app_real.py
services/api/pyproject.toml
services/api/tests/test_app_real.py
services/rows/pyproject.toml
services/search/pyproject.toml
services/worker/pyproject.toml
services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/tests/job_runners/config/test_parquet_and_info.py

fixes #2578 
In the codebase, we still access the following canonical datasets, which have not been moved to an org: `cnn_dailymail`, `mnist`, `blog_authorship_corpus`, `rotten_tomatoes`, `ett`, `amazon_polarity`, `imagenet-1k`, `cifar100`, `superb`, `imdb`, `atomic`.

Replace canonical datasets with community ones in the docs/tests

---

services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/tests/fixtures/hub.py
services/worker/tests/job_runners/config/test_parquet_and_info.py

fixes #2581 
---
After merging and deploying, I'll refresh all the affected datasets.
It's not so much (<2k jobs)
```
db.cachedResponsesBlue.countDocuments({
"kind": "config-parquet-and-info"
})
140609
db.cachedResponsesBlue.countDocuments({
"kind": "config-parquet-and-info",
"updated_at": { 
$gte: new Date("2024-03-12T08:00:00.000Z"),
}
})
1644
```

Fix size of splits

---

libs/libcommon/src/libcommon/constants.py
libs/libcommon/src/libcommon/exceptions.py
services/worker/src/worker/job_runners/config/parquet_and_info.py

Related to https://github.com/huggingface/datasets-server/issues/1443 for `config-parquet-and-info`, we have 1065 entries with HfHubHTTPError UnexpectedError, we should retry because sometimes it is not a final error but just an issue with Hub's connectivity.

Add retry when loading dataset builder

---

libs/libcommon/src/libcommon/viewer_utils/truncate_rows.py

We were using the same `list` for all the cells. So if a cell has truncated columns then all the cells end up with the same value for `truncated_cells`
Close https://github.com/huggingface/datasets-server/issues/2586

Fix cell truncation

---

chart/env/prod.yaml

- increase threshold for medium and light workers, because it's pretty common to have a burst of 50 jobs
- reduce the max number of mium and heavy workers because it's not possible currently, with 50 nodes, to get 100 medium workers and 50 heavy workers at the same time

change values for autoscaling

---

libs/libcommon/src/libcommon/processing_graph.py
services/worker/src/worker/job_runners/dataset/hub_cache.py
services/worker/tests/job_runners/dataset/test_hub_cache.py

Follows the changes in https://github.com/huggingface/datasets-server/pull/2454
The `dataset-hub-cache` should have `libraries` as a list of strings, not a list of CompatibleLibrary objects

Fix hub cache libraries

---

services/worker/src/worker/job_runners/split/opt_in_out_urls_scan_from_streaming.py
services/worker/tests/fixtures/datasets.py
services/worker/tests/job_runners/split/test_opt_in_out_urls_scan_from_streaming.py

Fix for https://github.com/huggingface/datasets-server/issues/2608
Many URLs are None and the job runner failed when doing the join operation at https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runners/split/opt_in_out_urls_scan_from_streaming.py#L38

Fix  ExternalServerError for None URLs in split-opt-in-out-scan

---

libs/libcommon/src/libcommon/processing_graph.py
services/worker/src/worker/dtos.py
services/worker/src/worker/job_runners/dataset/compatible_libraries.py
services/worker/src/worker/job_runners/dataset/hub_cache.py
services/worker/tests/job_runners/dataset/test_compatible_libraries.py
services/worker/tests/job_runners/dataset/test_hub_cache.py

Added `formats: list[str]` to "hub-cache". It is computed in "compatible-libraries" since compatibilities depend on the format.
Possibles values are
- csv
- json
- parquet
- text
- imagefolder
- audiofolder
Mentioned in https://github.com/huggingface/datasets-server/issues/2455
I chose to have it as a list for simplicity, but lmk if you think we should set it to `format: Optional[str]` instead
includes a minor change: updated the libraries order

Add formats tags

---

services/worker/src/worker/job_runners/dataset/compatible_libraries.py
services/worker/tests/job_runners/dataset/test_compatible_libraries.py

Pandas only supports paths without `*`.
I fixed an issue to get the full file name from single-file datasets YAML metadata containing the `data_files` with `*` 
close https://github.com/huggingface/datasets-server/issues/2614

Use pandas for single files datasets

---

chart/templates/_env/_envWorker.tpl
chart/templates/services/search/_container.tpl

While deploying the search component, it throws error:
cannot convert int64 to string

try to fix env variable

---

libs/libapi/src/libapi/jwt_token.py
libs/libapi/tests/test_authentication.py
libs/libapi/tests/test_jwt_token.py

The JWT now contains `permissions: {"repo.content.read": true}` instead
of the (soon deprecated) ``read: true`.
fixes https://github.com/huggingface/datasets-server/issues/2620.

adapt JWT verification to new field

---

chart/env/prod.yaml
services/search/src/search/routes/search.py
services/search/tests/routes/test_search.py

Following PR https://github.com/huggingface/datasets-server/pull/2633 and comment https://github.com/huggingface/datasets-server/pull/2633#issuecomment-2021117342 I would like to first try with a JOIN approach:
1. Get the rows that match the query criteria (score NOT NULL)
2.  JOIN with the `data` table to get the other columns 
This approach should be better than the current process, but it might still not work for big datasets since the "data" table does not have a PRIMARY KEY yet. See https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runners/split/duckdb_index.py#L58 we only define the sequence, but it is still a heap table (without indexes to improve the duckdb query plan). 
If this approach sounds good, it will be necessary to change …

 Try to improve fts for big datasets by stage table join

---

docs/source/croissant.md
docs/source/mlcroissant.md
libs/libcommon/src/libcommon/processing_graph.py
services/worker/src/worker/job_runners/dataset/compatible_libraries.py
services/worker/tests/job_runners/dataset/test_compatible_libraries.py

I updated the URLs in the compatible-libraries jobs and also in the docs.
cc @severo

Update Croissant URL to use the HF Hub `/api`

---

services/worker/src/worker/job_runners/config/parquet_and_info.py

Close https://github.com/huggingface/datasets-server/issues/2646
I'll recompute the parquet-and-info jobs for the impacted datasets, otherwise their Viewer will still be slow or get TooBigContentError

Fix row-group size for imagefolder and audiofolder datasets

---

chart/env/prod.yaml

Before https://github.com/huggingface/datasets-server/pull/2641, I wanted to try changing the memory limit.
Maybe it is a dummy doubt, but I don't understand why we have many search replicas when there are a low number of requests (we have only 12 for rows, which is highly requested).
Isn't it better to have less replicas with a high memory limit so that we avoid OOM? (Not sure how it impacts in terms of infra costs) 
I might be wrong but I chose 7 replicas with a 30 GB memory based on:
- Our biggest index with FTS support is 30 GB size:
I am still investigating, but even with the JOIN with a small stage in the left table at https://github.com/huggingface/datasets-server/pull/2641, duckdb looks to be doing a SEQ_SCAN (full table scan) when retrieving all the columns. (I will ask the …

try if search works in big datasets

---

services/worker/poetry.lock
services/worker/pyproject.toml

Now that we require pillow >= 10.3.0, the package types-pillow is no longer necessary.
This PR removes it as dev dependency.

Remove unnecessary types-pillow

---

services/search/src/search/routes/search.py

Before trying to change to local disks for duckdb index files, I would like to confirm whether it speeds up the response for some datasets analyzed in https://github.com/huggingface/dataset-viewer/issues/2593.
**wikimedia/wikipedia-20231101.en-train** (Medium size: 9.1 GB) =  ~17 seconds
**MohamedRashad/Arabic-CivitAi-Images - default - train** (Small size: 580 MB) =  ~4 seconds
**jp1924/VIsualQuestionAnswering - default - train** (Big size: 23 GB) =  ~42 seconds
**asoria/search_test - default - train** (Small: 27 MB)  =  ~2 seconds
All of these indexes will occupy something like 33 GB, which is not a problem for our current pods with 40 GB free. I will manually delete after each test and then rollback.

Try FTS index in local storage

---

chart/values.yaml

It's used in `datasets` CI which is failing right now

Allow hf-internal-testing/dataset_with_script

---

chart/env/prod.yaml

Related to #2690
See https://github.com/huggingface/infra/pull/940 (internal) which provides more resources, in a specific new "role" (role-datasets-server-api)
It provides up to 6 m6a.4xlarge nodes, each of which has 16 vCPUs and 64GB RAM. So: each node should get 4 pods, we should use 3 nodes, and have room to scale up twice
---
blocked by https://github.com/huggingface/infra/pull/940

increase resources for API service

---

chart/nginx-templates/default.conf.template
chart/templates/services/search/ingress.yaml
chart/values.yaml

As discussed in #468, let's start to remove nginx proxy.
In this PR, we begin with the search API.

feat(chart): search api exposed directly with ALB

---

chart/env/prod.yaml
chart/values.yaml

Rollback of https://github.com/huggingface/dataset-viewer/pull/2716 and align schedule with cache folder

Align clean downloads schedule

---

.github/workflows/_quality-python.yml
docs/pyproject.toml
e2e/pyproject.toml
e2e/src/__init__.py
e2e/src/e2e/__init__.py
front/admin_ui/pyproject.toml
tools/Python.mk

Once that we have updated Poetry to 1.8.2, we can set non-package mode in the components we are not packaging:
- docs
- admin-ui
- e2e
Note that currently a warning was raised when installing (poetry@1.8.2 install) the docs and the admin-ui components:
```
Warning: The current project could not be installed: No file/folder found for package dataset-viewer-doc
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!
```

Set non-package mode

---

chart/values.yaml

Bblock [mitermix/yt-links](https://huggingface.co/datasets/mitermix/yt-links) 
apparently it has too many files and is causing issues on the hub
cc @XciD if you could tell us more about what issues it's causing and how we can avoid this in the future

Block dataset

---

services/worker/src/worker/job_runners/config/parquet_and_info.py

I missed this occurence of DatasetWithTooManyParquetFilesError in https://github.com/huggingface/dataset-viewer/pull/2503
I'd like to deploy this soon for the FW dataset release
cc @guipenedo

Remove remaining DatasetWithTooManyParquetFilesError

---

services/worker/src/worker/executor.py

Now Kube shows the reason "Error" (so not "OOM") but thanks to logging I managed to see that the main process did receive a SIGTERM.
Temporarily disable some signal handling in case they prevent some logs from the children processes to appear, or if it prevents Kube from detecting the OOM.
cc @polinaeterna

Disable signal handling (temporarily for fineweb)

---

libs/libcommon/src/libcommon/exceptions.py
services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/src/worker/job_runners/config/split_names.py
services/worker/src/worker/job_runners/dataset/config_names.py
services/worker/src/worker/job_runners/split/first_rows.py
services/worker/src/worker/job_runners/split/opt_in_out_urls_scan_from_streaming.py
services/worker/src/worker/utils.py

Suggest using the `datasets` convert_to_parquet CLI instead of opening a Discussion.
Additionally, this PR sets a default error message, instead of repeating the same everywhere.
Fix #2742.

Update DatasetWithScriptNotSupportedError message suggesting CLI

---

libs/libcommon/src/libcommon/operations.py
libs/libcommon/src/libcommon/state.py
libs/libcommon/tests/test_backfill.py
libs/libcommon/tests/test_backfill_on_real_graph.py
libs/libcommon/tests/test_operations.py

fixes #2767.
Hopefully, applying this to production will delete a lot of obsolete cache entries after the next backfill

Delete the cache entries before backfilling again if cache is incoherent (inexisting config or split names)

---

docs/poetry.lock
e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/worker/poetry.lock

Update tqdm to >= 4.66.3 to fix vulnerability.
This will fix 13 Dependabot alerts.

Update tqdm to >= 4.66.3 to fix vulnerability

---

.github/workflows/_quality-python.yml
e2e/poetry.lock
e2e/pyproject.toml
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/worker/poetry.lock

Pin `huggingface_hub` to https://github.com/huggingface/huggingface_hub/pull/2271
This should avoid spamming the Hub with `/paths-info` calls when opening files, e.g. to read Parquet files metadata

Use huggingface-hub with paths-info fix

---

libs/libcommon/src/libcommon/exceptions.py
services/worker/src/worker/config.py
services/worker/src/worker/job_runners/config/split_names.py
services/worker/tests/job_runners/config/test_split_names.py

To avoid cases with 300 splits = 300 load_dataset() * 300 data files resolutions = 90k calls to the Hub API to list files

Set max number of splits

---

docs/source/filter.md
e2e/tests/test_53_filter.py
services/search/tests/routes/test_filter.py

Suggest enclosing column names in double quotes in filter docs for robustness with non-alphanumeric characters.
Note that the viewer uses DuckDB: https://duckdb.org/docs/sql/introduction
> DuckDB’s SQL dialect follows the conventions of the PostgreSQL dialect.
And in PostgreSQL SQL Syntax: https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
> Quoted identifiers can contain any character, except the character with code zero. (To include a double quote, write two double quotes.) This allows constructing table or column names that would otherwise not be possible, such as ones containing spaces or ampersands.
Fix #2794.
CC: @lhoestq

Enclose column names in double quotes in filter docs and tests

---

e2e/poetry.lock
e2e/pyproject.toml
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/cache_maintenance/pyproject.toml
jobs/mongodb_migration/poetry.lock
jobs/mongodb_migration/pyproject.toml
libs/libapi/poetry.lock
libs/libapi/pyproject.toml
libs/libapi/tests/test_utils.py
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
libs/libcommon/src/libcommon/croissant_utils.py
libs/libcommon/src/libcommon/simple_cache.py
libs/libcommon/src/libcommon/viewer_utils/features.py
libs/libcommon/src/libcommon/viewer_utils/rows.py
services/admin/poetry.lock
services/admin/pyproject.toml
services/api/poetry.lock
services/api/pyproject.toml
services/rows/poetry.lock
services/rows/pyproject.toml
services/search/poetry.lock
services/search/pyproject.toml
services/sse-api/poetry.lock
services/sse-api/pyproject.toml
services/worker/poetry.lock
services/worker/pyproject.toml
services/worker/tests/job_runners/split/test_first_rows.py
services/worker/tests/test_executor.py

Update ruff CI dependency from 0.2.2 to 0.4.4: 
- v.0.4.0: https://github.com/astral-sh/ruff/releases/tag/v0.4.0
> Ruff's new parser is >2x faster, which translates to a 20-40% speedup for all linting and formatting invocations.
Also allow future minor updates because they were not permitted.

Update ruff CI dependency from 0.2.2 to 0.4.4

---

services/worker/src/worker/job_runners/dataset/compatible_libraries.py

Part of https://github.com/huggingface/dataset-viewer/issues/1443
Currently we have 414 entries with UnexpectedErrorCode because of missing comment value:
`{kind:"dataset-compatible-libraries", http_status:{$ne:200}, "details.cause_exception":"KeyError", "details.copied_from_artifact":{$exists:false}}`
```
File "/src/services/worker/src/worker/job_runners/dataset/compatible_libraries.py", line 507, in get_compatible_libraries_for_csv
loading_code["code"] = DASK_CODE.format(function=function, dataset=dataset, pattern=pattern)
KeyError: 'comment'
```

Add missing comment

---

chart/env/prod.yaml
chart/env/staging.yaml
chart/templates/_common/_ingressTls.tpl
chart/templates/ingress.yaml
chart/templates/services/admin/ingress.yaml
chart/templates/services/api/ingress.yaml
chart/templates/services/rows/ingress.yaml
chart/templates/services/search/ingress.yaml
chart/templates/services/sse-api/ingress.yaml
chart/values.yaml

feat(chart): expose all services through ALB

---

libs/libcommon/src/libcommon/viewer_utils/rows.py

..in first-rows, otherwise we can't show images in the viewer
related to #1416 (issue for iamge and audio type that were also truncated at one point)

Don't truncate urls

---

libs/libcommon/src/libcommon/operations.py
libs/libcommon/tests/test_operations.py

cc @Pierrci 
We enable the viewer for *private* NFAA datasets, owned by a Pro user or Enterprise Hub org.
The viewer is still disallowed on all public NFAA datasets.

allow dataset viewer on private NFAA datasets for Pro and Enterprise Hub

---

e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Update ruff CI dependency to 0.4.5: https://github.com/astral-sh/ruff/releases/tag/v0.4.5

Update ruff CI dependency to 0.4.5

---

docs/poetry.lock
e2e/poetry.lock
e2e/pyproject.toml
front/admin_ui/poetry.lock
front/admin_ui/pyproject.toml
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/admin/pyproject.toml
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Update requests from yanked 2.32.1 to 2.32.2.
Note that 2.32.1 version was yanked: https://pypi.org/project/requests/2.32.1/

Update requests from yanked 2.32.1 to 2.32.2 to fix vulnerability

---

chart/env/prod.yaml
chart/env/staging.yaml

The backfill jobs can restart 2, 3, even 6 times... due to OOM. And we end up with successive cron jobs occurring at the same time.

Give more ram to backfill cron jobs

---

libs/libcommon/src/libcommon/processing_graph.py

fixes https://github.com/huggingface/dataset-viewer/pull/2737#issuecomment-2133157229
> shouldn't i update the job runner's version?
I don't increment the `split-descriptive-statistics` version, because I understand that the responses will not be changed, right?

increase duckdb job runner version (follows #2737)

---

chart/values.yaml

Datasets like https://huggingface.co/datasets/huggingface-leaderboard/details_huggingface__llama-13b are redirected to https://huggingface.co/datasets/open-llm-leaderboard/details_huggingface__llama-13b, and the org https://huggingface.co/datasets/huggingface-leaderboard does not seem to exist, but we currently have 200k jobs for namespace "huggingface-leaderboard", so I'm blocking them.

block huggingface-leaderboard/*

---

e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Update ruff from 0.4.5 to 0.4.6: https://github.com/astral-sh/ruff/releases/tag/v0.4.6

Update ruff from 0.4.5 to 0.4.6

---

chart/env/prod.yaml

We currently have four consecutive backfill-retryable-errors jobs running simultaneously, which could cause an overload of the DB.
I would like to see if it helps somehow other services.

 Run the backfill on retryable errors every 2 hours (not every 30 min)

---

e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Update ruff to 0.4.8: https://github.com/astral-sh/ruff/releases/tag/v0.4.8
> Linter performance has been improved by around 10% on some microbenchmarks

Update ruff to 0.4.8

---

services/worker/src/worker/statistics_utils.py

Will fix duckdb-index step for [common-canvas/commoncatalog-cc-by](https://huggingface.co/datasets/common-canvas/commoncatalog-cc-by)

Fix get_shape in statistics when argument is bytes, not dict 

---

libs/libcommon/src/libcommon/queue.py
libs/libcommon/src/libcommon/simple_cache.py

don't keep the full query result in memory (as mongoengine does by default)
this should reduce the frequency of memory spikes and could have an effect of the memory issues we're having

No mongo cache in DatasetRemovalPlan

---

libs/libcommon/src/libcommon/storage_client.py
libs/libcommon/src/libcommon/url_signer.py

Fix string representation of storage client.
The string representation of the storage client is used by the orchestrator `DeleteDatasetStorageTask` in both the task `id` attribute and as a `label` for prometheus_client Histogram:
- https://github.com/huggingface/dataset-viewer/blob/1ea458cb22396f8af955bf5b1ebbb92d89f0a707/libs/libcommon/src/libcommon/orchestrator.py#L221
- https://github.com/huggingface/dataset-viewer/blob/1ea458cb22396f8af955bf5b1ebbb92d89f0a707/libs/libcommon/src/libcommon/orchestrator.py#L234
Since the inclusion of the URL signer to the storage client by PR:
- #2298
the string representation of the storage client is something like:
```
StorageClient(protocol=s3, storage_root=hf-datasets-server-statics-test/assets, …
```

Fix string representation of storage client

---

libs/libcommon/src/libcommon/orchestrator.py

This is a minor fix of some Tasks ids containing the length of of the string dataset name.
I discovered this while investigating the memory leak issue.

Minor fix id with length of str dataset name

---

.github/workflows/_e2e_tests.yml
.github/workflows/_unit-tests-python.yml
services/admin/Makefile
services/api/Makefile
services/rows/Makefile
services/search/Makefile
services/webhook/Makefile
tools/PythonTest.mk

Fix skipped async tests caused by pytest-memray: do not pass memray argument to pytest.
Fix #2901.

Fix skipped async tests caused by pytest-memray

---

libs/libapi/src/libapi/duckdb.py
libs/libcommon/src/libcommon/parquet_utils.py
libs/libcommon/src/libcommon/storage_client.py
libs/libcommon/tests/test_parquet_utils.py
services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/src/worker/job_runners/config/parquet_metadata.py
services/worker/src/worker/job_runners/split/descriptive_statistics.py
services/worker/src/worker/job_runners/split/duckdb_index.py
services/worker/src/worker/utils.py
services/worker/tests/job_runners/config/test_parquet_metadata.py

`config-parquet-metadata` step is failing again for [FineWeb](https://huggingface.co/datasets/HuggingFaceFW/fineweb) with errors like 
```
"Could not read the parquet files: 504, message='Gateway Time-out', url=URL('https://huggingface.co/datasets/HuggingFaceFW/fineweb/resolve/refs%2Fconvert%2Fparquet/default/train-part1/4089.parquet')"
```
Maybe this would help (the same is used in `config-parquet-and-info` step which works).
Previous fix was https://github.com/huggingface/dataset-viewer/pull/2884

Use `HfFileSystem` in config-parquet-metadata step instead of `HttpFileSystem`

---

libs/libcommon/src/libcommon/processing_graph.py

It has to do HTTP requests, it can manage big objects, and it depends on `datasets`. So... it might be better to process it with "medium" workers, not "light" ones that generally only transform cached entries.

dataset-filetypes is not a small step

---

libs/libcommon/src/libcommon/state.py

Do not keep unnecessary DataFrames in memory in State classes and instead forward them for use only in class instantiation.
This PR reduces memory use by avoiding keeping unnecessary DataFrames in all State classes.
This PR supersedes (neither copies nor views are longer necessary):
- #2903

Do not keep DataFrames in memory in State classes

---

front/admin_ui/app.py

In the admin-ui, some datasets have all the features working (is-valid) but are shown as errors.
This is due to gated datasets; I just added another sign to identify those and let us know that the issue is unrelated to jobs not being correctly processed.
Another question is if we should consider this dataset as part of the coverage metric since we need to know the value.
Or maybe there is another way to automatically subscribe to the admin-UI user token for those datasets?

admin-ui: Do not mark gated datasets as error

---

libs/libcommon/src/libcommon/processing_graph.py
services/worker/src/worker/job_runners/dataset/hub_cache.py
services/worker/src/worker/job_runners/dataset/is_valid.py
services/worker/tests/job_runners/dataset/test_hub_cache.py
services/worker/tests/job_runners/dataset/test_is_valid.py

We always want to have a "status", even if some of the previous steps are not available.

Do not propagate error for is valid and hub cache

---

libs/libcommon/src/libcommon/orchestrator.py
libs/libcommon/src/libcommon/queue.py
libs/libcommon/tests/test_orchestrator.py

When we change the priority of a job manually after it has started, we want the children jobs to use the same priority

Use current priority for children jobs

---

front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Update scikit-learn to 1.5.0 to fix vulnerability.
This will close 12 Dependabot alerts.

Update scikit-learn to 1.5.0 to fix vulnerability

---

services/worker/src/worker/job_runners/config/parquet_and_info.py
services/worker/tests/fixtures/files.py
services/worker/tests/job_runners/config/test_parquet_and_info.py

I simply had to track metadata reads only once to fix the estimator.
(otherwise every file opened in a zip archive triggers an additional read of the metadata with the central directory of the zip file that prevents the estimator from converging)
ex: locally and on only 100MB of parquet conversion (prod is 5GB), it estimates 47871 examples on https://huggingface.co/datasets/datasets-maintainers/test_many_zip_with_images_MSCOCO_zip (true value is exactly 50k)
Unrelared, but I noticed that parquet conversion of zip files is super slooooooowww, we'll have to improve that at one point because it can surely take more than 40min to run. When tested in prod, an error happens before that though (JobManagerCrashedError) which suggests a termination by kubernetes.

Fix estimate info for zip datasets

---

jobs/mongodb_migration/src/mongodb_migration/collector.py
jobs/mongodb_migration/src/mongodb_migration/deletion_migrations.py
libs/libcommon/src/libcommon/queue/dataset_blockages.py
libs/libcommon/src/libcommon/queue/past_jobs.py

blocked for 1h -> 6h
based on the last 6h -> 1h
The effect should be to block more datasets, more quickly, and for a longer time. Currently, all the resources are still dedicated to datasets that are updated every xxx minutes.

Increase blockage duration

---

docs/source/_toctree.yml

Follow up to https://github.com/huggingface/dataset-viewer/pull/2941
I realized the docs were not building in the CI: https://github.com/huggingface/dataset-viewer/actions/runs/9648374360/job/26609396615
Apologies for not checking this in my prior PR.

add cudf to toctree

---

docs/poetry.lock
e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Update urllib3 to 1.26.19 and 2.2.2 to fix vulnerability.
This PR will close 14 Dependabot alerts.

Update urllib3 to 1.26.19 and 2.2.2 to fix vulnerability

---

libs/libcommon/src/libcommon/orchestrator.py
libs/libcommon/tests/test_orchestrator_smart_update.py
libs/libcommon/tests/utils.py

...since it was causing 
```
smart_update_dataset failed with PermissionError: [Errno 13] Permission denied: '/.cache'
```
I used the HfFileSystem instead to read the README.md files, since it doesn't use caching

No cache in smart update

---

services/worker/src/worker/job_runners/dataset/modalities.py
services/worker/tests/job_runners/dataset/test_modalities.py

Fix modalities false positives for
- https://huggingface.co/datasets/chenxx1/jia
- https://huggingface.co/datasets/proj-persona/PersonaHub
- https://huggingface.co/datasets/BAAI/Infinity-Instruct
- https://huggingface.co/datasets/m-a-p/COIG-CQIA
- https://huggingface.co/datasets/Magpie-Align/Magpie-Pro-300K-Filtered
I added two thresholds to get less false positives:
- one general threshold to ignore file types that are <10% of the files
- one additional threshold specific to images in presence of csv/json/parquet, since images are often used in README as figures 
cc @severo 
This should take care of most false positives, and we can refine later if needed

Add threshold to modalities from filetypes

---

docs/poetry.lock
e2e/poetry.lock
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Update certifi to 2024.7.4 to fix vulnerability.
It will close 14 Dependabot alerts.

Update certifi to 2024.7.4 to fix vulnerability

---

front/admin_ui/poetry.lock

Update zipp to 3.19.2 to fix vulnerability.
It will close 1 Dependabot alert.

Update zipp to 3.19.2 to fix vulnerability

---

services/api/README.md
services/worker/src/worker/dtos.py
services/worker/src/worker/job_runners/dataset/compatible_libraries.py
services/worker/src/worker/job_runners/dataset/hub_cache.py
services/worker/tests/job_runners/dataset/test_compatible_libraries.py
services/worker/tests/job_runners/dataset/test_hub_cache.py

Note that I don't migrate to remove the field from the cache (we could do it, but not sure it's worth the pain)
Better wait for https://github.com/huggingface-internal/moon-landing/pull/10591 (internal) to be deployed on the Hub before merging.

remove the 'tags' field from the Hub cache response

---

libs/libcommon/src/libcommon/processing_graph.py
libs/libcommon/tests/test_processing_graph.py
libs/libcommon/tests/test_utils.py
services/worker/src/worker/job_runners/dataset/modalities.py
services/worker/tests/job_runners/dataset/test_modalities.py

close https://github.com/huggingface/dataset-viewer/issues/2970 for images (audio can be taken care of later)

Count image urls as image modality

---

services/worker/poetry.lock

Update setuptools to 70.3.0 to fix vulnerability.
It will close 1 Dependabot alert.

Update setuptools to 70.3.0 to fix vulnerability

---

.github/workflows/doc-build.yml
.github/workflows/doc-pr-build.yml
.github/workflows/doc-pr-upload.yml
DEVELOPER_GUIDE.md
README.md
docs/Makefile
docs/source/croissant.md
docs/source/openapi.json
jobs/cache_maintenance/src/cache_maintenance/discussions.py
services/api/README.md
services/rows/README.md
services/search/README.md
services/webhook/README.md
services/worker/src/worker/job_runners/dataset/croissant_crumbs.py

This change should move https://huggingface.co/docs/datasets-server to https://huggingface.co/docs/dataset-viewer.
cc @mishig25: we also need to redirect https://huggingface.co/docs/datasets-server to https://huggingface.co/docs/dataset-viewer. Where do we do it?

move the docs page

---

services/worker/src/worker/dtos.py
services/worker/src/worker/job_runners/dataset/compatible_libraries.py
services/worker/tests/job_runners/dataset/test_compatible_libraries.py

Hello from the Polars team! We've recently added support for scanning Hugging Face datasets, and to make it easier for users we're hoping that Polars code snippets could be added under the "Use this dataset" section on the dataset viewer webpage, next to the other libraries.
Specifically, here's where we'd like to add Polars as an option:

Add Polars loading code

---

services/worker/src/worker/job_runners/dataset/compatible_libraries.py

json datasets currently don't have a "Use this dataset" button because the compatible-libraries job fails
note that this doesn't impact datasets with .jsonl files

Fix json compatible libraries

---

services/worker/src/worker/job_runners/dataset/compatible_libraries.py
services/worker/tests/job_runners/dataset/test_compatible_libraries.py

We simply don't put Polars as a supported library when we're not able to detect if it's JSON or JSONL.
TODO: transform `**/*` to a list of files? In the case of `datasets/tcor0005/langchain-docs-400-chunksize`, it's a single file
---
The error we fix:
```
tests/job_runners/dataset/test_compatible_libraries.py:564:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/worker/job_runners/dataset/compatible_libraries.py:700: in get_polars_compatible_library
is_json_lines = ".jsonl" in first_file or HfFileSystem(token=hf_token).open(first_file, "r").read(1) != "[" …
```

fix 'FileNotFoundError' in polars detection function

---

libs/libcommon/src/libcommon/queue/metrics.py

deployment (migration script) error:
```
INFO: 2024-07-31 22:33:14,880 - root - Start migrations
INFO: 2024-07-31 22:33:14,926 - root - 72 migrations have already been applied. They will be skipped.
INFO: 2024-07-31 22:33:14,927 - root - Migrate 20240731143600: add to the migrations collection
INFO: 2024-07-31 22:33:14,931 - root - Migrate 20240731143600: apply
INFO: 2024-07-31 22:33:14,931 - root - If missing, add the 'dataset_status' field with the default value 'normal' to the jobs metrics
INFO: 2024-07-31 22:33:14,941 - root - Migrate 20240731143600: validate
INFO: 2024-07-31 22:33:14,941 - root - Ensure that a random selection of jobs metrics have the 'dataset_status' field
ERROR: 2024-07-31 22:33:14,943 - root - Migration failed: An existing index has the same name as the requested …
```

add a field to the index + it should fix the deployment issue

---

e2e/tests/test_21_api_metrics.py
e2e/tests/test_31_admin_metrics.py
e2e/tests/test_41_rows_metrics.py
e2e/tests/test_51_search_metrics.py

Fix CI e2e admin test_metrics by adding missing `dataset_status="normal"` label.
This CI failure was introduced by:
- #3008
Fix #3021.

Fix CI e2e admin test_metrics with missing dataset_status

---

libs/libapi/tests/test_response.py

Fix CI test StorageClient.url_preparator.
This fail in CI tests was introduced after:
- #2966
See: https://github.com/huggingface/dataset-viewer/actions/runs/10350752694/job/28648303009?pr=3018
```
FAILED tests/test_response.py::test_create_response_with_image - AssertionError: assert [{'row': {'im...d_cells': []}] == [{'row': {'im...d_cells': []}]
At index 0 diff: {'row_idx': 0, 'row': {'image': {'src': 'http://localhost/cached-assets/ds_image/--/{dataset_git_revision}/--/default/train/0/image/image.jpg', 'height': 480, 'width': 640}}, 'truncated_cells': []} != {'row_idx': 0, 'row': {'image': {'src': 'http://localhost/cached-assets/ds_image/--/revision/--/default/train/0/image/image.jpg', 'height': 480, 'width': 640}}, 'truncated_cells': []}
Full diff:
[
{
'row': {
'image': {
'height': …
```

Fix CI test StorageClient.url_preparator

---

services/worker/tests/job_runners/config/test_split_names.py
services/worker/tests/job_runners/dataset/test_config_names.py

Fix CI worker tests for gated datasets.
Fix #3025.

Fix CI worker tests for gated datasets

---

libs/libcommon/src/libcommon/viewer_utils/asset.py

I had set it to `audio/opus` which does not exist.
https://datatracker.ietf.org/doc/html/rfc7845.html#section-9
> An "Ogg Opus file" consists of one or more sequentially multiplexed
segments, each containing exactly one Ogg Opus stream.  The
RECOMMENDED mime-type for Ogg Opus files is "audio/ogg".
>    The RECOMMENDED filename extension for Ogg Opus files is '.opus'.
> When Opus is concurrently multiplexed with other streams in an Ogg
container, one SHOULD use one of the "audio/ogg", "video/ogg", or
"application/ogg" mime-types, as defined in [[RFC5334](https://datatracker.ietf.org/doc/html/rfc5334)].
https://github.com/user-attachments/assets/caed4ee5-975d-4233-9cf8-31fd755b2429

mediatype of opus is audio/ogg

---

docs/source/valid.md

At the moment, the examples fail because rotten_tomatoes moved to https://huggingface.co/datasets/cornell-movie-review-data/rotten_tomatoes

Update to new dataset ID in example

---

libs/libapi/src/libapi/authentication.py
libs/libapi/src/libapi/exceptions.py
libs/libapi/tests/test_authentication.py

fixes bug at https://github.com/huggingface/dataset-viewer/issues/2688#issuecomment-2303305529

return 404 when accessing a renamed dataset, instead of unexpected error

---

libs/libcommon/src/libcommon/constants.py
services/worker/src/worker/job_runners/config/parquet_and_info.py

Current:
https://huggingface.co/datasets/Recag/Rp_CommonC_53
```
The dataset generation failed
Error code:   DatasetGenerationError
Exception:    DatasetGenerationError
Message:      An error occurred while generating the dataset
Traceback:    Traceback (most recent call last):
File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/packaged_modules/json/json.py", line 145, in _generate_tables
dataset = json.load(f)
File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 340, in decode
raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 …
```

show the traceback of the cause, it's clearer

---

e2e/tests/conftest.py
e2e/tests/test_14_statistics.py
front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock
services/worker/tests/fixtures/hub.py

Update datasets to 2.20.0.
This PR is intended to address the CI errors raised by this update, as a first step before:
- #3037
Fixes after the update of `datasets`:
- Pass `trust_remote_code=True` for script dataset: 227f2c4
- Use JSON-Lines (instead of JSON) dataset in `test_statistics_endpoint` to avoid pandas bug that downcasts float to int column: a86d040

Update datasets to 2.20.0

---

services/api/src/api/routes/endpoint.py

previously we had the laion2b results, but laion re-released the dataset with an improved filtering based on safety

Add relaion2b dataset opt-out results

---

services/worker/src/worker/job_runners/_job_runner_with_datasets_cache.py
services/worker/tests/job_runners/test__job_runner_with_datasets_cache.py

Set custom `huggingface-hub` cache.
Fix #3074.

Set custom huggingface-hub cache

---

front/admin_ui/poetry.lock
jobs/cache_maintenance/poetry.lock
jobs/mongodb_migration/poetry.lock
libs/libapi/poetry.lock
libs/libcommon/poetry.lock
libs/libcommon/pyproject.toml
services/admin/poetry.lock
services/api/poetry.lock
services/rows/poetry.lock
services/search/poetry.lock
services/sse-api/poetry.lock
services/webhook/poetry.lock
services/worker/poetry.lock

Since it causes segfaults. I also modified `datasets` to allow using Video with disabled decoding
(I could use Video(decode=False) here but the disable_video_decoding context manager is easier to use and avoids side effects like modifyign the `features` object)

Remove decord

---

services/worker/src/worker/executor.py

workers i nstaging env don't start because of that
```
DEBUG: 2024-10-29 17:29:31,793 - mirakuru.base - Starting process: ['/src/services/worker/.venv/bin/python', '/src/services/worker/src/worker/start_worker_loop.py', '--print-worker-state-path']
Traceback (most recent call last):
File "/src/services/worker/src/worker/main.py", line 76, in <module>
worker_executor.start()
File "/src/services/worker/src/worker/executor.py", line 86, in start
worker_loop_executor.start()  # blocking until the banner is printed
File "/src/services/worker/.venv/lib/python3.9/site-packages/mirakuru/output.py", line 105, in start
self.wait_for(await_for_output)
File "/src/services/worker/.venv/lib/python3.9/site-packages/mirakuru/base.py", line 450, in wait_for
raise TimeoutExpired(self, …
```

Increase executor time out for staging

---

libs/libcommon/src/libcommon/processing_graph.py

cc @ccl-core this way all the croissant-crumbs will be updated with the latest changes

bump croissant job version

---

services/rows/src/rows/routes/rows.py

Fix pagination for https://huggingface.co/datasets/foursquare/fsq-os-places and https://huggingface.co/datasets/Major-TOM/Core-S2L2A which have binary columns. Currently it raises an UnexpectedApiError

Fix excluded binary column in rows

---

docs/source/openapi.json

We are adding support for more generic types for the SQL Console in the AudioCell [Internal PR](https://github.com/huggingface-internal/moon-landing/pull/11843#discussion_r1871635683).

AudioCell - set audio type to string

---

chart/env/prod.yaml

was causing timeout on get_latest_dataset_revision_if_supported_or_raise preventing jobs from being added to the queue after dataset-config-names

higher timeout

---

libs/libcommon/src/libcommon/operations.py

I got this which triggered a recompute of the dataset but I don't know why it happened, adding some logs in case it happens again
> WARNING: 2024-12-10 10:35:59,554 - root - Dataset HuggingFaceFW/fineweb-2 has incoherent entries in the cache. Let's first delete the dataset, then backfill again.

Log incoherent state error

---

libs/libcommon/src/libcommon/state.py

Fix issues like
> WARNING: 2024-12-13 10:18:31,382 - root - Dataset HuggingFaceFW/fineweb-2 has incoherent entries in the cache. Let's first delete the dataset, then backfill again. UnexceptedSplitNamesError: Unexpected split names for dataset=HuggingFaceFW/fineweb-2 config=mor_Latn (1): ['train']
it happended because at the time of the backfill:
- config-split-names wasn't ready yet for `config=mor_Latn`
- split-first-rows was ready for `config=mor_Latn` and `split=train` (possible since the job if triggered by both config-split-names and config-parquet-metadata which enables reading from parquet to get the first rows)

Fix backfill deleting cache when split names not ready

---

docs/source/_toctree.yml
docs/source/parquet_process.md
docs/source/postgresql.md
jobs/cache_maintenance/src/cache_maintenance/discussions.py

Add documentation for how to use PostgreSQL with pgai to access the dataset.

Add PostgreSQL as a possible viewer

---

docs/source/analyze_data.md
docs/source/clickhouse.md
docs/source/cudf.md
docs/source/duckdb.md
docs/source/first_rows.md
docs/source/mlcroissant.md
docs/source/pandas.md
docs/source/polars.md

Replacing `barilan/blog_authorship_corpus` with `tasksource/blog_authorship_corpus` since the former is no longer accessible due to being a script-based dataset, and replacing `ETDataset/ett` with `GEM/SciDuet` for the same reason. Additionally, making minor fixes.

doc: Update inaccessible datasets

---

docs/source/postgresql.md

Markdown formatting isn't working well inside the `<Tip>` element.
This might be affecting other pages as well, but this is the one I came across.

chore: update markdown formatting inside <Tip>

---

libs/libcommon/src/libcommon/croissant_utils.py

This PR adds a few missing value types. This would avoid skipping columns for a few more datasets.

Include more value types to the hf to crs mapping

---

libs/libcommon/src/libcommon/croissant_utils.py
libs/libcommon/tests/test_croissant_utils.py

This is used to set the correct Transform operations.
This was needed in particular for this dataset: https://huggingface.co/datasets/allenai/WildChat-1M as some of its feature names contain slashes. This creates a problem when the slashes are included non-escaped as part of the json_path attribute of a Transform operation.
An example of the corrected croissant def, as it will be now generated by HF, is here: https://github.com/mlcommons/croissant/pull/829

Add function to convert a feature name to a valid jsonpath.

---

libs/libcommon/src/libcommon/orchestrator.py

The `/api/.../compare/:compare` endpoint does support app tokens, unlike `/:rev.diff`
and if I query the git comparison `{rev}^..{rev}` I get the same output as `/:rev.diff`, so no need to update the parsing
follows https://github.com/huggingface/dataset-viewer/pull/3163
original pr for smart updates: https://github.com/huggingface/dataset-viewer/pull/2788

Re-enable smart update for private and gated repos

---

libs/libcommon/src/libcommon/duckdb_utils.py
services/search/src/search/routes/filter.py
services/search/src/search/routes/search.py

I spent some time trying to optimize the on-the-fly searching but couldn't find a way to make it faster.
It seems FTS indexing can take a couple minutes to run, maybe because of https://github.com/duckdb/duckdb-fts/issues/7
I tried not using FTS indexing but searching on 5GB without index takes 1min+ (or 15sec if you remove tokenization/stemming but you don't end up with great results)
For now I'll just enable more datasets to do more tests on other types of data (small text, big text, image and audio)

Enable more datasets to work without `refs/convert/duckdb`

---

libs/libapi/src/libapi/duckdb.py
libs/libcommon/src/libcommon/duckdb_utils.py
services/admin/src/admin/authentication.py
services/search/src/search/routes/filter.py
services/search/src/search/routes/search.py

it was taking way too much time to index datasets for full text search, and it's pretty important now that we want to get rid of `refs/convert/duckdb` and index only when necessary
follows #3166 
todo:

Parallelize tokenization to enable fast on-the-fly indexing

---

services/search/src/search/routes/search.py

fix e.g. for /search dataset='nvidia/describe-anything-dataset' config='COCOStuff' split='train' query='pokemon' offset=0 length=100` with 0 results

Fix empty result in search

---

libs/libcommon/src/libcommon/viewer_utils/features.py
services/rows/src/rows/routes/rows.py
services/worker/src/worker/job_runners/split/first_rows.py

fix for https://huggingface.co/datasets/nvidia/describe-anything-dataset
- support binary for /rows, /filter and /search
- truncate too long binary data

Always truncate binary data

---

services/worker/src/worker/job_runners/_job_runner_with_datasets_cache.py
services/worker/tests/job_runners/test__job_runner_with_datasets_cache.py

fix this error in parquet conversion
```
Data processing error: I/O error: Permission denied (os error 13)
Error code:   UnexpectedError
```

Set xet cache dir
