huggingface/dataset-viewer

- chart/docker-images.yaml
- services/worker/src/worker/features.py
> fix: 🐛 fix tests for the Sequence cells

- chart/docker-images.yaml
- workers/splits/src/splits/response.py
> feat: 🎸 sort the configs alphabetically

- .github/workflows/doc-pr-build.yml
- .github/workflows/doc-pr-delete.yml
Reverts huggingface/datasets-server#632
Everything is handled on the doc-builder side now 😊
> Revert "Update pr docs actions"

- chart/docker-images.yaml
- workers/first_rows/poetry.lock
- workers/first_rows/pyproject.toml
- workers/splits/poetry.lock
- workers/splits/pyproject.toml
see
https://huggingface.co/datasets/mrdbourke/food_vision_199_classes/discussions/1
> feat: 🎸 upgrade to datasets 2.7.1

- chart/docker-images.yaml
- workers/datasets_based/src/datasets_based/workers/_datasets_based_worker.py
- workers/datasets_based/src/datasets_based/workers/first_rows.py
- workers/datasets_based/src/datasets_based/workers/parquet.py
- workers/datasets_based/src/datasets_based/workers/splits.py
as datasets library has been upgraded, we want to upgrade the major version of the workers so that jobs are not skipped if re-run on the same commit (erroneous ones can be OK now)
> feat: 🎸 give each worker its own version + upgrade to 2.0.0

- chart/env/prod.yaml
needed today for allenai, see #674
> feat: 🎸 allow more concurrent jobs fo the same namespace

- chart/env/prod.yaml
error was: Warning:
spec.template.spec.containers[0].resources.requests[memory]: fractional byte value "107374182400m" is invalid, must be an integer
> fix: 🐛 fix memory specification + increase pods in /parquet

- chart/env/prod.yaml
> feat: 🎸 reduce logs level from DEBUG to INFO

- front/admin_ui/app.py
this way we can deploy in a private Space and don't ask for the token
> Add HF_TOKEN env var for admin ui

- workers/datasets_based/src/datasets_based/workers/first_rows.py
The fallback will be removed once
https://github.com/huggingface/datasets-server/issues/755 is implemented. Meanwhile, we hide the parameter to prepare deprecation.
> refactor: 💡 hard-code the value of the fallback

- chart/env/dev.yaml
- chart/env/prod.yaml
- chart/values.yaml
Updating docker image hash values
> Updating docker image hash

- chart/templates/_helpers.tpl
- chart/values.yaml
https://github.com/huggingface/private-hub-package/issues/15
> Allow to use http instead of https

- jobs/mongodb_migration/src/mongodb_migration/config.py
- libs/libcommon/src/libcommon/config.py
- services/admin/src/admin/config.py
- services/api/src/api/config.py
- workers/datasets_based/src/datasets_based/config.py
- workers/datasets_based/src/datasets_based/resources.py
See https://stackoverflow.com/questions/12179271/meaning-of-classmethod-and-staticmethod-for-beginner for example
Depends on: #790
> use classmethod for factories instead of staticmethod

- services/worker/src/worker/main.py
- services/worker/tests/fixtures/hub.py
- services/worker/tests/test_executor.py
Last step for https://github.com/huggingface/datasets-server/issues/741 regarding zombies
> Set error response when zombie job is killed

- e2e/poetry.lock
- front/admin_ui/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libcommon/poetry.lock
- services/admin/poetry.lock
- services/api/poetry.lock
- services/worker/poetry.lock
- services/worker/pyproject.toml
> chore: 🤖 upgrade dependencies to fix vulnerability

- services/worker/src/worker/job_runners/split_names_from_dataset_info.py
- services/worker/src/worker/job_runners/split_names_from_streaming.py
As per PR https://github.com/huggingface/datasets-server/pull/878, worker versions should have been increased
> Increase version of workers /split-names from streaming and dataset info

- chart/Chart.yaml
- chart/nginx-templates/default.conf.template
- e2e/tests/test_10_healthcheck.py
- services/api/src/api/app.py
<strike>It is needed by argocd</strike>
It is needed by the ALB
It's defined at https://github.com/huggingface/datasets-server/blob/fb48ed36cd41b13fba88b6b18072faf1bbd1fb62/chart/env/prod.yaml#L125
> Publish /healthcheck again

- libs/libcommon/src/libcommon/queue.py
> feat: 🎸 add an index to the jobs collection

- .github/workflows/chart-pr.yml
- chart/Chart.lock
- chart/Chart.yaml
- chart/env/prod.yaml
- chart/templates/_helpers.tpl
- chart/templates/ingress.yaml
- chart/templates/jobs/mongodb-migration/job.yaml
- chart/templates/pvc.yaml
- chart/templates/reverse-proxy/service.yaml
- chart/templates/services/admin/service.yaml
- chart/templates/services/api/service.yaml
- chart/values.yaml
More info here : https://github.com/huggingface/private-hub-package/issues/24
> Allow to use service nodeport

- chart/env/prod.yaml
- libs/libcommon/src/libcommon/log.py
This reverts commit 6643f943619a6b8c2b4449c12eafc883db1873fe.
Do not merge or deploy while the investigation is not finished.
> Revert "feat: 🎸 change log level to DEBUG (#917)"

- e2e/tests/fixtures/hub.py
- libs/libcommon/src/libcommon/dataset.py
- services/admin/tests/fixtures/hub.py
- services/worker/tests/fixtures/hub.py
> Fix gated (gated=True -> gated="auto")

- .github/workflows/_e2e_tests.yml
- chart/templates/services/api/_container.tpl
- chart/values.yaml
- services/api/README.md
- services/api/poetry.lock
- services/api/pyproject.toml
- services/api/src/api/app.py
- services/api/src/api/authentication.py
- services/api/src/api/config.py
- services/api/src/api/jwt_token.py
- services/api/src/api/routes/endpoint.py
- services/api/src/api/routes/valid.py
- services/api/src/api/utils.py
- services/api/tests/test_authentication.py
- services/api/tests/test_jwt_token.py
- tools/docker-compose-datasets-server.yml
- tools/docker-compose-dev-datasets-server.yml
Alternative to https://github.com/huggingface/datasets-server/pull/897, corresponding to option 2 in https://github.com/huggingface/datasets-server/issues/877#issuecomment-1456474625
> Add jwt to bypass auth

- chart/env/prod.yaml
This PR reduces the log level to INFO. To be merged after the investigation is done. See https://github.com/huggingface/datasets-server/pull/939
> Revert log increase

- chart/env/prod.yaml
- services/api/src/api/routes/webhook.py
these errors should not occur, and we should be alerted when it's the case.
> feat: 🎸 add logs in case of error in /webhook

- chart/env/prod.yaml
Investigation on #950 has finished, we can reduce the log level
> feat: 🎸 reduce log level to INFO in prod

- .github/workflows/_e2e_tests.yml
- chart/env/dev.yaml
- chart/env/prod.yaml
- chart/templates/_envCommon.tpl
- chart/templates/_envLog.tpl
- chart/templates/jobs/cache-refresh/_container.tpl
- chart/templates/jobs/mongodb-migration/_container.tpl
- chart/templates/services/admin/_container.tpl
- chart/templates/services/api/_container.tpl
- chart/templates/worker/_container.tpl
- chart/values.yaml
- e2e/Makefile
- jobs/cache_refresh/src/cache_refresh/config.py
- jobs/cache_refresh/src/cache_refresh/main.py
- jobs/mongodb_migration/src/mongodb_migration/config.py
- jobs/mongodb_migration/src/mongodb_migration/main.py
- libs/libcommon/README.md
- libs/libcommon/src/libcommon/config.py
- libs/libcommon/src/libcommon/log.py
- libs/libcommon/tests/test_config.py
- services/admin/src/admin/app.py
- services/admin/src/admin/config.py
- services/api/src/api/app.py
- services/api/src/api/config.py
- services/worker/src/worker/config.py
- services/worker/src/worker/main.py
- services/worker/src/worker/start_worker_loop.py
- tools/docker-compose-base.yml
- tools/docker-compose-dev-base.yml
This allows to define LOG_LEVEL without having to define other "common" variables like HF_ENDPOINT and HF_TOKEN
Required by https://github.com/huggingface/datasets-server/issues/994
> feat: 🎸 move COMMON_LOG_LEVEL to LOG_LEVEL

- services/worker/poetry.lock
- services/worker/pyproject.toml
> Update datasets dependency to 2.11.0 version

- jobs/cache_refresh/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- libs/libcommon/src/libcommon/processing_graph.py
- libs/libcommon/tests/test_processing_steps.py
- services/admin/poetry.lock
- services/api/poetry.lock
- services/worker/poetry.lock
We now rely on a specialized library to compute the graph. It will help when we allow multiple parents per step.
See https://github.com/huggingface/datasets-server/issues/1014
> Use networkx to compute the processing graph

- services/api/src/api/routes/rows.py
Found this bug while adding tests
> Fix RowsIndex.query

- chart/env/prod.yaml
- chart/templates/jobs/cache-maintenance/job.yaml
- jobs/cache_maintenance/src/cache_maintenance/backfill.py
Increase resources for cache_maintenance job - backfill action.
Adding logs each 100 datasets in backfill
> Increase backgill resources and adding logs

- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/test_simple_cache.py
Closes https://github.com/huggingface/datasets-server/issues/948
> Adding dataset, config and split in dataset-status

- .vscode/monorepo.code-workspace
- front/admin_ui/app.py
Adding new tab in admin-ui to get dataset status
Closes https://github.com/huggingface/datasets-server/issues/822
Depends on https://github.com/huggingface/datasets-server/pull/1041
> Dataset status in admin ui

- libs/libcommon/src/libcommon/processing_graph.py
- libs/libcommon/tests/test_processing_steps.py
- libs/libcommon/tests/test_state.py
Even if a parent is an ancestor of another parent, we want to get it in the list.
> fix: 🐛 remove wrong filtering of the step parents

- libs/libcommon/src/libcommon/state.py
- libs/libcommon/tests/test_state.py
Now, the fan-in steps are refreshed when one of the parent artifacts is updated (ie. if a config-parquet entry is computed, the dataset-parquet artifact is marked for refresh). Before, they were not updated in that case, which was a bug.
> Handle fan in steps

- services/worker/src/worker/config.py
- services/worker/src/worker/job_runner_factory.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/job_runners/parquet_and_dataset_info.py
- services/worker/src/worker/job_runners/split/first_rows_from_parquet.py
- services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
- services/worker/tests/conftest.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
- services/worker/tests/job_runners/split/test_first_rows_from_parquet.py
- services/worker/tests/job_runners/split/test_first_rows_from_streaming.py
- services/worker/tests/job_runners/test_parquet_and_dataset_info.py
instead of creating a FirstRowsConfig every time
> refactor: 💡 create the configs at startup

- e2e/tests/test_11_api.py
- e2e/tests/utils.py
no need to test every endpoint on every auth case
> test: 💍 make the e2e tests on API clearer

- libs/libcommon/src/libcommon/state.py
- libs/libcommon/tests/test_state.py
the relation created by "requires" means that the step will be refreshed when the required step will be refreshed. (should we change the name?).
> fix: 🐛 remove the wrong concept of blocked_by_parent

- libs/libcommon/src/libcommon/state.py
- libs/libcommon/tests/test_state.py
Split steps were not visible on dataset state
> Fix key name for split names

- services/worker/src/worker/job_runners/config_names.py
With this PR, we raise a specific informative error when a dataset script tries to import a module/library that is not installed.
Note that once we propagate error messages from the children jobs, we only need this message in the root job "/config-names".
Fix #1083.
> Raise informative error when importing non-installed module

- chart/env/dev.yaml
- chart/env/prod.yaml
- chart/templates/worker/_container.tpl
- chart/values.yaml
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/tests/test_queue.py
- libs/libcommon/tests/test_state.py
- services/worker/README.md
- services/worker/pyproject.toml
- services/worker/src/worker/config.py
- services/worker/src/worker/loop.py
Now, we can list:
- the jobs types that a worker cannot process: `WORKER_JOB_TYPES_BLOCKED`
- the jobs types that a worker can process: `WORKER_JOB_TYPES_ONLY`
> Add WORKER_JOB_TYPES_BLOCKED

- jobs/cache_maintenance/src/cache_maintenance/backfill.py
> feat: 🎸 add logs to backill job

- chart/Chart.yaml
- chart/env/prod.yaml
- chart/templates/cron-jobs/backfill/_container.tpl
- chart/templates/jobs/cache-maintenance/_container.tpl
- chart/values.yaml
- jobs/cache_maintenance/README.md
- jobs/cache_maintenance/src/cache_maintenance/backfill.py
- jobs/cache_maintenance/src/cache_maintenance/config.py
- jobs/cache_maintenance/src/cache_maintenance/main.py
- libs/libcommon/src/libcommon/state.py
- libs/libcommon/tests/test_state.py
To be launched after https://github.com/huggingface/datasets-server/pull/1116 is merged, to recompute the erroneous UnexpectedError entries
> Recompute all the cache entries with error code "UnexpectedError"

- front/admin_ui/app.py
sorry i forgot to push one commit to the previous plot PR, this is to make test on nodes visible.
> change color and size of nodes

- services/worker/poetry.lock
- services/worker/pyproject.toml
> feat: 🎸 upgrade tensorflow

- services/worker/src/worker/job_manager.py
> fix: 🐛 hot fix - catch exception on git revision

- services/api/src/api/routes/rows.py
- services/api/tests/routes/test_rows.py
I still keep "Audio" unsupported since there are some errors with librosa on API workers
> Use parquet metadata for all datasets

- libs/libcommon/src/libcommon/queue.py
> feat: 🎸 add an index

- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/src/libcommon/state.py
- libs/libcommon/tests/state/test_plan.py
- libs/libcommon/tests/state/test_plan_on_real_graph.py
- libs/libcommon/tests/state/utils.py
- services/api/src/api/routes/endpoint.py
instead of one (or multiple) operations for every job creation
> feat: 🎸 create all jobs in backfill in one operation

- docs/source/quick_start.mdx
> Fix link to first_rows docs

- .github/workflows/_quality-python.yml
- services/worker/poetry.lock
- services/worker/pyproject.toml
- tools/Python.mk
Remove `torchaudio` dependency.
Fix partially #1281.
> Remove torchaudio dependency

- chart/env/prod.yaml
the cache has been filled, no more jobs to be run
> feat: 🎸 remove temporal workers

- libs/libcommon/src/libcommon/exceptions.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/fixtures/files.py
- services/worker/tests/fixtures/hub.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
Do not support datasets that require manual download.
Fix #1307.
> Raise if dataset requires manual download

- chart/env/prod.yaml
and restore the number of resources for the "light" jobs (all, but 6) that never have pending jobs
> feat: 🎸 increase resources again

- chart/env/prod.yaml
also: restore a bit more replicas for the light job runners, because we have a lot of waiting jobs for them now.
> feat: 🎸 increase the resources even more

- front/admin_ui/app.py
following https://github.com/huggingface/datasets-server/pull/1264
> fix refresh in admin ui

- docs/source/parquet_process.mdx
> Fix missing word and typo in parquet_process docs

- chart/env/prod.yaml
> feat: 🎸 reduce resources

- chart/env/dev.yaml
- chart/env/prod.yaml
- chart/templates/worker/_container.tpl
- chart/values.yaml
- libs/libcommon/README.md
- libs/libcommon/src/libcommon/config.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/tests/test_queue.py
- services/worker/src/worker/loop.py
- services/worker/src/worker/start_worker_loop.py
- services/worker/tests/test_loop.py
- tools/docker-compose-base.yml
- tools/docker-compose-dev-base.yml
It's not needed anymore. Let's simplify the code
> feat: 🎸 remove limit on number of started jobs per namespace

- .github/workflows/_quality-python.yml
- chart/env/dev.yaml
- chart/env/prod.yaml
- chart/templates/worker/_container.tpl
- chart/values.yaml
- libs/libcommon/README.md
- libs/libcommon/src/libcommon/config.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/tests/test_queue.py
- services/worker/poetry.lock
- services/worker/pyproject.toml
- services/worker/src/worker/loop.py
- services/worker/src/worker/start_worker_loop.py
- services/worker/tests/test_loop.py
- tools/Python.mk
- tools/docker-compose-base.yml
- tools/docker-compose-dev-base.yml
> feat: 🎸 upgrade transformers and remove exception

- front/admin_ui/app.py
- fix the columns of dataset status
- prefill the step name (in a select element) in refresh tab
> Fix admin app

- front/admin_ui/poetry.lock
- front/admin_ui/pyproject.toml
- front/admin_ui/requirements.txt
> feat: 🎸 upgrade duckdb and gradio

- chart/env/prod.yaml
See https://github.com/huggingface/datasets-server/issues/1301#issuecomment-1590120816
> feat: 🎸 add resources for temporary load

- .github/workflows/doc-pr-build.yml
- .github/workflows/doc-pr-delete-trigger.yml
> ci: 🎡 don't run doc CI if no doc has been changed

- libs/libcommon/src/libcommon/queue.py
- services/worker/src/worker/config.py
- services/worker/src/worker/executor.py
instead of running the zombie killing routine, and the long jobs killing routine on a regular basis, we run them between 50% and 150% of that delay. Fixes #1330
> feat: 🎸 run jobs killing routines with some random delay

- .github/workflows/doc-build.yml
Enables the doc-builder to build Colab notebooks :)
> [docs] Add build notebook workflow

- services/worker/src/worker/job_runners/config/parquet_and_info.py
close https://github.com/huggingface/datasets-server/issues/1374
NamedSplit peut pas être convertit par orjson
> Fix fill_builder_info

- jobs/mongodb_migration/tests/test_deletion_migrations.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/tests/test_queue.py
First part of https://github.com/huggingface/datasets-server/issues/1326
> Delete ttl index from queue.py code

- jobs/mongodb_migration/tests/test_deletion_migrations.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/tests/test_queue.py
This reverts commit 47ea65b2567db4482579cd7000393cf0a15b412e.
> Revert "Delete ttl index from queue.py code (#1378)"

- DEVELOPER_GUIDE.md
- services/reverse-proxy/README.md
Fix closing brackets and GH action link
> Small typos

- jobs/mongodb_migration/tests/test_deletion_migrations.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/tests/test_queue.py
Like https://github.com/huggingface/datasets-server/commit/47ea65b2567db4482579cd7000393cf0a15b412e , firs step to modify TTL index is to remove it from the code, then a deploy is needed.
> Temporaly remove TTL index

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/fixtures/hub.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
- services/worker/tests/job_runners/config/test_split_names_from_streaming.py
- services/worker/tests/job_runners/dataset/test_config_names.py
- services/worker/tests/job_runners/split/test_first_rows_from_streaming.py
- services/worker/tests/job_runners/split/test_opt_in_out_urls_scan_from_streaming.py
> Add tests on create_commits

- libs/libcommon/src/libcommon/queue.py
As it's difficult to test on multiple MongoDB replicas (we should do it at one point), I'll try to:
- merge to main
- deploy this on staging
- refresh the dataset `severo/flores_101` from staging, which also have 3 replicas (beware, it writes to the Hub, as prod!)
- see if all the configs could be processed for the parquet creation, or if we still have an error for "half" of them
> fix: 🐛 try to ensure only one job can get the lock

- services/api/src/api/routes/rows.py
Remove unused code from /rows API endpoint.
> Remove unused code from /rows API endpoint

- services/worker/src/worker/job_runners/split/first_rows_from_parquet.py
- services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
- services/worker/src/worker/utils.py
close https://github.com/huggingface/datasets-server/issues/1416
> keep image and audio untruncated

- services/api/src/api/routes/rows.py
fix
```
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://huggingface.co/datasets/bigcode/the-stack-dedup/resolve/refs%2Fconvert%2Fparquet/bigcode--the-stack-dedup/parquet-train-00000-of-05140.parquet')
```
when doing pagination on the bigcode/the-stack-dedup which is gated
> Add auth in rows

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
needed for https://github.com/huggingface/datasets-server/pull/1296
see https://github.com/huggingface/datasets-server/pull/1296#issuecomment-1604502957
> Ignore duckdb files in parquet and info

- services/worker/src/worker/job_runners/config/parquet_and_info.py
close https://github.com/huggingface/datasets-server/issues/1433
> Unquote path and revision when copying parquet files

- chart/env/prod.yaml
After this PR is merged and deployed, I will rollback to action=skip to disable the k8s job.
> Enable backfill one time

- jobs/cache_maintenance/src/cache_maintenance/metrics.py
- jobs/cache_maintenance/tests/test_collect_metrics.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20221117223000_cache_generic_response.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20230126164900_queue_job_add_priority.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20230309123100_cache_add_progress.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20230309141600_cache_add_job_runner_version.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20230313164200_cache_remove_worker_version.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20230511100600_queue_remove_force.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20230511110700_queue_delete_skipped_jobs.py
- jobs/mongodb_migration/src/mongodb_migration/migrations/_20230516101500_queue_job_add_revision.py
- jobs/mongodb_migration/src/mongodb_migration/renaming_migrations.py
- jobs/mongodb_migration/tests/migrations/test_20230511100700_queue_delete_indexes_with_force.py
- jobs/mongodb_migration/tests/test_deletion_migrations.py
- libs/libcommon/src/libcommon/metrics.py
- libs/libcommon/src/libcommon/prometheus.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/test_orchestrator.py
- libs/libcommon/tests/test_prometheus.py
- libs/libcommon/tests/test_queue.py
- libs/libcommon/tests/test_simple_cache.py
- services/worker/tests/test_executor.py
- services/worker/tests/test_job_manager.py
This commit adds `Document` suffix to classes to indicate inheritance.
cc @severo 
Fixes https://github.com/huggingface/datasets-server/issues/1359
> Rename classes to indicate inheritance

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/job_runners/split/duckdb_index.py
- services/worker/src/worker/utils.py
Should fix HfHubHTTPError when creating commit for duckdb-index
Part of https://github.com/huggingface/datasets-server/issues/1462
> Adding retry to create duckdb index commit

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
got
```
"_prepare_split() missing 1 required positional argument: 'check_duplicate_keys'"
```
when converting C4 (config="en")
This query should return the jobs to re-run:
```
{kind: "config-parquet-and-info", http_status: 500, "details.error": "_prepare_split() missing 1 required positional argument: 'check_duplicate_keys'"}
```
> fix stream_convert_to_parquet for GeneratorBasedBuilder

- chart/env/prod.yaml
Is it the right value @lhoestq ?
> feat: 🎸 increase RAM for /rows service

- e2e/tests/test_11_api.py
- services/api/src/api/config.py
- services/api/tests/routes/test_endpoint.py
- services/worker/README.md
part of https://github.com/huggingface/datasets-server/issues/1086
> Delete `/parquet-and-dataset-info` endpoint

- chart/env/prod.yaml
- libs/libcommon/src/libcommon/queue.py
It looks like db performance has been improved, try to increase resources to flush jobs queue.
> Last index sync and Increase resources

- front/admin_ui/app.py
- services/admin/src/admin/routes/force_refresh.py
Right now I always have to manually set the priority in mongo to "normal"
> Add priority param to force refresh endpoint

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/fixtures/hub.py
close https://github.com/huggingface/datasets-server/issues/1519
> Always verify parquet before copying

- docs/source/parquet.mdx
close https://github.com/huggingface/datasets-server/issues/1400
> add Hub API convenience endpoint in parquet docs

- services/worker/src/worker/job_runners/split/first_rows_from_parquet.py
related to [ivrit-ai/audio-base](https://huggingface.co/datasets/ivrit-ai/audio-base)
it works the same way as in /rows
> Add auth to first_rows_from_parquet

- libs/libcommon/src/libcommon/viewer_utils/asset.py
in cached assets. It will help delete old directories.
> feat: 🎸 update the modification date of root dataset dir

- chart/env/prod.yaml
it will reduce the number of crashes due to missing RAM
> feat: 🎸 reduce overcommitment for rows service

- chart/templates/_dnsConfig.tpl
- chart/templates/cron-jobs/backfill/job.yaml
- chart/templates/cron-jobs/metrics-collector/job.yaml
- chart/templates/jobs/cache-maintenance/job.yaml
- chart/templates/jobs/mongodb-migration/job.yaml
- chart/templates/services/admin/deployment.yaml
- chart/templates/services/api/deployment.yaml
- chart/templates/services/rows/deployment.yaml
- chart/templates/worker/_deployment.yaml
This reverts commit ad754cda0c26bf7d609292853f0c1681380a882e.
> Revert "feat: 🎸 reduce the number of DNS requests (#1581)"

- libs/libcommon/src/libcommon/simple_cache.py
Removal of redundant indices from simple_cache.py.
> remove redundant indices

- chart/env/prod.yaml
- chart/templates/_volumeMountDescriptiveStatistics.tpl
also (unrelated) increase resources
> fix: 🐛 fix statistics volume

- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/test_simple_cache.py
fixes #1604.
It seems like I had to first sort by the fields.
> feat: 🎸 optimize the computation of metrics

- .github/workflows/cd.yml
- .vscode/monorepo.code-workspace
- chart/env/prod.yaml
- chart/env/staging.yaml
- chart/templates/_common/_helpers.tpl
- chart/templates/storage-admin/_container.tpl
- chart/values.yaml
- services/storage-admin/Dockerfile
- services/storage-admin/README.md
> feat: 🎸 build a Docker image for storageAdmin to have rsync

- chart/env/prod.yaml
Currently we have 365K jobs waiting, might help flush the queue
> Increase resources

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/job_runners/config/split_names_from_streaming.py
- services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
- services/worker/src/worker/utils.py
Fix authentication by passing `DownloadConfig` with `token`.
Fix partially #1589.
> Fix authentication with DownloadConfig

- tools/stale.py
The issue tags must be lowercase. P0, P1 and P2 were ignored since they were uppercase. I also refactored to make the code a bit clearer.
> ci: 🎡 fix the stale bot

- tools/stale.py
https://github.com/huggingface/datasets-server/actions/runs/5798651863/job/15716898067
> fix: 🐛 TypeError: can't subtract offset-naive and offset-aware

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/worker/poetry.lock
Update datasets to 2.14.4.
Fix #1652.
Fix partially #1550.
> Update datasets to 2.14.4

- docs/source/openapi.json
the failed configs format is a CustomError
> feat: 🎸 be more specific in OpenAPI type

- services/worker/src/worker/job_runners/config/parquet_and_info.py
for https://huggingface.co/datasets/GalaktischeGurke/full_dataset_1509_lines_invoice_contract_mail_GPT3.5_test/discussions/1#64da13ff3a7ab21ea7c45e63
> Fix parquet filename regex

- docs/source/openapi.json
- e2e/tests/test_52_search.py
- libs/libcommon/src/libcommon/parquet_utils.py
- libs/libcommon/src/libcommon/utils.py
- services/rows/src/rows/routes/rows.py
- services/rows/tests/routes/test_rows.py
- services/search/src/search/routes/search.py
- services/search/tests/routes/test_search.py
also rename num_total_rows in num_rows_total
BREAKING CHANGE: 🧨 field num_total_rows in /rows and /search has been renamed num_rows_total
fixes #1687
> feat: 🎸 add num_rows_per_page in /rows and /search responses

- libs/libcommon/src/libcommon/queue.py
Related to https://github.com/huggingface/datasets-server/pull/1420
fixes (hopefully) https://github.com/huggingface/datasets-server/issues/1467
> Fix start job lock owner

- docs/source/analyze_data.mdx
- docs/source/duckdb.mdx
- docs/source/openapi.json
- docs/source/pandas.mdx
- docs/source/parquet.mdx
- docs/source/polars.mdx
- docs/source/quick_start.mdx
Following https://github.com/huggingface/datasets-server/pull/1685
> Parquet renames docs

- libs/libcommon/src/libcommon/simple_cache.py
This reverts commit ab99a259cbf9f961a5286a583239db8d50677e8e.
> Revert "Add unique compound index to cache metric (#1703)"

- front/admin_ui/requirements.txt
was already updated in pyproject.toml
> Update admin app requirements.txt

- libs/libcommon/src/libcommon/queue.py
related to https://github.com/huggingface/datasets-server/issues/1467#issuecomment-1687104152
> Start job only if waiting

- libs/libapi/src/libapi/utils.py
- services/admin/src/admin/app.py
- services/admin/src/admin/utils.py
- services/api/src/api/app.py
- services/rows/src/rows/app.py
- services/search/src/search/app.py
> fix: 🐛 expose X-Error-Code and X-Revision headers to browser

- services/search/src/search/routes/search.py
Fix for https://github.com/huggingface/datasets-server/issues/1729
> fix: Change score alias name in FST query

- services/worker/src/worker/job_runners/split/descriptive_statistics.py
- services/worker/tests/job_runners/split/test_descriptive_statistics.py
I've found errors in statistics computation in cache database and want to debug them but the error message doesn't contain feature names so it's harder
> Improve error messages content in `split-descriptive-statistics`

- .github/workflows/_e2e_tests.yml
- .github/workflows/_quality-python.yml
- .github/workflows/_unit-tests-python.yml
- .github/workflows/cd.yml
- .github/workflows/chart-pr.yml
- .github/workflows/openapi-spec.yml
- .github/workflows/publish-helm.yml
- .github/workflows/stale.yml
fixes https://github.com/huggingface/datasets-server/issues/1756?
> ci: 🎡 upgrade github action

- chart/env/prod.yaml
they were too much spammed and were OOMing a lot this morning
> More rows worker

- chart/env/prod.yaml
Following https://github.com/huggingface/datasets-server/pull/1768 that failed to deploy because of too many workers
> Reduce other workers

- docs/source/_toctree.yml
- docs/source/clickhouse.md
- docs/source/parquet_process.mdx
A first draft for querying Hub datasets with ClickHouse :)
> [docs] ClickHouse integration

- chart/env/prod.yaml
- chart/env/staging.yaml
- chart/templates/_volumeMounts/_volumeMountCachedAssets.tpl
- chart/templates/_volumes/_volumeCachedAssets.tpl
- chart/templates/services/rows/deployment.yaml
- chart/templates/storage-admin/_container.tpl
- chart/templates/storage-admin/deployment.yaml
- chart/values.yaml
Depends on https://github.com/huggingface/infra/pull/680 being deployed first (internal).
> feat: 🎸 use EFS instead of NFS for cached assets

- chart/templates/reverse-proxy/deployment.yaml
- chart/templates/services/search/deployment.yaml
> fix: 🐛 fix the volumes

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/worker/poetry.lock
fixes https://github.com/huggingface/datasets-server/issues/1781
> feat: 🎸 upgrade datasets from 2.14.4 to 2.14.5

- docs/source/quick_start.mdx
- docs/source/search.mdx
See also https://github.com/huggingface/hub-docs/pull/940
> docs: ✏️ fix the docs: search is not performed on ClassLabel

- .github/workflows/s-sse-api.yml
- chart/templates/services/sse-api/_container.tpl
- services/sse-api/Makefile
comments by @AndreaFrancis  in https://github.com/huggingface/datasets-server/pull/1784
> fix: 🐛 remove unnecessary configs

- services/sse-api/README.md
- services/sse-api/src/sse_api/routes/hub_cache.py
- services/sse-api/src/sse_api/watcher.py
- services/sse-api/tests/test_app.py
Required by https://github.com/huggingface/moon-landing/pull/7456#discussion_r1328913356 and https://github.com/huggingface/moon-landing/pull/7456#discussion_r1328910039 (internal)
> Remove "operation" field from /sse/hub-cache, and add `?all=true`

- front/admin_ui/app.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/src/libcommon/utils.py
- libs/libcommon/tests/test_queue.py
And set the "refresh" jobs to HIGH priority in the admin space.
This way, the manual actions we do at https://huggingface.co/spaces/datasets-maintainers/datasets-server-admin-ui are effective more quickly.
> feat: 🎸 add HIGH priority level

- docs/source/index.mdx
Fix typo in docs index page.
Fix #1814.
> Fix typo in docs index page

- docs/source/openapi.json
- services/worker/src/worker/job_runners/dataset/hub_cache.py
> docs: ✏️ remove doc for deleted /hub-cache endpoint

- chart/env/prod.yaml
they're now using the NFAA tag.
I'll also delete the cache entries with `DatasetInBlockListError `
> unblock cyberharem

- DEVELOPER_GUIDE.md
- chart/templates/_common/_helpers.tpl
- chart/templates/_env/_envDiscussions.tpl
- chart/templates/cron-jobs/post-messages/_container.tpl
- chart/templates/cron-jobs/post-messages/job.yaml
- chart/templates/jobs/cache-maintenance/_container.tpl
- chart/values.yaml
- docs/source/parquet.mdx
- jobs/cache_maintenance/README.md
- jobs/cache_maintenance/poetry.lock
- jobs/cache_maintenance/pyproject.toml
- jobs/cache_maintenance/src/cache_maintenance/config.py
- jobs/cache_maintenance/src/cache_maintenance/delete_indexes.py
- jobs/cache_maintenance/src/cache_maintenance/discussions.py
- jobs/cache_maintenance/src/cache_maintenance/main.py
- jobs/cache_maintenance/tests/conftest.py
- jobs/cache_maintenance/tests/constants.py
- jobs/cache_maintenance/tests/test_discussions.py
- jobs/cache_maintenance/tests/utils.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/src/libcommon/utils.py
- libs/libcommon/tests/test_simple_cache.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/job_runners/split/descriptive_statistics.py
fixes #1270.
Implements https://github.com/huggingface/datasets-server/issues/1270#issuecomment-1726384167
> Send a message in Hub discussion after Parquet conversion

- libs/libcommon/src/libcommon/parquet_utils.py
- services/rows/tests/routes/test_rows.py
Fix https://github.com/huggingface/datasets-server/issues/1752
> Fix /rows for empty split

- jobs/cache_maintenance/src/cache_maintenance/discussions.py
see
https://github.com/huggingface/datasets-server/pull/1824#issuecomment-1733328326
> feat: 🎸 add call to action to get feedback on notifications

- chart/env/prod.yaml
following https://github.com/huggingface/datasets-server/pull/1856
since indexing C4 still OOMs
cc @rtrompier @severo
> Increase worker ram limit

- jobs/cache_maintenance/src/cache_maintenance/main.py
I removed the allowlist, because it requires to modify the code at two places, which is error prone (at least, I had the issue).
> feat: 🎸 allow "post-messages" action

- chart/env/prod.yaml
I'm going to try with requests=limits first to make sure it's not because of overcommitting
First I'll try with 20, then 24 if it doesn't work
> Moar ram for c4 indexing

- docs/source/_toctree.yml
- docs/source/parquet_process.mdx
As pointed out [here](https://huggingface.slack.com/archives/C05NVC4K0Q4/p1694911765308159?thread_ts=1693329498.070839&cid=C05NVC4K0Q4), this PR alphabetizes the section to be a little tidier :)
> [docs] Reorder query section

- chart/env/prod.yaml
C4 indexing OOMed with 20GB, trying with 24GB
following https://github.com/huggingface/datasets-server/pull/1876
> Even more ram for worker

- docs/source/openapi.json
- services/worker/src/worker/dtos.py
(we migrated all the entries in the prod database)
> feat: 🎸 set "truncated" field of /first-rows as mandatory

- tools/stale.py
See https://github.com/huggingface/datasets-server/actions/runs/6381892186/job/17319474629
> feat: 🎸 use a timezone-aware date in stale bot script

- libs/libcommon/README.md
- libs/libcommon/src/libcommon/orchestrator.py
- libs/libcommon/src/libcommon/utils.py
- libs/libcommon/tests/test_utils.py
forbidden in namespace or canonical names. See
https://github.com/huggingface/datasets-server/pull/1899#pullrequestreview-1653142782
> feat: 🎸 allow wildcard only in dataset name of blocked datasets

- e2e/poetry.lock
- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
This should fix 12 dependabot alerts.
Fix #1907.
> Update urllib3 to 1.26.17 to fix vulnerability

- chart/env/prod.yaml
Following https://github.com/huggingface/datasets-server/pull/1903
Close https://github.com/huggingface/datasets-server/issues/1891
> Add heavy workers

- front/admin_ui/poetry.lock
see https://github.com/huggingface/datasets-server/security/dependabot/272
also update libcommon in front/admin
> fix: 🐛 fix vulnerability (pillow)

- chart/env/prod.yaml
This should finally give a decent speed for search (aiming for <15sec on big datasets).
I'll first try it like this and will adapt the other parameters in a second step (ram, num workers)
cc @rtrompier @AndreaFrancis
> More CPU for search

- chart/env/staging.yaml
Try to use karpenter in staging env for a better optimisation of our resources consumptions.
> feat(chart): use spot instance in staging env

- docs/source/openapi.json
> feat: 🎸 update openapi.json spec

- e2e/tests/test_14_statistics.py
Fix e2e `test_statistics_endpoint` after the simultaneous merge of:
- #1870 
- #1418
> Fix e2e test_statistics_endpoint

- jobs/cache_maintenance/src/cache_maintenance/discussions.py
reference: https://huggingface.slack.com/archives/C04L6P8KNQ5/p1696502639784009 (internal)
> feat: 🎸 rename the discussion title to be clearer

- chart/env/prod.yaml
- chart/env/staging.yaml
Tests in staging are finished. Let's prepare the prod deployment (not yet planned)
> fix(chart): remove nodeSelector in staging & prepare prod

- jobs/cache_maintenance/src/cache_maintenance/main.py
> Fix clean datasets cache action name

- jobs/cache_maintenance/src/cache_maintenance/main.py
Certain jobs were not working because of
```
WARNING: 2023-10-09 12:00:35,208 - root - The connection to the cache database could not be established. The action is skipped.
```
even though they don't require a connection to the cache or queue databases.
Affected jobs:
- clean-hf-datasets-cache
- delete-indexes
> Fix cronjob resources

- chart/values.yaml
Unblock alexandrainst/nota dataset.
See discussion on the Hub: https://huggingface.co/datasets/alexandrainst/nota/discussions/1
> Unblock viewer of alexandrainst/nota dataset

- front/admin_ui/poetry.lock
This should fix 1 dependabot alert.
> Update fastapi to 0.103.2 to fix vulnerability

- jobs/cache_maintenance/src/cache_maintenance/discussions.py
see https://github.com/huggingface/moon-landing/issues/7729#issuecomment-1757276965 (internal)
> fix: 🐛 ensure the order of discussion comments

- jobs/cache_maintenance/src/cache_maintenance/clean_hf_datasets_cache.py
- jobs/cache_maintenance/tests/test_clean_hf_datasets_cache.py
it wasn't deleting anything because the pattern was wrong
> Fix clean hf datasets cache pattern

- services/admin/src/admin/app.py
- services/admin/src/admin/routes/cache_reports.py
- services/admin/src/admin/routes/cache_reports_with_content.py
- services/admin/src/admin/routes/dataset_backfill.py
- services/admin/src/admin/routes/dataset_backfill_plan.py
- services/admin/src/admin/routes/dataset_status.py
- services/admin/src/admin/routes/force_refresh.py
- services/admin/src/admin/routes/metrics.py
- services/admin/src/admin/routes/num_dataset_infos_by_builder_name.py
- services/admin/src/admin/routes/obsolete_cache.py
- services/admin/src/admin/routes/pending_jobs.py
- services/admin/src/admin/routes/recreate_dataset.py
- services/admin/src/admin/utils.py
Remove duplicate `admin.utils` and use `libapi.utils` instead.
> Remove duplicate admin utils

- jobs/cache_maintenance/src/cache_maintenance/clean_hf_datasets_cache.py
I noticed that the errors counter was incorrect (was counting subdirectories)
> minor logging improvement in clean hf dset cache

- services/search/src/search/routes/search.py
Fix quality issue in search by removing unused import.
This quality issue was introduced by:
- #1983
> Fix quality in search by removing unused import

- services/worker/src/worker/job_runners/config/split_names_from_streaming.py
- services/worker/src/worker/job_runners/dataset/config_names.py
- services/worker/src/worker/job_runners/split/first_rows_from_streaming.py
- services/worker/src/worker/job_runners/split/opt_in_out_urls_scan_from_streaming.py
- services/worker/tests/job_runners/config/test_split_names_from_streaming.py
Satasets scripts were still loaded in some cases.
following https://github.com/huggingface/datasets-server/pull/2001
> More disable_dataset_scripts_support

- services/worker/tests/job_runners/config/test_parquet_and_info.py
from https://github.com/huggingface/datasets-server/pull/2003
> Fix another test

- docs/source/openapi.json
Add missing filter errors to `openapi.json`.
> Add missing filter errors to openapi.json

- services/search/src/search/routes/filter.py
- services/search/src/search/routes/search.py
Run `duckdb` queries asynchronously in a separate thread.
> Run duckdb queries async in separate thread

- front/admin_ui/app.py
> Fix trending datasets dashboard

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
Update `datasets` to 2.14.6.
Fix #2006.
> Update datasets to 2.14.6

- .github/workflows/doc-build.yml
Add missing token to doc build workflow
> Update doc-build.yml - add missing token

- chart/env/prod.yaml
Internal references:
API: https://huggingface.slack.com/archives/C04L6P8KNQ5/p1698224417526029
workers: https://huggingface.slack.com/archives/C04L6P8KNQ5/p1698323528797149
> increase number of replicas

- libs/libapi/src/libapi/duckdb.py
- services/search/src/search/routes/filter.py
- services/search/src/search/routes/search.py
Download `duckdb` index asynchronously in separate thread, and make `get_index_file_location_and_download_if_missing` asynchronous.
> Download duckdb index async in separate thread

- jobs/cache_maintenance/src/cache_maintenance/discussions.py
- jobs/cache_maintenance/tests/test_discussions.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/test_simple_cache.py
fixes #2023 
note: `__PARQUET_CONVERTER_USER__` will be shown as `parquet-converter` in prod, without the bold formatting (due to the `__` characters).
---
> 2023 reduce number comments

- docs/source/openapi.json
- services/api/src/api/routes/endpoint.py
Refactor the "endpoint" route in the "api" service and use libapi `get_request_parameter`.
> Use get_request_parameter in endpoint

- docs/source/filter.mdx
Explain single quote string SQL syntax in filter docs.
Close #2038.
> Explain single quote string SQL syntax in filter docs

- .vscode/monorepo.code-workspace
Can you test if it works for you?
For me, after some struggle, it works well. A nice improvement is that it will sort the imports.
https://github.com/huggingface/datasets-server/assets/1676121/ba698454-b6df-42d6-b402-676b6d030e8c
> Use ruff in vscode

- libs/libcommon/src/libcommon/exceptions.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
see internal discussion in Slack:
https://huggingface.slack.com/archives/C04L6P8KNQ5/p1692803953736769
> fix: 🐛 hide the error to avoid disclosing a token

- services/worker/src/worker/executor.py
> Stop worker loop executor on SIGTERM

- .gitignore
Add .ruff_cache to .gitignore.
> Add .ruff_cache to .gitignore

- chart/templates/worker/podmonitor.yaml
I think it's the only required change! I'll merge and test.
cc @XciD @rtrompier for reference
> use a pod monitor

- services/sse-api/src/sse_api/routes/hub_cache.py
To investigate https://github.com/huggingface/moon-landing/issues/7674 (internal)
> log on every new value sent in SSE

- services/sse-api/src/sse_api/routes/hub_cache.py
This log generates too many outputs. Reducing the log level to DEBUG
> log as debug

- chart/env/prod.yaml
See https://huggingface.slack.com/archives/C04L6P8KNQ5/p1699868155882279?thread_ts=1699778874.172699&cid=C04L6P8KNQ5 for reference (internal link)
> add RAM to the API pods, to avoid OOM

- libs/libcommon/src/libcommon/simple_cache.py
> add an index recommended by Atlas

- e2e/poetry.lock
- e2e/pyproject.toml
- front/admin_ui/poetry.lock
- front/admin_ui/pyproject.toml
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/admin/pyproject.toml
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
- services/worker/pyproject.toml
Update `datasets` to 2.15.0 and `huggingface-hub` to 0.18.0.
Close #2121 and close #1956
> Update datasets to 2.15.0 and huggingface-hub to 0.18.0

- .github/workflows/_quality-python.yml
- e2e/poetry.lock
- front/admin_ui/poetry.lock
- front/admin_ui/pyproject.toml
- front/admin_ui/requirements.txt
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/admin/pyproject.toml
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
- services/worker/pyproject.toml
- tools/Python.mk
This reverts commit 91d4661b9bab69b3af50e1c7da97c44b312aa52e.
> Revert "upgrade huggingface-hub to temporary branch (#2128)"

- chart/values.yaml
asked here (internal): https://huggingface.slack.com/archives/C0311GZ7R6K/p1700727747983759
> allow dataset script on a new dataset

- libs/libapi/src/libapi/exceptions.py
- services/rows/src/rows/routes/rows.py
> Give insights to the user when we raise TooBigRows

- libs/libcommon/src/libcommon/queue.py
Now that the queue only stores the status "started" and "waiting," it is not necessary to add filter `status__in=[Status.WAITING, Status.STARTED]`.
After this PR, I will monitor database performance to see if any index can be optimized/changed.
> removing useless status filter

- chart/env/prod.yaml
> decrease number of workers

- .vscode/monorepo.code-workspace
the value cannot be boolean in new versions of vscode. See https://stackoverflow.com/a/77637765/7351594
> chore: 🤖 update vscode settings

- chart/values.yaml
This reverts commit 87b93e8f246bc5af61c56808c48ea2fa4834b20d.
> Revert "feat: 🎸 block big dataset (#2204)"

- services/worker/poetry.lock
- services/worker/pyproject.toml
For https://github.com/huggingface/datasets-server/security/dependabot/347
> update transformers in services/workers

- front/admin_ui/poetry.lock
- front/admin_ui/pyproject.toml
Update gradio to 4.11.0.
This should fix 2 dependabot alerts.
> Update gradio dependency to fix vulnerability

- docs/source/openapi.json
- docs/source/quick_start.mdx
- libs/libcommon/src/libcommon/processing_graph.py
- services/worker/src/worker/dtos.py
- services/worker/src/worker/job_runners/config/is_valid.py
- services/worker/src/worker/job_runners/dataset/is_valid.py
- services/worker/src/worker/job_runners/split/is_valid.py
- services/worker/tests/job_runners/config/test_is_valid.py
- services/worker/tests/job_runners/dataset/test_is_valid.py
- services/worker/tests/job_runners/split/test_is_valid.py
> add filter field to is-valid

- front/admin_ui/app.py
> add filter column + ignore errors (fixes #2241)

- libs/libcommon/src/libcommon/operations.py
- libs/libcommon/src/libcommon/orchestrator.py
- libs/libcommon/tests/test_operations.py
- services/admin/src/admin/routes/force_refresh.py
- services/api/src/api/routes/webhook.py
close https://github.com/huggingface/datasets-server/issues/2253
> Dont delete dataset cache if webhook is update on another branch

- services/api/src/api/routes/webhook.py
- services/api/tests/routes/test_webhook.py
- services/api/tests/test_app_real.py
it was updating datasets completely on event scopes like "discussion.comment"
> filter webhook scope

- services/worker/src/worker/job_runners/split/descriptive_statistics.py
- services/worker/src/worker/job_runners/split/duckdb_index.py
Related to https://github.com/huggingface/datasets-server/issues/1443
For `split-duckdb-index` and `split-descriptive-statistics`, I found 11 records in the cache with UnexpectedErrors due to ReadTimeout error when downloading files from hub.
When calling a force refresh, they worked, so instead of adding this error to the error_codes_to_retry list, it is better to retry downloads when job execution is in progress.
> add retry for download hub file

- jobs/cache_maintenance/src/cache_maintenance/clean_directory.py
> catch FileNotFoundError, raised when a path has disappeared during the loop

- services/api/src/api/routes/croissant.py
- services/api/tests/routes/test_croissant.py
> limit number of columns in croissant

- front/admin_ui/pyproject.toml
- front/admin_ui/requirements.txt
already reverted in the space https://huggingface.co/spaces/datasets-maintainers/datasets-server-admin-ui
see https://github.com/huggingface/datasets-server/issues/2228
> downgrade gradio to avoid error

- chart/env/prod.yaml
- chart/env/staging.yaml
- chart/templates/_env/_envCloudfront.tpl
- chart/templates/services/rows/_container.tpl
- chart/templates/services/search/_container.tpl
- chart/values.yaml
Pass the CLOUDFRONT_* environment variables to rows and search services, for the staging environment.
> pass cloudfront key id and private key to staging

- services/api/src/api/routes/croissant.py
- services/api/tests/routes/test_croissant.py
Fixes: https://github.com/huggingface/datasets-server/issues/2332
> Support a `full` parameter to produce either an abridged JSON-LD or a full-length JSON-LD.

- services/worker/src/worker/job_runners/split/duckdb_index.py
- services/worker/tests/job_runners/split/test_duckdb_index.py
fix for https://github.com/huggingface/datasets-server/issues/2344
> fix add pattern for partial splits when removing old duckb index files

- chart/env/prod.yaml
> no overcommitment for RAM in services/api

- front/admin_ui/app.py
> Difficulty in admin UI

- front/admin_ui/README.md
- front/admin_ui/app.py
- front/admin_ui/poetry.lock
- front/admin_ui/pyproject.toml
- front/admin_ui/requirements.txt
> Upgrade gradio

- jobs/cache_maintenance/src/cache_maintenance/backfill.py
- libs/libcommon/src/libcommon/operations.py
- libs/libcommon/src/libcommon/orchestrator.py
- libs/libcommon/tests/test_operations.py
- libs/libcommon/tests/test_queue.py
> Fix backfill when dataset only has one cache entry

- front/admin_ui/app.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/test_simple_cache.py
- services/admin/src/admin/app.py
- services/admin/src/admin/routes/force_refresh.py
- Adding difficulty param in admin UI so we can run the job in a light, medium, or heavy worker (It will change on job_type change event).
- Adding failed_runs in cache UI table
> UI: Add difficulty and failed_runs to admin_ui

- services/api/src/api/routes/webhook.py
side-effect : any configuration change recreates everything in the datasets-server.
Possibly, the Hub will implement "scope": "repo.config.visibility", but for now, it's the way to react to visibility changes.
fixes #2379
> handle visibility (public/private) changes

- libs/libcommon/src/libcommon/constants.py
fixes #2049 
(we retry ConnectionError, not ClientConnection, btw)
> retry on ConnectionError

- chart/values.yaml
> unblock two datasets

- docs/source/parquet.mdx
> add information about Parquet

- libs/libcommon/src/libcommon/orchestrator.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/tests/test_operations.py
- libs/libcommon/tests/test_orchestrator.py
- libs/libcommon/tests/test_queue.py
> delete only waiting jobs

- jobs/cache_maintenance/src/cache_maintenance/discussions.py
fixes #2419
It could be too verbose now.
Also: we might add a section or a sentence to handle the case where the dataset was already in Parquet (until we properly detect if the dataset was already in Parquet format: https://github.com/huggingface/datasets-server/issues/2301)
> give more details in the discussions opened by parquet-converter

- jobs/cache_maintenance/src/cache_maintenance/backfill.py
- libs/libcommon/src/libcommon/operations.py
- libs/libcommon/src/libcommon/orchestrator.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/src/libcommon/storage_client.py
> add statistics to the backfill cron job logs

- docs/source/splits.md
https://moon-ci-docs.huggingface.co/docs/datasets-server/pr_2431/en/splits
https://github.com/huggingface/datasets-server/assets/1676121/414e04d0-95b6-4677-8c19-778daab05cff
> show image in /splits page + change link

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
Update `datasets` to 2.17.0.
Fix #2428.
> Update datasets to 2.17.0

- docs/source/_toctree.yml
- docs/source/croissant.md
- docs/source/croissant_metadata.md
- docs/source/mlcroissant.md
- docs/source/parquet_process.md
- docs/source/quick_start.md
- services/api/README.md
also add mention of support for the private datasets
> Add croissant page

- jobs/mongodb_migration/src/mongodb_migration/collector.py
> add missing migration

- chart/env/prod.yaml
This reverts commit f495e2c437689519f6bed507fb43b5a6f2d9b39c.
> Revert "increase resources to 10/80/10 (#2468)"

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
Update `datasets` to 2.17.1.
Fix #2465.
> Update datasets to 2.17.1

- jobs/cache_maintenance/src/cache_maintenance/cache_metrics.py
- jobs/cache_maintenance/src/cache_maintenance/queue_metrics.py
- jobs/cache_maintenance/tests/test_collect_cache_metrics.py
- jobs/cache_maintenance/tests/test_collect_queue_metrics.py
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/test_queue.py
- libs/libcommon/tests/test_simple_cache.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
> Fix metrics

- chart/env/prod.yaml
See https://www.notion.so/huggingface2/Infrastructure-b4fd07f015e04a84a41ec6472c8a0ff5 and https://huggingface.slack.com/archives/C04L6P8KNQ5/p1702553107305559 (internal links)
> Tweak the production resources

- chart/values.yaml
[espnet/yodas](https://huggingface.co/datasets/espnet/yodas)
> Support yodas

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
This should make the viewer faster to get for datasets with images/audio in parquet file.
I also updated hfh - close https://github.com/huggingface/datasets-server/issues/2317
> Update datasets and hfh

- libs/libcommon/src/libcommon/viewer_utils/features.py
> Support binary columns for images

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/utils.py
revert https://github.com/huggingface/datasets-server/pull/2544 since it made it too slow to process https://huggingface.co/datasets/Major-TOM/Core-S2L2A
> Revert max_workers for pq validation

- libs/libcommon/src/libcommon/viewer_utils/features.py
fix https://github.com/huggingface/datasets-server/pull/2545
> hot fix for images

- libs/libcommon/src/libcommon/parquet_utils.py
to fix https://huggingface.co/datasets/Major-TOM/Core-S2L2A RowsPostProcessingError
> Don't truncate image bytes

- docs/source/openapi.json
Some values of numerical results might be null now (rare cases when all values in column are null)
See https://github.com/huggingface/datasets-server/pull/2453
> Update openapi specs according to changes in stats #2453

- chart/env/prod.yaml
temporary fix for https://github.com/huggingface/datasets-server/issues/889#issuecomment-1985943755
> increase threshold for heavy workers to 50

- chart/env/prod.yaml
I increased the minimum number of workers to what we had nominally before autoscaling.
> tweak autoscale parameters (again)

- .github/workflows/openapi-spec.yml
- docs/source/openapi.json
also: fix action name
also: update openapi.json detail just to trigger the action
> check openapi spec against spectral

- docs/source/openapi.json
- docs/source/quick_start.md
- front/admin_ui/app.py
- libs/libcommon/src/libcommon/constants.py
- libs/libcommon/src/libcommon/processing_graph.py
- services/worker/src/worker/dtos.py
- services/worker/src/worker/job_runners/config/is_valid.py
- services/worker/src/worker/job_runners/dataset/is_valid.py
- services/worker/src/worker/job_runners/split/is_valid.py
- services/worker/tests/job_runners/config/test_is_valid.py
- services/worker/tests/job_runners/dataset/test_is_valid.py
- services/worker/tests/job_runners/split/test_is_valid.py
> Add "statistics" field to is-valid workers

- docs/source/openapi.json
- e2e/tests/test_11_api.py
- libs/libapi/src/libapi/authentication.py
- libs/libapi/tests/test_authentication.py
- services/admin/src/admin/authentication.py
Fixes #1011
and then
Fixes #2572
Fixes #2052
> remove support for cookies

- libs/libcommon/src/libcommon/processing_graph.py
following https://github.com/huggingface/datasets-server/pull/2454
> increment job runner version

- .vscode/monorepo.code-workspace
- docs/source/openapi.json
- fix assets/cached-assets urls in openapi spec
- fix vscode extension
> Fix openapi deatils

- docs/source/openapi.json
all the cache entries have been updated
> set statistics as required in response to /is-valid

- libs/libcommon/src/libcommon/viewer_utils/asset.py
The EXIF orientation tag is currently ignored when displaying images (see https://huggingface.co/datasets/mariosasko/exif_image).
This PR should fix this.
> Support exif images

- libs/libcommon/src/libcommon/processing_graph.py
- services/worker/src/worker/job_runners/dataset/compatible_libraries.py
- services/worker/tests/job_runners/dataset/test_compatible_libraries.py
Example:
```python
from datasets import load_dataset
ds = load_dataset("imagenet-1k")
```
The comment is only show for datasets that require a token to be accessed
Close https://github.com/huggingface/datasets-server/issues/2619
> Add login comment in code snippets

- services/api/src/api/app.py
after we have these two PRs in prod:
- https://github.com/huggingface/datasets-server/pull/2643
- https://github.com/huggingface/moon-landing/pull/9426
> Remove croissant endpoint

- chart/env/prod.yaml
- jobs/cache_maintenance/src/cache_maintenance/backfill.py
- jobs/cache_maintenance/tests/test_backfill.py
- libs/libcommon/src/libcommon/operations.py
> Parallelize the backfill cron job

- services/search/src/search/routes/search.py
Related to https://github.com/huggingface/dataset-viewer/pull/2673
> Fix typo for local big dataset and remove others

- libs/libcommon/src/libcommon/config.py
- libs/libcommon/src/libcommon/storage_client.py
Make s3fs dependency explicit in libcommon.
Related to:
- #2671
> Make s3fs dependency explicit

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
Update numba from 0.56.4 to 0.59.1.
Fix #2698.
> Update numba from 0.56.4 to 0.59.1

- docs/poetry.lock
- e2e/poetry.lock
- e2e/pyproject.toml
- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
Update huggingface-hub to 0.22.2.
Fix #2634.
> Update huggingface-hub to 0.22.2

- libs/libapi/src/libapi/duckdb.py
- libs/libapi/tests/test_duckdb.py
> create the directory if it does not exist when checking disk space

- services/worker/src/worker/executor.py
Needed to debug HuggingFaceFW/fineweb "default" config that crashes in 15min without meaningful logs
cc @polinaeterna
> More logs for crashes

- services/worker/src/worker/executor.py
I also removed the custom exception handler that can cause a segfault and has never been useful (no logs from this in the past days and I've never seen it)
> Re enable signal handling

- services/worker/src/worker/job_runners/config/parquet_and_info.py
I think it causes the fineweb job to hang, and then kube thinks the pod is doing nothing and can kill it
cc @polinaeterna 
also cc @Wauplin just FYI
> Add timeout to hffs requests

- services/worker/src/worker/job_runners/split/duckdb_index.py
- services/worker/tests/fixtures/datasets.py
- services/worker/tests/fixtures/hub.py
- services/worker/tests/job_runners/split/test_duckdb_index.py
Fix for https://github.com/huggingface/dataset-viewer/issues/2613
> Adding large_string to duckdb-index worker and tests

- services/worker/tests/fixtures/hub.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
fixes #2759
I'm not sure why we need to add 5 bytes to the size though...
> Fix size in tests

- chart/values.yaml
They are very big (a lot of configs) and are updated all the time.
> block mcding-org/* datasets

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
Update datasets to 2.19.1.
Fix #2777.
> Update datasets to 2.19.1

- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- services/rows/poetry.lock
- services/worker/poetry.lock
Update werkzeug to 3.0.3 to fix vulnerability.
> Update werkzeug to 3.0.3 to fix vulnerability

- front/admin_ui/poetry.lock
- libs/libcommon/poetry.lock
- services/rows/poetry.lock
- services/worker/poetry.lock
Update jinja2 to 3.1.4 to fix vulnerability.
> Update jinja2 to 3.1.4 to fix vulnerability

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/job_runners/split/first_rows.py
- services/worker/src/worker/utils.py
- services/worker/tests/job_runners/split/test_first_rows.py
> test info.features once they are filled

- services/worker/src/worker/job_runners/config/parquet_and_info.py
Fix for https://github.com/huggingface/dataset-viewer/issues/2709
> fix: Validate and get compression ratio if available row groups

- services/worker/src/worker/job_runners/split/descriptive_statistics.py
- services/worker/tests/fixtures/descriptive_statistics_dataset.py
- services/worker/tests/job_runners/split/test_descriptive_statistics.py
should fix cases like this https://huggingface.co/datasets/lhoestq/test-cmcv
> Fix image stats when image column type is bytes, not struct

- libs/libcommon/src/libcommon/exceptions.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
Will fix https://github.com/huggingface/dataset-viewer/issues/2601 and https://github.com/huggingface/dataset-viewer/issues/2723
Related to https://github.com/huggingface/dataset-viewer/issues/1443
Current number of records with this issue (UnexpectedError):
```
{ _id: { error: 'DatasetGenerationError' }, count: 5504 }
{ _id: { error: 'DatasetGenerationCastError' }, count: 1697 }
```
> Catch DatasetGenerationCastError and show details

- tools/Python.mk
Add lock-no-update command to Makefile.
I find this command useful when there are issues in the local Python environment. See: https://github.com/huggingface/dataset-viewer/pull/2783#issuecomment-2102015730
> Add lock-no-update command to Makefile

- libs/libcommon/src/libcommon/log.py
> limit logs to 5000 characters

- chart/values.yaml
Part of https://github.com/huggingface/dataset-viewer/issues/2804 (the dataset had already been moved to data-only by  the maintainers).
https://huggingface.co/datasets/pufanyi/MIMICIT/tree/main
> pufanyi/MIMICIT is now data-only

- chart/nginx-templates/default.conf.template
- chart/templates/services/admin/servicemonitor.yaml
- e2e/tests/test_31_admin_metrics.py
- services/admin/README.md
- services/admin/src/admin/app.py
- services/admin/tests/test_app.py
- services/admin/tests/test_app_real.py
> add prefix /admin in admin service

- chart/templates/services/admin/_container.tpl
- e2e/tests/test_31_admin_metrics.py
> Fix admin again

- e2e/tests/test_30_admin_healthcheck.py
- e2e/tests/test_31_admin_metrics.py
> fix e2e test

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/worker/poetry.lock
for a new dataset being released that has a field "url.txt" that is not read correctly as text; and another field "npz" that had an error
thsoe have been fixed in https://github.com/huggingface/datasets/pull/6904 and included in branch `datasets-2.19.1-hotfix`
> Fix webdatset multipart ext and npz

- docs/source/search.md
Disclose the search algorithm and stemmer
> doc: BM25 and Porter stemmer reference

- libs/libcommon/src/libcommon/viewer_utils/asset.py
- libs/libcommon/tests/viewer_utils/test_assets.py
added .opus as supported audio extension
> added .opus as supported audio extension

- libs/libcommon/src/libcommon/viewer_utils/asset.py
- libs/libcommon/src/libcommon/viewer_utils/features.py
This PR fixes the no-conversion of Opus audio file:
- #2818
because the following PR does not avoid the conversion of Opus audio files to WAV:
- #2832
CC: @Airop
> Fix the no-conversion of Opus audio files

- chart/env/prod.yaml
We currently use 5 out of 8 nodes. I'll try to increase the max number of nodes at the same time
> increase the number of API pods from 12 to 20

- chart/templates/services/sse-api/_container.tpl
- chart/templates/services/sse-api/servicemonitor.yaml
- services/reverse-proxy/nginx-templates/default.conf.template
- services/sse-api/README.md
- services/sse-api/src/sse_api/app.py
- services/sse-api/tests/test_app.py
same issue as for /admin, which was fixed in three PR: https://github.com/huggingface/dataset-viewer/pull/2820, https://github.com/huggingface/dataset-viewer/pull/2821, https://github.com/huggingface/dataset-viewer/pull/2825
> fix sse prefix, after switching from nginx proxy to ALB

- chart/env/prod.yaml
See: https://github.com/huggingface/infra/pull/1022
> fix(chart): add kube tolerations

- front/admin_ui/requirements.txt
had to pin a few s3 related deps (from poetry.lock) or pip couldn't resolve them
> fix admin ui deps

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/webhook/poetry.lock
- services/worker/poetry.lock
...by pinning a more recent version of `datasets@datasets-2.19.1-hotfix`
The webdataset fixes are needed for a dataset release, see [internal](https://huggingface.slack.com/archives/C06T0REVAH1/p1716998706658099?thread_ts=1714048738.307959&cid=C06T0REVAH1)
<s>I also included your fix for the columns order and Json improvement @albertvillanova </s>
> More webdataset fixes

- services/worker/poetry.lock
- services/worker/pyproject.toml
needed for webdataset with .pth files in them
> Re-add torch dependency

- services/worker/src/worker/job_runners/config/parquet_metadata.py
...to see if it helps with [FineWeb](https://huggingface.co/datasets/HuggingFaceFW/fineweb) `config-parquet-metadata` issue. 
Currently the error says just `Server disconnected` which seems to be a `aiohttp.ServerDisconnectedError` error.
If that works, a more fundamental solution would be to completely switch to `HfFyleSystem` instead of `HTTPFileSystem` and remove retries.
> Add retry mechanism to get_parquet_file in parquet metadata step

- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- libs/libcommon/src/libcommon/queue.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/test_backfill.py
- libs/libcommon/tests/test_orchestrator.py
- libs/libcommon/tests/test_state.py
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/webhook/poetry.lock
- services/worker/poetry.lock
Fix for https://github.com/huggingface/dataset-viewer/issues/2868
> Use pymongoarrow to get dataset results as dataframe

- services/admin/dev.Dockerfile
- services/api/dev.Dockerfile
- services/rows/dev.Dockerfile
- services/search/dev.Dockerfile
- services/sse-api/dev.Dockerfile
- services/webhook/dev.Dockerfile
- services/worker/dev.Dockerfile
otherwise I can't build the images on mac m2
I didn't touch the prod images
> add missing deps to dev images

- libs/libapi/src/libapi/authentication.py
- libs/libcommon/src/libcommon/orchestrator.py
- libs/libcommon/src/libcommon/prometheus.py
- libs/libcommon/src/libcommon/state.py
- libs/libcommon/tests/test_prometheus.py
- services/api/src/api/routes/endpoint.py
- services/api/tests/test_app.py
- services/rows/tests/test_app.py
- services/search/tests/test_app.py
- services/sse-api/tests/test_app.py
- services/webhook/tests/test_app.py
- services/worker/src/worker/loop.py
Remove Prometheus context label.
Fix #2895.
> Remove Prometheus context label

- services/worker/src/worker/dtos.py
- services/worker/src/worker/job_runners/dataset/hub_cache.py
- services/worker/tests/job_runners/dataset/test_hub_cache.py
> 2754 partial instead of error

- services/worker/src/worker/utils.py
- services/worker/tests/job_runners/dataset/test_filetypes.py
- services/worker/tests/test_utils.py
> fix: extensions are always lowercase

- services/worker/src/worker/dtos.py
- services/worker/src/worker/job_runners/dataset/modalities.py
- services/worker/tests/job_runners/dataset/test_modalities.py
> Additional modalities detection

- libs/libcommon/src/libcommon/processing_graph.py
- libs/libcommon/tests/test_operations.py
- libs/libcommon/tests/test_processing_graph.py
- services/worker/src/worker/dtos.py
- services/worker/src/worker/job_runners/dataset/modalities.py
- services/worker/tests/job_runners/dataset/test_modalities.py
> Detect dataset modalities using dataset-filetypes

- front/admin_ui/app.py
> order the steps alphabetically

- libs/libcommon/src/libcommon/processing_graph.py
- services/worker/src/worker/job_runners/config/is_valid.py
- services/worker/src/worker/job_runners/dataset/is_valid.py
- services/worker/tests/job_runners/config/test_is_valid.py
- services/worker/tests/job_runners/dataset/test_is_valid.py
Should remove the remaining PreviousStepFormatError: https://github.com/huggingface/dataset-viewer/issues/2433#issuecomment-2179014134
> only raise error in config-is-valid if format is bad

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
> Enable estimate info (size) on all datasets

- docs/source/cudf.md
- docs/source/parquet_process.md
Firstly, thanks a lot for this project and hosting so many datasets!
This PR add an example for how to read in data using cudf. This can be useful if you have access to a GPU and want to use the GPU to accelerate any ETL.
The code works and can be testing in this google colab notebook: https://colab.research.google.com/drive/1KrhARlJMPoaIpHqE9X2fMQFcYTLffrem?usp=sharing
> add cudf example

- chart/templates/services/admin/deployment.yaml
- chart/templates/services/api/deployment.yaml
- chart/templates/services/rows/deployment.yaml
- chart/templates/services/search/deployment.yaml
- chart/templates/services/sse-api/deployment.yaml
- chart/templates/services/webhook/deployment.yaml
- chart/templates/worker/_deployment.yaml
Will automatically redeploy applications when secrets are changed in Infisical (max 1 min after the change).
> feat(chart): auto deploy when secrets change

- chart/env/prod.yaml
- chart/env/staging.yaml
- chart/templates/worker/_container.tpl
- chart/values.yaml
- libs/libcommon/src/libcommon/queue/jobs.py
- libs/libcommon/tests/queue/test_jobs.py
- libs/libcommon/tests/test_backfill_on_real_graph.py
- services/worker/README.md
- services/worker/src/worker/config.py
- services/worker/src/worker/loop.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
- services/worker/tests/test_loop.py
> Remove blocked only job types

- .github/workflows/cd.yml
This reverts commit 858ec8c147959cd426c2c662a2ff067dcc7149c3.
> Revert "the repository will be moved (#2977)"

- docs/source/parquet.md
asked at https://huggingface.slack.com/archives/C0709MK0PUN/p1720433431019569?thread_ts=1720210655.175099&cid=C0709MK0PUN
> Docs: mention partial parquet conversion for big row groups

- libs/libcommon/src/libcommon/croissant_utils.py
- libs/libcommon/tests/test_croissant_utils.py
- services/worker/src/worker/job_runners/dataset/croissant_crumbs.py
WIP: still checking that it works as intended on mlcroissant side.
> Support `Sequence()` features in Croissant crumbs.

- docs/source/_toctree.yml
- docs/source/configs_and_splits.md
- docs/source/croissant.md
- docs/source/filter.md
- docs/source/first_rows.md
- docs/source/info.md
- docs/source/openapi.json
- docs/source/parquet.md
- docs/source/quick_start.md
- docs/source/rows.md
- docs/source/search.md
- docs/source/server.md
- docs/source/size.md
- docs/source/splits.md
- docs/source/statistics.md
see also https://github.com/huggingface/hub-docs/pull/1347.
> replace configuration with subset where appropriate

- docs/source/statistics.md
specify that the "string_text " length is calculated by its character number.
> Update statistics.md: Add the length calculation statement.

- libs/libcommon/src/libcommon/processing_graph.py
recompute croissant files after https://github.com/huggingface/dataset-viewer/pull/2943
cc @marcenacp
> bump croissant job version

- services/worker/src/worker/job_runners/split/presidio_scan.py
asked at https://huggingface.slack.com/archives/C01GSG1QFPF/p1720525385703189?thread_ts=1720079065.204769&cid=C01GSG1QFPF
> run presidio on UpVoteWeb

- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/fixtures/hub.py
Not sure what to with the existing entries (we don't want to recompute all the entries).
Alternative: remove the field?
> otherwise we have dataset_name: 'parquet'

- docs/source/index.md
> Add links to the Hub docs

- docs/source/valid.md
found using https://github.com/raviqqe/muffet while checking for broken links
```
muffet --rate-limit 5 -i "https://huggingface.co/docs/dataset-viewer/*" https://huggingface.co/docs/dataset-viewer
```
> fix anchor

- docs/source/_toctree.yml
- docs/source/parquet_process.md
- docs/source/pyspark.md
Adding primary doc for reading parquet files with PySpark
> doc: Read parquet files with PySpark 

- chart/env/staging.yaml
https://datasets-server.us.dev.moon.huggingface.tech/sse/healthcheck or https://datasets-server.us.dev.moon.huggingface.tech/sse/hub-cache are currently returning 404 not found
> add ingress for /sse

- e2e/tests/test_31_admin_metrics.py
- services/admin/src/admin/app.py
- services/admin/tests/test_app.py
- services/sse-api/src/sse_api/app.py
> [nit] admin and sse-api get requests from ALB on /healthcheck

- e2e/tests/utils.py
- jobs/cache_maintenance/tests/utils.py
- services/admin/tests/fixtures/hub.py
- services/worker/tests/fixtures/hub.py
see
https://github.com/huggingface/huggingface_hub/pull/2474#issuecomment-2302132315
> import from the correct file

- docs/poetry.lock
- e2e/poetry.lock
- e2e/pyproject.toml
- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/webhook/poetry.lock
- services/worker/poetry.lock
Update huggingface-hub to 0.24.6.
Note that the fix:
- #2781
- https://github.com/huggingface/huggingface_hub/pull/2271
was released in : https://github.com/huggingface/huggingface_hub/releases/tag/v0.23.1
Related to:
- #3037
> Update huggingface-hub to 0.24.6

- libs/libcommon/src/libcommon/queue/jobs.py
- libs/libcommon/src/libcommon/queue/lock.py
> fix the lock release when finishing a job

- libs/libcommon/src/libcommon/queue/dataset_blockages.py
- libs/libcommon/src/libcommon/queue/jobs.py
- libs/libcommon/src/libcommon/queue/lock.py
- libs/libcommon/src/libcommon/queue/metrics.py
- libs/libcommon/src/libcommon/queue/past_jobs.py
- libs/libcommon/src/libcommon/simple_cache.py
- libs/libcommon/tests/queue/test_past_jobs.py
I think it's enough to close #862
> More explicit test and comments about offset-naive datetimes read from mongo

- libs/libcommon/src/libcommon/constants.py
- libs/libcommon/src/libcommon/exceptions.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/job_runners/dataset/config_names.py
- services/worker/tests/job_runners/dataset/test_config_names.py
It will help show them better in moonlanding
see #3010
> Raise specific errors instead of ConfigNamesError when appropriate

- chart/values.yaml
> mnist and zalando are now data-only

- services/worker/tests/job_runners/config/test_duckdb_index_size.py
- services/worker/tests/job_runners/config/test_info.py
- services/worker/tests/job_runners/config/test_is_valid.py
- services/worker/tests/job_runners/config/test_opt_in_out_urls_count.py
- services/worker/tests/job_runners/config/test_parquet.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
- services/worker/tests/job_runners/config/test_parquet_metadata.py
- services/worker/tests/job_runners/config/test_size.py
- services/worker/tests/job_runners/config/test_split_names.py
- services/worker/tests/job_runners/dataset/test_compatible_libraries.py
- services/worker/tests/job_runners/dataset/test_config_names.py
- services/worker/tests/job_runners/dataset/test_duckdb_index_size.py
- services/worker/tests/job_runners/dataset/test_filetypes.py
- services/worker/tests/job_runners/dataset/test_hub_cache.py
- services/worker/tests/job_runners/dataset/test_info.py
- services/worker/tests/job_runners/dataset/test_is_valid.py
- services/worker/tests/job_runners/dataset/test_modalities.py
- services/worker/tests/job_runners/dataset/test_opt_in_out_urls_count.py
- services/worker/tests/job_runners/dataset/test_parquet.py
- services/worker/tests/job_runners/dataset/test_presidio_entities_count.py
- services/worker/tests/job_runners/dataset/test_size.py
- services/worker/tests/job_runners/dataset/test_split_names.py
- services/worker/tests/job_runners/split/test_descriptive_statistics.py
- services/worker/tests/job_runners/split/test_duckdb_index.py
- services/worker/tests/job_runners/split/test_first_rows.py
- services/worker/tests/job_runners/split/test_image_url_columns.py
- services/worker/tests/job_runners/split/test_is_valid.py
- services/worker/tests/job_runners/split/test_opt_in_out_urls_count.py
- services/worker/tests/job_runners/split/test_opt_in_out_urls_scan_from_streaming.py
- services/worker/tests/job_runners/split/test_presidio_scan.py
see https://github.com/huggingface/dataset-viewer/pull/3046#issuecomment-2307793018
> call pre_compute() and post_compute() in tests

- services/worker/src/worker/job_runners/config/split_names.py
- services/worker/src/worker/job_runners/split/first_rows.py
> no need to keep the trace of the first exception

- libs/libcommon/src/libcommon/constants.py
we don't have these error codes in the database anymore
> remove obsolete retryable error codes

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/webhook/poetry.lock
- services/worker/poetry.lock
Fix for https://github.com/huggingface/dataset-viewer/security/dependabot/610
> Update cryptography >=43.0.1

- services/admin/README.md
- services/admin/src/admin/authentication.py
- services/admin/tests/test_authentication.py
- services/admin/tests/utils.py
require fine grained token with repo.write permission to access the admin endpoints
> fine grained token for admin

- services/worker/tests/job_runners/split/test_descriptive_statistics.py
Delete `test_polars_struct_thread_panic_error`.
Note that the previous CI-Hub dataset (with the specific Parquet file) has been deleted.
Fix #3069.
> Fix CI by deleting test_polars_struct_thread_panic_error

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/webhook/poetry.lock
- services/worker/poetry.lock
- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/tests/job_runners/config/test_split_names.py
- services/worker/tests/job_runners/dataset/test_config_names.py
Update datasets to 3.0.1.
Fix #3068.
> Update datasets to 3.0.1

- chart/values.yaml
fix the admin page space
following https://github.com/huggingface/dataset-viewer/pull/3067
cc @AndreaFrancis for viz
> Set datasets-maintainers org for admin auth

- services/rows/src/rows/routes/rows.py
- services/worker/src/worker/job_runners/split/first_rows.py
fix viewer for trending dataset https://huggingface.co/datasets/Marqo/marqo-GS-10M
(it has UINT64 features that mongo don't support but setting the feature to string in YAML fixes the issue)
> Cast features in rows

- libs/libcommon/src/libcommon/viewer_utils/features.py
there was still an import that should not be done now that decord is not required
> Fix decord import

- libs/libapi/src/libapi/rows_utils.py
- libs/libcommon/src/libcommon/url_preparator.py
because they are still returned as hf:// urls
> Render first rows video urls

- services/webhook/src/webhook/routes/webhook.py
- services/webhook/tests/routes/test_webhook.py
- services/webhook/tests/test_app_real.py
related to https://github.com/huggingface/dataset-viewer/issues/2379
> Don't recompute on private->public for pro/enterprise

- services/webhook/src/webhook/routes/webhook.py
fix after https://github.com/huggingface/dataset-viewer/pull/3111
> fix webhook on parquet conversion

- libs/libcommon/src/libcommon/parquet_utils.py
following https://github.com/huggingface/dataset-viewer/pull/3124
> fix rows schema mismatch

- services/worker/src/worker/job_runners/config/parquet_and_info.py
hot fix for https://github.com/huggingface/datasets/pull/7374
> ignore h5 files

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- libs/libcommon/src/libcommon/croissant_utils.py
- libs/libcommon/src/libcommon/url_preparator.py
- libs/libcommon/src/libcommon/viewer_utils/features.py
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/webhook/poetry.lock
- services/worker/poetry.lock
- services/worker/src/worker/job_runners/dataset/modalities.py
- services/worker/src/worker/job_runners/split/descriptive_statistics.py
- services/worker/src/worker/job_runners/split/duckdb_index.py
to avoid RowsPostProcessingError from `TypeError: could not determine the type of the data cell` errors in open R1 project
> Support large list

- docs/source/openapi.json
> Update openapi large_list

- libs/libapi/src/libapi/duckdb.py
- services/search/src/search/duckdb_connection.py
- services/search/src/search/routes/filter.py
- services/search/src/search/routes/search.py
> Fix concurrent duckdb accesses

- libs/libcommon/src/libcommon/croissant_utils.py
We recently introduced support for cr:UInt* data types https://github.com/mlcommons/croissant/pull/836
> Use new cr:UInt* data types.

- libs/libapi/src/libapi/duckdb.py
- libs/libcommon/src/libcommon/duckdb_utils.py
> Return response not ready if dataset indexing is too long

- libs/libapi/src/libapi/duckdb.py
- libs/libcommon/src/libcommon/duckdb_utils.py
- services/search/src/search/routes/filter.py
- services/search/src/search/routes/search.py
follows #3166 
PS: the 40% is by taking the users/orgs of the top 10k trending datasets
> Enable new search/filter (without `refs/convert/duckdb`) for 40% of users/orgs

- libs/libcommon/src/libcommon/duckdb_utils.py
> Enable new filter/search on all datasets

- services/worker/src/worker/config.py
- services/worker/src/worker/dtos.py
- services/worker/src/worker/job_runner_factory.py
- services/worker/src/worker/job_runners/config/parquet_and_info.py
- services/worker/src/worker/main.py
- services/worker/src/worker/start_worker_loop.py
- services/worker/tests/conftest.py
- services/worker/tests/job_runners/config/test_parquet_and_info.py
- services/worker/tests/job_runners/split/test_is_valid.py
- services/worker/tests/test_executor.py
- services/worker/tests/test_job_runner_factory.py
+ remove other duckdb related code in workers
this PR fixes failing worker initialization after #3188
> Dont init duckdb cache in workers

- services/worker/src/worker/job_runners/_job_runner_with_datasets_cache.py
follows https://github.com/huggingface/dataset-viewer/pull/3192
> Set xet cache env var

- services/worker/src/worker/job_runners/config/parquet_and_info.py
fix for https://hf.co/datasets/EssentialAI/essential-web-v1.0
> fix max files per repo

- front/admin_ui/poetry.lock
- jobs/cache_maintenance/poetry.lock
- jobs/mongodb_migration/poetry.lock
- libs/libapi/poetry.lock
- libs/libcommon/poetry.lock
- libs/libcommon/pyproject.toml
- services/admin/poetry.lock
- services/api/poetry.lock
- services/rows/poetry.lock
- services/search/poetry.lock
- services/sse-api/poetry.lock
- services/webhook/poetry.lock
- services/worker/poetry.lock
for https://huggingface.co/datasets/allenai/olmo-mix-1124
> bump datasets for json

- libs/libcommon/src/libcommon/croissant_utils.py
Example of a dataset info defining Audio: https://datasets-server.huggingface.co/info?dataset=MLCommons/peoples_speech
Can also not define sampling_rate: https://datasets-server.huggingface.co/info?dataset=ylacombe/google-tamil
> Include Audio features in HuggingFace.

- chart/env/prod.yaml
> fix(infra): resources optimization
